### ISSUE TITLE
[Website Request] tachidesk (media server)

### ISSUE THREAD

**Issue by Robonau** [MALSync/MALSync#1014]
## tachidesk (media server)
- Name: tachidesk
- Link: https://github.com/Suwayomi/Tachidesk-Server
- Language(s): any

## Other details
as the name suggests its tachiyomi but as a desktop app/server 
whilst tracking is planned in the future it seems vary far off looking at the development roadmap
it has an api (though not well documented, its pretty simple)

**Comment by voltrare** [comment]
these would be useful
`http://127.0.0.1:4567/api/swagger-ui`
`http://127.0.0.1:4567/api/swagger-ui#/default/getApiV1MangaWithMangaidChapterWithChapterindex`

**Comment by Pikcee** [comment]
_I just found out about the mentioned project and I'm looking forward to this very much <3_

**Comment by toprak** [comment]
any updates?

**Comment by lolamtisch** [comment]
Nobody picked it up yet ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by mbahakeskin** [comment]
https://www.youtube.com/watch?v=yBJFDOx1pUk

**Comment by Ruthalas** [comment]
@Pikcee 
Is this something you are using with tamper/violent monkey? Or adding to MalSync somehow?
I'm not entirely clear how you set this up.

**Comment by voltrare** [comment]
#2227 thanks @Pikcee!

**Comment by voltrare** [comment]
#2286
