### ISSUE TITLE
Can you add 9anime other domains?

### ISSUE THREAD

**Issue by petercontact** [MALSync/MALSync#1017]
9anime.to is down, but all the other domain of the site are working. 
9anime.me: here you can find a complete list with its domains, i find this list from old.reddit.com/r/9anime/
MALSync only has 9anime.to to its list, so for now i can't use it.

**Comment by lolamtisch** [comment]
We already support all 9anime domains listet on `.me`. 
https://github.com/MALSync/MALSync/blob/master/src/pages/nineAnime/meta.json

**Comment by petercontact** [comment]
You are right, for some reason it didn't work and i had to uninstall and install again, maybe i had an old version?
Regardless, i apologize.
