### ISSUE TITLE
[New Domain] AnimesVision changed its domain, and MAL-Sync stopped working.

### ISSUE THREAD

**Issue by IgorSal0** [MALSync/MALSync#1024]
**Describe the bug**
Before AnimesVision had the domain https://animesvision.biz and MAL-Sync worked perfectly, but now its domain is https://animes.vision and MAL-Sync stopped working.

[Google Translated]

**Additional information:**
 - Browser: Chrome
 - Type: Extension
 - Url: https://animes.vision

**Comment by lolamtisch** [comment]
This is the last time I am going to fix the page. Next time it breaks it will be removed. With the current design we would never have added support for the page as the design is stolen from another page.
