### ISSUE TITLE
Anime not being marked as completed in animixplay.to

### ISSUE THREAD

**Issue by GaganRohith** [MALSync/MALSync#1025]
**Describe the bug**
When I rate an anime and click ok on set as completed in https://animixplay.to/ it is not updating when i check my list instead its is being saved as currently watching as n-1/n episodes.

**Steps to reproduce the behaviour:**
1. Open https://animixplay.to/
2. Open any anime 
3. Click ok under start watching pop-up
4. Go to the last episode
5. Click ok on set as completed pop up 

**Additional information:**
 - Browser: chrome
 - Type: Extension
 - Url: https://animixplay.to/

**Comment by lolamtisch** [comment]
> **Animixplay player not detected (Extension only)**
> 
> You will need to add the custom domain like below. There is a button Custom Domains in the settings. You possibly need to restart the browser afterwards.
> 
> **Video Iframe** -> `https://animixplay.to/player.html`
> 
> Wiki: <https://github.com/MALSync/MALSync/wiki/Custom-Domains>

**Comment by GaganRohith** [comment]
but it is updating the episode count and also status from plan to watch to currently watching. I will try it out and let you know
