### ISSUE TITLE
Princess Connect Season 2 is being misdetected as Season 1 at 9anime

### ISSUE THREAD

**Issue by Demiko** [MALSync/MALSync#1027]
**Describe the bug**

When opening Princess Connect Re:Dive Season 2 at 9anime, MALSync detects it as Season 1 instead.

**Steps to reproduce the behavior:**
1. Open https://9anime.to/watch/princess-connect-redive-season-2.43yo
2. Check MALSync. Either the extension window, which switches to current anime, or the link in the score display, which leads to MAL page of the anime detected by MALSync.

**Additional information:**
 - Browser: Firefox
 - Type: Extension
 - Url: https://9anime.to/watch/princess-connect-redive-season-2.43yo

**Comment by henrik9999** [comment]
https://github.com/MALSync/MALSync/wiki/Troubleshooting#myanimeentry--anilist--kitsu--simkl-entry-is-not-correct
