### ISSUE TITLE
Often MALSync "syncing" bad anime

### ISSUE THREAD

**Issue by LukyMore** [MALSync/MALSync#1031]
**Describe the bug**
When I want to watch an anime that has "unclear" title like Gintama on the Crunchyroll Beta, it is divided to seasons each consisting of 50 episodes or so but when I watch the very first episode of Gintama, it registers it as Gintama', the second season, what should I do?

**Steps to reproduce the behavior:**
Go to Crunchyroll Beta
Watch very first episode of Gintama
Done, now it shows as Gintama second season in MALSync

**Additional information:**
 - Browser: Chrome
 - Url: https://beta.crunchyroll.com/watch/GRWEXZWJR/you-guys-do-you-even-have-a-gintama-part-1

**Comment by lolamtisch** [comment]
Press `C` (Or what every you set in the settings) on the video page. It should open an UI and with the correction search you can select the correct season.
