### ISSUE TITLE
animepahe Redirect Issue

### ISSUE THREAD

**Issue by raineedust** [MALSync/MALSync#1040]
**Describe the bug**
"Continue Watching" MalSync button incorrectly redirects to a private domain.

**Steps to reproduce the behavior:**
1. Open AniList anime page, such as https://anilist.co/anime/131681/Attack-on-Titan-Final-Season-Part-2/
2. Press on "Continue Watching" MalSync button
3. Get redirected to https://pahe.win/a/4657, which is a private domain and not meant for users

**What should happen:**
1. Redirected to public pages like https://animepahe.com/anime/f4565e2a-8d59-40ca-d93d-dd92009ce8b6 or https://animepahe.com/play/f4565e2a-8d59-40ca-d93d-dd92009ce8b6/260fcfc425ea4341de687582f751a6b2b36907920d7149ab950444194df25190

**Additional information:**
 - Browser: Chrome 97
 - Type: Bug
 - Url: -

**Comment by farahnur42** [comment]
@raineedust https://github.com/MALSync/MALSync/issues/840#issuecomment-914195068

**Comment by raineedust** [comment]
Gotcha. Apologies for missing out on that thread.
