### ISSUE TITLE
Chrome extension hacked? 

### ISSUE THREAD

**Issue by cwrau** [MALSync/MALSync#1045]
**Describe the bug**
Since a couple of days ago, clicking on a paused video opens random websites in new tabs; Etoro,... 

**Steps to reproduce the behavior:**

**Additional information:**
 - Browser: chrome
 - Type: extension
 - URL: 9anime.to
 - start a video, pause it, wait for a few minutes (I don't know the exact length), click the video to start playback, see a new tab open

**Comment by lolamtisch** [comment]
9anime has a lot of players with a lot of ads. That is quite normal. I would recommend you to install a better adblocker like ublock origin for example.  This has nothing to do with malsync. You could disable the extension and test it again if you want to be sure if it is not done by malsync

**Comment by farahnur42** [comment]
Also stock uBlock Origin doesn't seem to be blocking the popups however Rose's Anifiltrs does handle it - that's https://github.com/Karmesinrot/Anifiltrs @cwrau

**Comment by cwrau** [comment]
I have ublock origin installed.

I've already tried disabling MALSync, and it doesn't happen without it, thats why I opened this issue.

Please reopen, as it's still happening.

**Comment by lolamtisch** [comment]
@cwrau 
Could you join the discord server? 
https://discord.gg/cTH4yaw
