### ISSUE TITLE
How to unsync?

### ISSUE THREAD

**Issue by SuishRegmi** [MALSync/MALSync#1060]
When I installed this I loved it and made account in all 4 mal, anilist, kitsu and simkl. I have many upcoming anime in plan to watch and kitsu doesnt support upcoming anime so, it becomes wired seeing many not avaible anime in sync list. I want to unsync from kitsu only.

How to unsync from kitsu?

**Comment by lolamtisch** [comment]
Only way is to switch to kitsu once and then deauth there over the eject button and then switch back. Dont forget that background list sync will be disabled and has to be reenabled

**Comment by lolamtisch** [comment]
![image](https://user-images.githubusercontent.com/12599334/155972889-3a1cf46d-a87c-4574-9ad6-2c966e458928.png)
