### ISSUE TITLE
Discord Status Is Frozen

### ISSUE THREAD

**Issue by EnriqueBermudezz** [MALSync/MALSync#1069]
**Describe the bug**

My discord status is now frozen on a specific episode of an anime 
**Steps to reproduce the behavior:**
Unclear, but it seems that watching an episode then putting the computer to sleep may be the issue
**Additional information:**
 - Browser: 
 - Type: 
 - Url: https://www2.kickassanime.ro/anime/bleach-738982/episode-44-644464

**Comment by EnriqueBermudezz** [comment]
The formatting for the ticket was a little weird, but the extensions are Discord Rich Presense and MAL-Sync. Uninstalling and reinstalling does nothing

**Comment by lolamtisch** [comment]
Just restart Discord. Discord sometimes just gets stuck. No idea why
