### ISSUE TITLE
Notifications/Orange Remaining Chapters Bar Not Updating for Kitsu

### ISSUE THREAD

**Issue by 7910f6ba7ee4** [MALSync/MALSync#1072]
**Description:**

Orange bar that shows how far you've caught up with an anime or manga does not update passively, notifications are the same. To get the notifications and bar to update, you must click on the work in question, click out of the extension popup, then click on the extension again for it to refresh.

The progress check in settings is set to 30 min, I've attempted switching it back and forth with one hour to force update. This is only able to be replicated when using Kitsu account, works completely as intended when using Anilist or MAL. 

**System Info:**
 - Browser: Firefox 98.0.1
 - Type: Extension 0.8.20
 - Database: Kitsu

**Comment by lolamtisch** [comment]
Found the problem. Will be fixed with the next release.

**Comment by 7910f6ba7ee4** [comment]
thanks ^^
