### ISSUE TITLE
[Website Request] http://goodreads.com

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [MALSync/MALSync#1074]
### Website
Name: Goodreads.
Link: "http://goodreads.com".
Language(s): English.

**Comment by henrik9999** [comment]
They dont have an API

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@henrik9999, indeed. That was the response that I received from an issue created subsequent to this at a different repository. I consequently have suggested "https://github.com/MALSync/MALSync/issues/1287", because it appears to replace it well.
