### ISSUE TITLE
[Website Request] <http://imdb.com>

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [MALSync/MALSync#1075]
## Website
- Name: IMDb.
- Link: "http://imdb.com".
- Language(s): English and French and German and Portugese and Spanish.

**Comment by henrik9999** [comment]
We do not have the intention of adding this website

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@henrik9999, https://github.com/MALSync/MALSync/issues/1287#issuecomment-1218764261

**Comment by lolamtisch** [comment]
> We do not have the intention of adding this website
The main maintainers of the extension do not have the intention to adding it. The community (you included) is free to open a Pull request to add this functionility. 

And as far as I see it costs at least 500000$ per year to access the api.

**Comment by rokejulianlockhart** [comment]
That's a very good reason, @lolamtisch! I apologise for even suggesting it.
