### ISSUE TITLE
[Website Request] <http://reelgood.com>

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [MALSync/MALSync#1076]
## Website
- Name: Reelgood.
- Link: "http://reelgood.com".
- Language(s):

## Other details
The website appears to not be currently available, but I am confident that it shall return quickly, because I have not been notified of deliberate cessation of operation of it.

**Comment by henrik9999** [comment]
We do not have the intention of adding this website

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@henrik9999, "https://github.com/MALSync/MALSync/issues/1287#issuecomment-1218764261"?
