### ISSUE TITLE
Account switcher

### ISSUE THREAD

**Issue by dragow0lf** [MALSync/MALSync#1087]
I know we can switch the service (anilist, kitsu, mal) using a toggle available, but it would be nice to toggle accounts in same service. Example from one anilist account to another anilist account

**Comment by lolamtisch** [comment]
Why would you want that?

**Comment by dragow0lf** [comment]
for people who have multiple accounts, would be useful

**Comment by lolamtisch** [comment]
Dont see why someone wants to have multiple accounts

**Comment by lolamtisch** [comment]
Using the browsers buildin user accounts is the better way to handle this use case
