### ISSUE TITLE
Anilist Tab closes if opened from 9anime

### ISSUE THREAD

**Issue by Rennerdo30** [MALSync/MALSync#1095]
**Describe the bug**
When opening the Anilist page for the current anime on 9anime, the opened tab will be closed immediately.
Does Anilist know that the page was opened from 9anime and decides to close the tab then? 
This feature works on Crunchyroll

**Steps to reproduce the behavior:**
- Connect MALSync to Anilist
- goto 9anime and open any anime
- open the Anilist page via pressing middle mouse button while hovering over the score (as seen in screenshot)

![image](https://user-images.githubusercontent.com/9086097/163057750-7ab9299c-6182-4068-b09d-83fd54233381.png)
![chrome_MXcJ3PEt8p](https://user-images.githubusercontent.com/9086097/163058223-6fc1c91d-c7ed-4caa-abbc-c840c410ea48.gif)

**Additional information:**
 - Browser: chrome Version 100.0.4896.75 (Official Build) (64-bit)
 - Type: Extension
 - Url: any anime on 9anime

**Comment by lolamtisch** [comment]
I think this is normally because of aggressive adblocker rules.

**Comment by Rennerdo30** [comment]
Oh. You're right. If I disable uBlock Origin, the tab stays open. Then I need to find a rule to prevent this. 
Thanks for your help!
