### ISSUE TITLE
Suddenly not working on Animepahe specifically

### ISSUE THREAD

**Issue by heterostasis** [MALSync/MALSync#1097]
(sorry for the edits I pressed enter accidentally)

Hi! I don't know how else to explain this other than. I was on the last episode of a show on animepahe and I reloaded the page and suddenly the extension just wasn't working anymore. It works on other sites still. I tried clearing cookies, cache, reinstalling etc. But nothing worked. I'm using chrome

**Comment by snowbabyy** [comment]
i have the same problem too on my animepahe, it just wont load it

**Comment by henrik9999** [comment]
animepahe got rid of the ids in the html it will not be easy to fix this

**Comment by chpoit** [comment]
I'm looking at the code for animepahe, is there any reason why the Id is not just obtained from the url?

Appart from that, I found the ids in the HTML, in the sync page it's in meta <og:url>

I'll create a PR a little later

**Comment by henrik9999** [comment]
> I'm looking at the code for animepahe, is there any reason why the Id is not just obtained from the url?
> 
> Appart from that, I found the ids in the HTML, in the sync page it's in meta og:url
> 
> I'll create a PR a little later

I already fixed it in #1099
Also the IDs in the url are Session based they stop working after a while

**Comment by chpoit** [comment]
Alright, hadn't seen that PR

**Comment by lolamtisch** [comment]
We have a db for matching ids. Animepahe was a part of it, but obviously not anymore.

With the session ids you would need to correct an entry every time it runs out, incase it gets recognized wrong. A stable and permament Identifier is quite important.

**Comment by evoandroidevo** [comment]
`<meta name="id" content="4718">
<meta name="anidb" content="16947">
<meta name="anilist" content="140960">
<meta name="ann" content="24917">
<meta name="kitsu" content="45398">
<meta name="myanimelist" content="50265">`
the ids were added to the header
