### ISSUE TITLE
Adds a note in anilist

### ISSUE THREAD

**Issue by Alpha11510** [MALSync/MALSync#1102]
Hi, There is a bug (may note be a bug) that has been really annoying me. It is that Whenever I update an anime using MAL-Sync it automatically adds this note on **anilist** ![image](https://user-images.githubusercontent.com/94781213/164708785-b42ddc7e-ccae-4de0-b078-62194a335ba7.jpeg)  

Please fix this as I primarily use notes to see which anime I should rewatch 
Thank you,

**Comment by farahnur42** [comment]
@Alpha11510 Untick this 
![image](https://user-images.githubusercontent.com/37258115/164708936-5e6c37f5-55c4-4fe9-945a-aaeaa307706d.png)
and then 
![image](https://user-images.githubusercontent.com/37258115/164708965-91b5f1db-ac2e-4c55-9bbb-d6523cb4b51c.png)
to clean them up.

**Comment by Alpha11510** [comment]
> @Alpha11510 Untick this 
> 
> ![image](https://user-images.githubusercontent.com/37258115/164708936-5e6c37f5-55c4-4fe9-945a-aaeaa307706d.png)
> 
> and then 
> 
> ![image](https://user-images.githubusercontent.com/37258115/164708965-91b5f1db-ac2e-4c55-9bbb-d6523cb4b51c.png)
> 
> to clean them up.
> 
> 

This quick 😳
Thanks ig
