### ISSUE TITLE
Add continue watching to all anime in 'watching'

### ISSUE THREAD

**Issue by nigelwarning** [MALSync/MALSync#1103]
Hello, first of all I love this addon. It works great with anilist.

<img width="1451" alt="Screen Shot 2022-04-23 at 17 11 31" src="https://user-images.githubusercontent.com/51288761/164912091-6c107438-4c20-42e0-8cad-e1ffcb0ee36b.png">

As you can see, there only appears a 'continue watching' icon on the series I watched the latest, I would love to see a option to have this for all the shows in my 'watching' list. Would be much quicker for me to switch between series!

Thanks :D

**Comment by henrik9999** [comment]
The icon shows if you watched a episode before with the addon so just watch something and then the icon will appear for the show
