### ISSUE TITLE
[Question] Where does the "Last chapter released XX days ago" comes from?

### ISSUE THREAD

**Issue by mackson888** [MALSync/MALSync#1108]
Some manga a read like Grand Blue and Your Throne says there are more chapters available than any source I know of (including Fast Pass on Webtoons), and on the flip side, some have new chapters but the "last released" is way behind for example Magi Lumiere and Mariagetoxin (both mangaplus' titles), and in both cases I don't get a notification when new chapters are actually released. 

So I've been wondering, where does this info comes from? Is it a specific source? If so, is it possible for the used to blacklist said source and/or get it from somewhere else?

**Comment by lolamtisch** [comment]
For anime we directly check torrents.
For manga we check mangadex, mangasee and manganato using the relations that are shown on the sidebar on mal. If there is something wrong just go to the page and correct it in MALsync.

Grand Blue and Your throne seems to be correct on my end. But you are right Magi Lumiere is wrong and Mariagetoxin still does not have any relation to mangadex etc.

There is no way to filter out specific sources, as would just complicate everything, we have more a focus to provide info for different subs and dub languages. We are currently working on a rewrite, which should make it more reliable for cases like for Magi Lumiere.

**Comment by mackson888** [comment]
Okay. Thanks for the clarification!
