### ISSUE TITLE
I got my IP banned for some reason

### ISSUE THREAD

**Issue by Outcast-X** [MALSync/MALSync#1110]
So I was just watching anime and when I reloaded my page, it said your IP is banned on MAL and since then the automatic updating for episodes has stopped. For some reason, it can still automatically update manga (I use Chrome with the MAL Sync extension btw).

**Comment by lolamtisch** [comment]
Do you use a vpn? MAL often bans VPN IPs. 
Does it still happen or was it just that one time?

**Comment by Outcast-X** [comment]
I do use a VPN and it happened while I was using it. I've just checked with the VPN off and it does still work but not on every site for some reason

**Comment by lolamtisch** [comment]
Check if there are new domains to add on this page. (9anime, gogoanime)
https://malsync.moe/pwa/#customDomains

**Comment by PeHeReBe** [comment]
happend me too  just use a difrent vpn ore try reconect to your vpn if someone using the same vpn there is a chance that if they do shit on the side the ip is bannen (multiple vpn ip´s from the opera vpn are banned on some sides)

**Comment by aasutossh** [comment]
I don't use VPN, was watching on animixplay, was working fine till just a minute ago. Now it says my IP is banned, change your IP or wait for it to be unbanned.
