### ISSUE TITLE
Not working on Crunchyroll Beta

### ISSUE THREAD

**Issue by Yeventry** [MALSync/MALSync#1119]
When I first downloaded the extension it worked perfectly fine wherever I tried to use it. However, it has stopped working on Crunchyroll and the issue seems to stem from it not being able to detect what anime/episode I am watching, among possible other issues that are not allowing it to know what I'm watching and sync that to my MAL.

**Comment by lolamtisch** [comment]
What browser? Example link where it does not work?

**Comment by Yeventry** [comment]
Google Chrome,  and here is one page where it isn't working: https://beta.crunchyroll.com/watch/GK9U353QJ/jolly-times-at-the-river
Doesn't work for, at the very least, any of the series I have tried watching on CR.
