### ISSUE TITLE
Not Skipping opening in 9 anime

### ISSUE THREAD

**Issue by giovanny-martinez** [MALSync/MALSync#1128]
**Describe the bug**

The opening is not skipped when i skip it but it works on other websites

**Steps to reproduce the behavior:**
go to the website press ctrl+rightarrow

**Additional information:**
 - Browser: 
chrome
 - Type: 
Extension
 - Url: 9anime.id

**Comment by henrik9999** [comment]
Check if on this page new domains need to be added and restart. If it still does not work please post the url here to the ep.
https://malsync.moe/pwa/#customDomains

**Comment by giovanny-martinez** [comment]
all of the anime i've tried do not work i even tried another browser and it still won't work https://9anime.to/ nor https://9anime.id/
