### ISSUE TITLE
Userscript not working since v0.8.20 but FF extension does

### ISSUE THREAD

**Issue by quietlystorming** [MALSync/MALSync#1142]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior
Use MAL-Sync
## Current Behavior
No MAL-Sync
## Relevant settings
N/A

## Context (Environment)

FF 100.0.2, Win8.1x64

I usually use the userscript via Tampermonkey. When I first upgraded from 0.8.19 to 0.8.20, MAL-Sync didn't work at all, no miniMAL on any sites, nothing. I downgraded and hoped I could get away with being lazy and not reporting it myself. Now that 0.8.21 is out, I notice that it still isn't working for me. The FF add-on version of 0.8.21 works though. I haven't tried with the add-on version of 0.8.20.

**Comment by lolamtisch** [comment]
I have no problem running 0.8.21 on Tampermonkey firefox. On what page exactly does it not work? I tested it on mangadex. Do you see anything if you open the console (f12 and then console tab)?

**Comment by quietlystorming** [comment]
It doesn't work on MAL, crunchyroll, 9anime, gogoanime... nowhere I try. Checking the console, there's an error, "Uncaught (in promise) InternalError: too much recursion". I'm not sure if/how I can paste the whole thing here with the formatting intact. When I view source in debugger, it points to line 11387:

`inlineScriptSource = pageSource.replace(inlineScriptSourceRegExp, "$1").trim());`

**Comment by lolamtisch** [comment]
Can you sent a screenshot?

**Comment by quietlystorming** [comment]
![mal-sync 01](https://user-images.githubusercontent.com/15165087/171691573-138c87ed-18ef-47d9-b6c1-54582c14fe03.JPG)
![mal-sync 02](https://user-images.githubusercontent.com/15165087/171691585-98fbcde2-fac3-4fb3-90a7-d8d49a9dcb79.JPG)

**Comment by lolamtisch** [comment]
Could you join our discord server as it is faster there to debug
https://discord.gg/cTH4yaw

**Comment by quietlystorming** [comment]
Sorry, meant to get back to this. Discord seems to be not like me for some reason, they don't send me the verification link at all despite multiple attempts. I'd used it once or twice before without making an account and there was always some hoop to jump through but now it's just not cooperating.

**Comment by quietlystorming** [comment]
I (finally) made it to discord made it to discord and can help with this.
