### ISSUE TITLE
css is breaking in safari Minimal (tamper monkey)

### ISSUE THREAD

**Issue by DrSHRI19** [MALSync/MALSync#1144]
### Describe the Bug

Both version 0.8.20 and  0.8.21 are breaking in css department while using in safari browser via tamper monkey user script.
it have 3 problems.

1. All icons (like back and search) are replaced with text.
2. No favcones in userecript (so malsync icon look like blue box with ? in middle.)
3. Does not load MAL (both full and hybrid).

Please solve these issues ASAP

### Steps to reproduce the behavior

while visiting Mangadex.org I had this issue.
no anime & manga sites have this issue. 

### Browser

safari

### Type

Userscript

### URL

mangadex.org

**Comment by lolamtisch** [comment]
It most like just gets blocked by ublock.

We have a filter that should fix that
https://github.com/Karmesinrot/Anifiltrs#readme

**Comment by DrSHRI19** [comment]
> It most like just gets blocked by ublock.
> 
> We have a filter that should fix that https://github.com/Karmesinrot/Anifiltrs#readme

no I don't have block or any adblocker installed, (only single extension tamper monkey with 1 script malsync)

**Comment by lolamtisch** [comment]
None of us has a Mac. So we can unfortunately not help you with that.

**Comment by lolamtisch** [comment]
We were able to find the problem with another user. The problem is mangadex has an CSP header set. This blocks external resources. This means there is no fix as it works as intended by mangadex. So there is no way for the userscript around that.
