### ISSUE TITLE
Create MiniMal launcher for Safari

### ISSUE THREAD

**Issue by DrSHRI19** [MALSync/MALSync#1145]
### Suggestion

Unlike Chrome and Firefox; Safari don't have mail launcher and instead have to relay on the  user script like Underscript which didn't work and Tamper monkey which works but none the less it is paid.

So please Create MiniMal launcher for Safari so it would be better for the safari users and save the lot of space by uselessly installing other browsers for only single function (watching anime and manga).

**Comment by henrik9999** [comment]
No
