### ISSUE TITLE
Installing add-on using the Userscript in Safari's macOS

### ISSUE THREAD

**Issue by criccadamus** [MALSync/MALSync#1159]
### Suggestion

Hello!,

I'd like to ask if its possible to install this add-on using the same method BetterTTV uses with Safari using TamperMonkey (or another Userscript solution)

This is the script BetterTTV uses: https://nightdev.com/betterttv/other/betterttv.user.js

**Comment by henrik9999** [comment]
We have a Userscript version
https://github.com/MALSync/MALSync/releases/latest/download/malsync.user.js
Only works with tampermonkey on safari

**Comment by criccadamus** [comment]
Tested and working! Thank you very much!
