### ISSUE TITLE
No anilist link on mal

### ISSUE THREAD

**Issue by venkat2305** [MALSync/MALSync#1160]
### Describe the Bug

the button on mal pages to go to anilist pages is missing in edge, but its there in chrome. plesae fix this

### Steps to reproduce the behavior

open edge 
check any anime page on mal
do the same but on chrome
![image](https://user-images.githubusercontent.com/55329452/174328385-13eacf03-efab-4143-962f-a3ff5fe33717.png)

### Browser

edge

### Type

Extension

### URL

https://myanimelist.net/anime/5114/Fullmetal_Alchemist__Brotherhood

**Comment by henrik9999** [comment]
also privacy and adblock extensions and whatever often remove them so try disabling those

**Comment by venkat2305** [comment]
Thanks for the help. It's working now
