### ISSUE TITLE
mal sync not working

### ISSUE THREAD

**Issue by Key-explanation** [MALSync/MALSync#1162]
### Describe the Bug

mal sync extension is not working on vidstream player on 9anime

### Steps to reproduce the behavior

![Capture](https://user-images.githubusercontent.com/103259523/174435518-8866213b-bb05-4cb1-b0b8-093ed8a323f3.PNG)

### Browser

chrome

### Type

Extension

### URL

www.9anime.id

**Comment by lolamtisch** [comment]
Check the page below if there are new permissions to add. If yes add them and restart the browser then it should work again.
https://malsync.moe/pwa/#customDomains

**Comment by Key-explanation** [comment]
It worked, thanks.
