### ISSUE TITLE
Episode Number for My Dress-Up Darling is wrong

### ISSUE THREAD

**Issue by SuperStormer** [MALSync/MALSync#1172]
### Describe the Bug

Episode count shows 8 episodes released, but in reality, all 12 have been released.
![image](https://user-images.githubusercontent.com/41648788/174508245-14463512-9a11-4de3-92c9-1dcb2d362700.png)

If you look at DevTools, it looks like it's tracking the wrong release?
![image](https://user-images.githubusercontent.com/41648788/174508321-dfa83da2-371a-474b-868b-0c6405c66bfa.png)

### Steps to reproduce the behavior

1. Enable "Estimate episode number"
2. Go to the linked URL
3. Observe bug

### Browser

Chrome

### Type

Extension

### URL

https://myanimelist.net/anime/48736/Sono_Bisque_Doll_wa_Koi_wo_Suru

**Comment by lolamtisch** [comment]
I changed a few things that hopefully makes it less likely to happening again for other anime.

**Comment by SuperStormer** [comment]
can't be repro'd anymore
