### ISSUE TITLE
"Recently Updated By" inserted in the wrong spot

### ISSUE THREAD

**Issue by SuperStormer** [MALSync/MALSync#1173]
### Describe the Bug

![image](https://user-images.githubusercontent.com/41648788/174509114-8700749d-3007-4547-b647-330dea02534f.png)

More Reviews button is now in the wrong spot (it should be inline with the "Reviews" header)

### Steps to reproduce the behavior

1. go to any anime that your friends have watched
2. observe bug

### Browser

Chrome

### Type

Extension

### URL

https://myanimelist.net/anime/1689/Byousoku_5_Centimeter

**Comment by SuperStormer** [comment]
I think it should work if you insert the section at the beginning of the div.

**Comment by SuperStormer** [comment]
ie. https://github.com/MALSync/MALSync/blob/b21355c852735dc659ea37d7fa5c15c1f3126a3d/src/myanimelist/myanimelistClass.ts#L547
should be 
```js
const position = $('h2:contains(Reviews)').prev();
```

though I haven't tested it.

**Comment by lolamtisch** [comment]
👍
