### ISSUE TITLE
Multi-tracker Sync

### ISSUE THREAD

**Issue by lasersPew** [MALSync/MALSync#1220]
### Suggestion

If mal-sync is logged into multiple sources, sync entries to other trackers.
Since there's rate limits, you can push entries to one tracker and when a specific limit exceeds, for example, 20 entries or 7 days, offload entries to other trackers.

Also, check if entries are the same throughout the sources.
1. If the entry is in tracker A and its not on tracker B, add the entry on tracker B.
2. If the entry in tracker A has more data(for example, theres watching/reading marker) than tracker B, inform the user next time they open the extension and modify the entry on tracker B.
3. If there's a conflict between two trackers(example, there's rewatch marker on tracker A whereas tracker B has no such marker),ask the user before modifying the data.

## **Why this helps?**

Its been a pain to me(and others) who has multiple tracker accounts and its worse to those that only use MAL-sync in their lives(i use Aniyomi on my phone so some way or another, i get to backup majority of the series i watch/read though i usually watch/read through my laptop/browser due to Aniyomi's shitty player design imo and not syncing items when i manually mark them as read/watched) and its definitely a nightmare to those who manually update their tracker lists. I also think that this is a gamechanger to your project and a huge lifesaver to many users of MAL-sync

**Comment by henrik9999** [comment]
https://github.com/MALSync/MALSync/issues/1092#issuecomment-1095984452
