### ISSUE TITLE
new 9anime design

### ISSUE THREAD

**Issue by Key-explanation** [MALSync/MALSync#1222]
### Describe the Bug

Normally, there would be a layout showing status, episode number, and score of the anime. But it is not showing

### Steps to reproduce the behavior

_

### Browser

chrome

### Type

Extension

### URL

www.9anime.id and www.animixplay.to

**Comment by Key-explanation** [comment]
Will it be fixed?

**Comment by Key-explanation** [comment]
Now that 9anime has permanently updated their page, when will I be able to use malsync?

**Comment by commons12** [comment]
indeed i dislike the new sute to be honest but I hope to extension is updated as it keeps me up to date

> Now that 9anime has permanently updated their page, when will I be able to use malsync?
