### ISSUE TITLE
Cant skip opening on 9anime.

### ISSUE THREAD

**Issue by DeezPeeNUTZ** [MALSync/MALSync#1258]
### Describe the Bug

Cant skip opening on 9anime.

### Steps to reproduce the behavior

ctr + left arrow

### Browser

chrome

### Type

Extension

### URL

https://9anime.id/home

**Comment by lolamtisch** [comment]
9anime blocks the current shortcut. Just set it to something else in the settings and it should work.

![image](https://user-images.githubusercontent.com/12599334/181620840-bf068761-0e72-4e2a-a6dc-a838bab4f51d.png)
