### ISSUE TITLE
Ask for browser permissions when they are needed, not on each extension update

### ISSUE THREAD

**Issue by itslychee** [MALSync/MALSync#1269]
### Suggestion

It's really annoying when the extension asks you for permission for 100+ websites in order for it to function correctly on those sites. I'm pretty certain that most users only go to 2-4 websites in total while they use MAL-Sync for tracking.

**Comment by farahnur42** [comment]
@itslychee That's not up to MALSync, it's just how browsers handle site permission additions (which is inevitable given that sites change, add more video players, change their video player urls, new sites get added and so on).

**Comment by lolamtisch** [comment]
Exactly. It is not in our hands and we can not change it. The solutions are unreliable (custom domain) or we need to inject into all pages, including unrelated pages like Google PayPal etc and obviously that is not an option.

**Comment by itslychee** [comment]
wow that sucks, thanks for the clarification
