### ISSUE TITLE
Add a toggle to swap the Discord Rich Presence report of show title and content type/MALSync name

### ISSUE THREAD

**Issue by muuyo** [MALSync/MALSync#1270]
### Suggestion

As it stands, I can either have it show "Playing Anime" or "Playing MAL-Sync". Any chance this could be made a toggle so it could show "Playing [title of content]", and then I can set the main text in the detailed Rich Presence report to be MALSync?

**Comment by farahnur42** [comment]
As far as I know that's a Discord-side limitation in terms of what you can register (and then change out the name for) in Rich Presences so not really.  (There's also a similar reason why it says Playing instead of Watching or Reading)

**Comment by lolamtisch** [comment]
Yeah. You would need to create a new project in discord for every anime and that not really possible.
