### ISSUE TITLE
Tracking anime not on my list

### ISSUE THREAD

**Issue by Key-explanation** [MALSync/MALSync#1274]
### Describe the Bug

Just like the title says, malsync automatically tracks anime not on my list

### Steps to reproduce the behavior

.

### Browser

chrome

### Type

Extension

### URL

www.9anime.id

**Comment by henrik9999** [comment]
what?

**Comment by Key-explanation** [comment]
Consider an anime that is not on your list. when watching that said anime malsync attomatically tracks and add it to the list as 'watching'.
