### ISSUE TITLE
Comick

### ISSUE THREAD

**Issue by Pikcee** [MALSync/MALSync#1282]
### Describe the Bug

Mal-Sync stopped working at ComicK since 3 days ago, if you started to read a manga it keep tracking the progress without any issues,
only injecting the extension related section? buttons? _(Idk what should this be called)_ to the page fails, 
### Steps to reproduce the behavior

Just check any manga

### Browser

Firefox

### Type

Extension

### URL

https://comick.fun

**Comment by henrik9999** [comment]
fixed

**Comment by Pikcee** [comment]
For some reason it's working now? I asked on ComicK subreddit if it was only me who had this issue and the developer probably saw it and reverted the changes he did to the page structure, it's just a guess so, well for now it's working if it broke again I'll reopen this issue again,
also to everyone who's involved in this masterpiece developing I'd like to express my thanks and gratitude :3
