### ISSUE TITLE
[Website Request] oku.club

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [MALSync/MALSync#1287]
### Website
Name: Oku.
Link: "http://oku.club".
Language(s): English.

### Other details

If "https://github.com/MALSync/MALSync/issues/1074" is impossible to achieve because of its [lack of API](https://github.com/MALSync/MALSync/issues/1074#issuecomment-1218486598), this should replace it.

**Comment by henrik9999** [comment]
We do not have the intention of adding this website

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@henrik9999, why? Surely some rationale is necessary.

**Comment by rokejulianlockhart** [comment]
Will you please tell me why this one was dismissed? I don't understand why every suggestion of mine was immediately dismissed, I don't care about them as much as this one – this is the only way for me to combine my regular books with my manga.

**Comment by lolamtisch** [comment]
@rokejulianlockhart This is a webextension. There technically no way to add support for an app.

**Comment by rokejulianlockhart** [comment]
@lolamtisch, oku.club is a website. “oku.club” is literally its domain. Are you able to clarify?

**Comment by lolamtisch** [comment]
The only thing I see when I open is to install the app. The explore tab is pointless as they dont even give you a search.

Either way I dont see any api docs.

**Comment by rokejulianlockhart** [comment]
@lolamtisch, I have asked @joealcorn of @readng at http://twitter.com/messages/187223083-3782186368 whether an API is available, and shall forward the response that he provides if it is useful.

I'm not certain of why you appear to be unable to access the website normally. Have you tried authenticating? (You may need to register to gain a useful interface.)

**Comment by lolamtisch** [comment]
hmm yeah could be that you need to make an account to access the full interface. Which would be dumb, but is probably to hide that they make money using the data from other people (Goodreads). No idea if that really is the case but I am not going to make an account just to find out. In general the branding is quite bad I have still no idea what the page does.
Another thing is we additionally need the malids which is even more difficult without a public data set. So it is very unlikely that this going to be added.

The twitter link sends me to the home page. But no idea could be that I have no twitter account.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/MALSync/MALSync/issues/1287#issuecomment-1385825927

@lolamtisch, I linked to a DM. That's why you couldn't see it. The darn developer still hasn't bothered to respond though, so it doesn't matter.
