### ISSUE TITLE
Not able to skip opening

### ISSUE THREAD

**Issue by Key-explanation** [MALSync/MALSync#1289]
### Describe the Bug

I can't skip opening even after pressing ctrl+right arrow. The only thing i changed was the skip length setting it to 80sec

### Steps to reproduce the behavior

.

### Browser

chrome

### Type

Extension

### URL

9anime

**Comment by lolamtisch** [comment]
Please add more informations. URL to the episode, what player and did you add all missing custom domain permission?

**Comment by Key-explanation** [comment]
URL-https://9anime.id/watch/phantom-of-the-idol.n330m/ep-8

I used both vidstream and mycloud player; both are not working

I add all the custom domain

**Comment by lolamtisch** [comment]
Duplicate #1258
