### ISSUE TITLE
Auto tracking the next episode as watched, even though I haven't watched it.

### ISSUE THREAD

**Issue by Key-explanation** [MALSync/MALSync#1302]
### Describe the Bug

It happens when 'Auto next' is toggled on. If you watch, like say, the first episode of an anime and malsync have successfully tracked it. After watching the first episode the player automatically switches to the next episode. Here malsync tracks the next episode as watched  even though I haven't watched it.

### Steps to reproduce the behavior

1. Watch an episode until malsync tracks the episode as watched
2. Then switch to the next episode
3. Malsync will consider the next episode as watched

### Browser

chrome

### Type

Extension

### URL

9anime.id

**Comment by lolamtisch** [comment]
Are you sure you dont have the script set to instant sync?

**Comment by Key-explanation** [comment]
I use the extension

**Comment by lolamtisch** [comment]
Are you sure you dont have the extension set to instant sync?

**Comment by Key-explanation** [comment]
Is this the one you were asking?
![Capture](https://user-images.githubusercontent.com/103259523/187664355-d8e08087-b56a-425a-9567-3100b245b41f.PNG)

**Comment by Key-explanation** [comment]
While watching anime I noticed something, don't know if it got something to do with it. As the site loads the next episode, the player still remains from the previous episode for some seconds.

**Comment by Vankka** [comment]
With Anime sync on Video,
on Crunchyroll, when going to the next episode eg. 5 -> 6 (auto play or manually) right as the episode switches it will *sometimes* mark episode 6 as watched,
on HiDive when going to the next episode it will do the same but every time (does not happen when going to a episode from the home page, for example)
also on HiDive if you watch the most recent episode of a airing anime and wait for the auto play at the end of the episode, and it says "Episode not available" (or whatever) MALSync will mark the next episode (the one that hasn't aired yet) as watched.

I'm guessing that there's a moment that MALSync still thinks the player is at the timestamp you were at the end of the last episode but is already 'tracking' the next episode when switching episodes
