### ISSUE TITLE
Doesn't recognize anime titles at all on AnimeDao

### ISSUE THREAD

**Issue by wondrousweeb** [MALSync/MALSync#1312]
### Describe the Bug

Whenever I open a title on AnimeDao and tap on malsync extension, it does not show which title I am on and thinks it should make a local save, although the anime is very clearly on MAL. 
![image](https://user-images.githubusercontent.com/70597482/191298032-7e68d095-2964-4cc3-bc70-4683ae670148.png)
![image](https://user-images.githubusercontent.com/70597482/191298085-f6e85593-814a-4202-b1e1-f35bf5cba0ac.png)

Moreover, due to this reason, it does not update the anime as I watch the episodes.
It doesn't even show the small banner on the top that shows how many anime I've watched.

### Steps to reproduce the behavior

1) Tap on any anime title
2) Tap on MALsync extension

### Browser

Microsoft Edge

### Type

Extension

### URL

animedao.to

**Comment by henrik9999** [comment]
Duplicate  #1308
