### ISSUE TITLE
Posable bug fix for 9anime fullscreen

### ISSUE THREAD

**Issue by EmFresh** [MALSync/MALSync#1313]
### Describe the Bug

Usually when an episode ends and it auto transitions to a new episode it never goes to fullscreen when the setting is turned on. I think I found an odd fix that seems to work on Opera GX (and probably other chromium browsers). When I skipped at the end of an episode, ( if the skip time would send me further than the end of the video) when the next episode popped up it was sent into fullscreen. I'm not sure why this works but if you could figure it out and implement this that would be gr8.

### Steps to reproduce the behavior

1. turn on the fullscreen setting and turn off the auto next setting in mal-sync
2. open any multi-episode anime in 9anime
3. make sure the auto next feature is on in 9anime (under the video)
4. at the end of the anime when there are 2 to 3 seconds left, hit the skip button (right arrow)
5. wait for the next episode to play and it should go to fullscreen

Note: if the next episode stalls it might not work but it doesn't happen much for me

### Browser

Opera GX

### Type

Extension

### URL

9anime

**Comment by henrik9999** [comment]
https://github.com/MALSync/MALSync/issues/1307#issuecomment-1257041511

**Comment by EmFresh** [comment]
whoops didn't see you sent a reply to the other one, my bad
