### ISSUE TITLE
Detection of local files

### ISSUE THREAD

**Issue by rollingmoai** [MALSync/MALSync#1318]
### Suggestion

Detect anime playing locally from media players like VLC, MPC-HC (Windows), or MPV similar to [taiga](https://github.com/erengy/taiga)'s functionality

**Comment by henrik9999** [comment]
Not possible and out of range for this project just use taiga

**Comment by rollingmoai** [comment]
Taiga is Windows only so it would be great to have this feature on MALSync.

**Comment by henrik9999** [comment]
> Taiga is Windows only so it would be great to have this feature on MALSync.

https://github.com/z411/trackma
