### ISSUE TITLE
[Website Request] <BiliBili>

### ISSUE THREAD

**Issue by lordxd588** [MALSync/MALSync#1320]
### Website name

Bilibili

### Website link

https://www.bilibili.tv/en

### Website language(s)

English, Thai, Vietnamese, and Bahasa Indonesia

### Other details

This website is free and has copyrighted sources. It's also legal because the content they are streaming are licensed by Muse Communication Co. Ltd.

**Comment by henrik9999** [comment]
Duplicate #979
