### ISSUE TITLE
AsuraScans no longer tracks

### ISSUE THREAD

**Issue by ReverseSync** [MALSync/MALSync#1331]
### Describe the Bug

MAL-Sync no longer tracks in AsuraScans after their domain name change https://www.asurascans.com -> https://asura.gg/

### Steps to reproduce the behavior

Visit asurascans website

### Browser

FireFox

### Type

Extension

### URL

https://asura.gg/

**Comment by farahnur42** [comment]
@ReverseSync Open Settings -> Custom Domains - the new domain is already listed there, add all the missing domains and accept the browser permission popup. Additionally, it's fixed for next release

**Comment by lolamtisch** [comment]
Check if there are new permissions on the page below. Try to remove them all once and re add them.
https://malsync.moe/pwa/#customDomains

**Comment by ReverseSync** [comment]
Sorry for not noticing the custom domains feature. Working as intended now after adding the domains thanks for the help!
