### ISSUE TITLE
Wrong episode count Watch2gether on 9anime

### ISSUE THREAD

**Issue by BernardoKaluza** [MALSync/MALSync#1334]
### Describe the Bug

Pretty much the title, I've noticed that when watching an anime through 9anime's Watch2gether feature, the anime episode count is wrong when it updates, it did the same to all other anime I watched via 9anime's Watch2gether feature.

I looked into the code that gets the episode number if we're in a Watch2gether room, 
https://github.com/MALSync/MALSync/blob/e1ec7918f9ce9404250ee52ab3392e498e4d0fad/src/pages/nineAnime/main.ts#L37
There's a mistake in the regex expression, as it doesn't match the number after the "/", it would parse 12 from "EP 1/2" an easy fix would be to drop the regex and do this instead:
```js
parseInt(j.$('div.info span.current-episode-name').text());
```

### Steps to reproduce the behavior

1-Create/join a room
2- trigger the episode update

### Browser

OperaGX

### Type

Extension

### URL

https://9anime.to

**Comment by henrik9999** [comment]
its already fixed in my pr https://github.com/MALSync/MALSync/pull/1290/commits/2d7e522b44248811a58e1d60a245bfd9cee02c98

**Comment by BernardoKaluza** [comment]
oh my bad only looked into issues
