### ISSUE TITLE
Asura Scans isn't working

### ISSUE THREAD

**Issue by ronaldolaj** [MALSync/MALSync#1337]
### Describe the Bug

Maybe because a new domain "asura.gg" but i can't update my mangas

### Steps to reproduce the behavior

- Visit the asura scans website and open any entry

### Browser

Google Chrome

### Type

Extension

### URL

https://asura.gg/

**Comment by farahnur42** [comment]
@ronaldolaj Go to Settings -> Custom Domains and add the missing domains (and accept when it asks for permission), this domain change has been included in that list for a while already.

**Comment by ronaldolaj** [comment]
@farahnur42 Thank you! Checking right now :)
