### ISSUE TITLE
Asura Scans site new URL

### ISSUE THREAD

**Issue by arthurmessi** [MALSync/MALSync#1346]
### Describe the Bug

The Asura Scans site has change from asurascans.com to asura.gg, the extension need to be updated. The site content does not seam to have changed, just the URL.

### Steps to reproduce the behavior

Site has changed URL

### Browser

Chrome

### Type

Extension

### URL

assura.gg

**Comment by henrik9999** [comment]
https://github.com/MALSync/MALSync/issues/1337#issuecomment-1275237737
