### ISSUE TITLE
Not working on Manganato

### ISSUE THREAD

**Issue by korshar** [MALSync/MALSync#1364]
### Describe the Bug

Some manga main page on Manganato now follow the link https://chapmanganato.com/ instead of https://manganato.com/
And all chapters are now opened in https://chapmanganato.com/

### Steps to reproduce the behavior

This manga page follows the new non supported url:
https://chapmanganato.com/manga-be978987

There still exists the old supported url for the manga main page but when opening a chapter it redirects for the new non supported url:
https://manganato.com/manga-kv987378
https://chapmanganato.com/manga-kv987378/chapter-1

### Browser

Firefox

### Type

Extension

### URL

https://chapmanganato.com/manga-be978987

**Comment by henrik9999** [comment]
update malsync extension
