### ISSUE TITLE
Hide score on "watching" list

### ISSUE THREAD

**Issue by kotx** [MALSync/MALSync#1365]
### Suggestion

![image](https://user-images.githubusercontent.com/33439542/199036419-57ce744d-68c1-4a60-86e7-c967519b6339.png)
There's a huge empty space on the right and I assume most people don't rate anime until after they've seen it completely.
You could also replace no score with a "-" or "-/10", etc.

**Comment by GeorgyBuns** [comment]
Initially there were dashes, but I dislike that approach because it just clutters the UI with unnecessary symbols. We’ll consider changing it somehow, or even return the dashes.
