### ISSUE TITLE
Button for rich presence not working on new update

### ISSUE THREAD

**Issue by DeaD7777** [MALSync/MALSync#1397]
### Describe the Bug

apparently the "watch anime" button functionality on discord is not working, the button doesn't seem to work

### Steps to reproduce the behavior

I'm using kitsu, the expected when clicking the rich presence button would take to the kitsu anime page or the website i'm watching, but apparently it doesn't work

Sorry for my bad english

### Browser

Chrome

### Type

Extension

### URL

https://animes.vision/animes/kyoukai-senki/episodio-08/legendado

**Comment by lolamtisch** [comment]
Only other people can Klick on the button. We don't know why discord did it like that
