### ISSUE TITLE
Horizontal scroll bar, window not big enough for content

### ISSUE THREAD

**Issue by Pyroptical** [MALSync/MALSync#1407]
### Describe the Bug

When viewing the menu on both the setting panel and the anime list the window is slightly too small for the content causing a horizontal scroll bar to show, using the extension pop up menu doesn't seem to affect the window size when in that mode, only when in "open in a separate window"

![image](https://user-images.githubusercontent.com/29610877/200137382-fa61b515-9cbf-444c-add7-5ef7eb7fd22e.png)

![image](https://user-images.githubusercontent.com/29610877/200137393-74e2bf95-10be-4d86-9607-eaa04dab8b51.png)

### Steps to reproduce the behavior

simply open the plug-in, Have a 2560x1440 monitor but the Firefox window size doesn't seem to affect this

### Browser

Firefox 106.0.5 (64-bit)

### Type

Extension

### URL

moz-extension://58513dda-a983-4b30-92aa-7005bb2cc8c4/popup.html#/book/anime/1

**Comment by Demiko** [comment]
It seems to occur on the pages that require a vertical scrollbar to appear. On the short settings pages, where all the content is contained in the initial window both the vertical scroll bar and the horizontal one are absent.
