### ISSUE TITLE
Sort by Release Date

### ISSUE THREAD

**Issue by evka745** [MALSync/MALSync#1414]
### Suggestion

Sorting anime & manga by when they're next going to be released would be a good feature, I have transferred from AniMouto to MALSync & this is a feature I very much miss.
<img width="614" alt="Screen Shot 2022-11-05 at 8 57 12 PM" src="https://user-images.githubusercontent.com/82726788/200149036-6cddbf66-7ae6-436e-b6f8-da1b79bf99fd.png">

**Comment by lolamtisch** [comment]
The Default sorting for anime in "watching" is already sorted like that.  
First it shows the anime that are currently aring and have an unwatched ep (longest time from release first). Then it sorts the airing by shortest time to release.

![image](https://user-images.githubusercontent.com/12599334/200161304-ea402839-6de2-4cbf-8228-2c01672e0d83.png)

For manga there is no sorting like that, as it does not really work without schedules. But there is a sorting to put entries with unreaded chapters on the top

![image](https://user-images.githubusercontent.com/12599334/200161673-aba6b5d9-1271-4412-83e5-5a999412e73e.png)

Is that what you where expecting or is there something you would like different?

**Comment by evka745** [comment]
Sorry, I didn’t notice that & I think that’s pretty good enough. But one that just sorts by release first to longest could also be nice, not taking into account how many eps you’ve watched and etc. From the image you sent, chainsaw first, kage no second, tensei 3rd & spy family 4th and etc.
