### ISSUE TITLE
View Titles in Japanese when Clicked

### ISSUE THREAD

**Issue by evkaw** [MALSync/MALSync#1416]
### Suggestion

I believe it would just be a lot more consistent if either both titles were in English or in Japanese. Thanks!
<img width="263" alt="Screen Shot 2022-11-05 at 9 04 33 PM" src="https://user-images.githubusercontent.com/82726788/200149221-745a996c-f873-4f4f-9d1a-a05947f8b080.png">
<img width="526" alt="Screen Shot 2022-11-05 at 9 04 46 PM" src="https://user-images.githubusercontent.com/82726788/200149225-67c9308d-6e0d-416c-9515-f54ff9dfdb00.png">

**Comment by lolamtisch** [comment]
Yeah you are right. This should follow user preferences too. Will be fixed
