### ISSUE TITLE
See how far you're behind on anime/manga

### ISSUE THREAD

**Issue by evka745** [MALSync/MALSync#1418]
### Suggestion

Would be nice to have an option to view how many episodes/ or chapters you're behind instead of seeing the total of episodes out. I think it's more confusing right now than helpful, the information for the number should match up with the progress bar under. The one that shows you have caught up is ok (it could not be there as well) but I think the other needs a change.
<img width="533" alt="Screen Shot 2022-11-06 at 12 18 21 AM" src="https://user-images.githubusercontent.com/82726788/200153998-524d443a-a697-46e7-a0a4-4e9f31651421.png">

**Comment by lolamtisch** [comment]
I think that is a lot more confusing to show the ep/ch to read. If someone sees 3/12 [1] no one would think that there is one Episode to see, the people expect to see 3/12 [9] if any. As the only visible info is 9 eps are left to finish the series.
Additional there would be no distincion between beeing on the newest ep or having no progress data.

**Comment by evka745** [comment]
Sorry, I don’t think I interpreted it right. What I mean is for releasing anime, for example you have watched 3 eps but there are 5 eps out. I don’t think it should display 5 but should display 2, in the meaning that you have 2 eps to go, at least for now. And when you’re caught up, it could say something that interprets that you have caught up.
