### ISSUE TITLE
Option for Japanese/English title when searching not always there

### ISSUE THREAD

**Issue by evkaw** [MALSync/MALSync#1419]
### Describe the Bug

The option to search a website for either the Japanese or English title is not always there even though both versions are featured.

Ex. Chainsaw Man not being able to search with its English title vs Spy x Family having both

### Steps to reproduce the behavior

Use a quicklink on pop-up for an anime/manga title

<img width="166" alt="Screen Shot 2022-11-06 at 12 31 42 AM" src="https://user-images.githubusercontent.com/82726788/200154306-cfd6a617-d613-4e6f-bb32-4ebdf59652dd.png">

### Browser

Chrome

### Type

Extension

### URL

https://www.netflix.com/search?q=Chainsaw%20Man

**Comment by lolamtisch** [comment]
Yeah apparently a bug.

Missing english title in serach if anilist is set to native titles.
