### ISSUE TITLE
Closing the popup breaks the internal back button navigation

### ISSUE THREAD

**Issue by DaveDuck321** [MALSync/MALSync#1421]
### Describe the Bug

After navigating to an anime with the popup, reopening the popup leaves me unable to navigate back to my list (note the greyed arrow, pressing it has no effect):

![image](https://user-images.githubusercontent.com/30243291/200179717-fb69f612-d167-4d3f-b6b9-85755fe6e209.png)

Now if I navigate to the settings view and close the popup, I am unable to return to either the previous anime or the list overview:

![image](https://user-images.githubusercontent.com/30243291/200179946-bc45f2c6-dacb-4137-b851-dd04b1bf246b.png)

### Steps to reproduce the behavior

Navigate to a page inside the popup, close the popup, reopen the popup, then try to press the back button.

This can be resolved by relaunching the entire browser.

### Browser

Firefox

### Type

Extension

### URL

n/a

**Comment by lolamtisch** [comment]
click on that. Fixed
![image](https://user-images.githubusercontent.com/12599334/200180166-5e6479df-6572-4c6a-9d09-843a028e4c49.png)

**Comment by DaveDuck321** [comment]
Cool, thanks 😊. Kinda intuitive but that works!
