### ISSUE TITLE
System theme on Firefox

### ISSUE THREAD

**Issue by DaveDuck321** [MALSync/MALSync#1422]
### Describe the Bug

The popup does not pickup my system theme but I can still manually set the theme. I know this used to work a few months ago.

Running `window.matchMedia('(prefers-color-scheme: dark)').matches` returns `True`.

### Steps to reproduce the behavior

Settings -> Theming -> Theme -> System (with a dark system + Firefox theme)

### Browser

Firefox

### Type

Extension

### URL

N/a

**Comment by lolamtisch** [comment]
![image](https://user-images.githubusercontent.com/12599334/200181118-5c3f74f4-4674-45e7-b337-eb305e9b9a06.png)
Works on my end

**Comment by DaveDuck321** [comment]
Turns out Firefox has separate theming for web content and chrome, the Malsync theme now matches the chrome rather than the web content. I suppose this is intentional tho.
