### ISSUE TITLE
Tracking confusion

### ISSUE THREAD

**Issue by JordanP22** [MALSync/MALSync#1426]
### Describe the Bug

I have anime tracking set to video and progress set to 90%. So theoretically, once I finish 90% of an episode, it should update the tracker so it shows I am now watching the next episode. However, it seems to be tracking one episode behind. For example, the tracker shows that I am watching episode 10, but in reality I am 5 minutes into watching episode 11. It will only update to show that I am watching episode 11 once I am 90% through with that episode. Am I simply misunderstanding the feature? 

### Steps to reproduce the behavior

1. Go to tracking in settings
2. set anime tracking to video
3. set progress to 90%
4. watch 90% of an episode of anime. it will say you are on that episode, when it should have updated to show you are on the next episode.
5. watch 90%of episode 2. It will now say you are watching episode 2, when in reality it should say you are on episode 3.

### Browser

firefox

### Type

Extension

### URL

9anime

**Comment by farahnur42** [comment]
@JordanP22 You misunderstood how it works then, that threshold is for telling MALSync when it should mark your *current* episode as watched so it's working as intended. If you want it to work the way you wish it would, add an episode offset of +1 in the correction menu

**Comment by lolamtisch** [comment]
But that makes no sense because if you watch ep 11 of 12 then it will already be finished with 12/12.

**Comment by JordanP22** [comment]
ok so the tracker shows how many episodes you've watched and not what episode you're currently on. Thanks for the clarification.
