### ISSUE TITLE
Rich Presence not working on BetterAnime

### ISSUE THREAD

**Issue by ghost** [MALSync/MALSync#1429]
### Describe the Bug

Apparently rich presence is not working properly on the betteranime site

Possibly some conflict with the prewrap

### Steps to reproduce the behavior

acess https://betteranime.net/anime/legendado/kuma-kuma-kuma-bear/episodio-08 and try to watch 

need to have prewrap instaled

### Browser

Chrome

### Type

Extension

### URL

https://betteranime.net/anime/legendado/kuma-kuma-kuma-bear/episodio-08

**Comment by lolamtisch** [comment]
What is the Problem?
