### ISSUE TITLE
Extension popup size 

### ISSUE THREAD

**Issue by magnusa2007** [MALSync/MALSync#1439]
### Describe the Bug

When i open the popup it has a different size depending on what way i open it.

### Steps to reproduce the behavior

1. Enable "Open in separate window".
2. Go to a manga/anime site and press the extension button and a small separate window open.
3. Click on the miniMal floating menu button and a large window will open.

Here is a video of what im doing
https://user-images.githubusercontent.com/49444876/201493818-2fa319ed-94f9-482c-a4d4-932855fd63e1.mp4

### Browser

Brave

### Type

Extension

### URL

Tested on https://animixplay.to/ and https://asura.gg/

**Comment by lolamtisch** [comment]
Do you have different sized screens or something like that? Because I can not reproduce it.

**Comment by lolamtisch** [comment]
We can not control on what display it opens. So no idea
