### ISSUE TITLE
"Rate limited. Retrying in a moment" issue

### ISSUE THREAD

**Issue by Key-explanation** [MALSync/MALSync#1446]
### Describe the Bug

Whenever I try to sync my list it says "Rate limited. Retrying in a moment". I has been like this for 2 days.(how do I open the Extension popup like before?)

### Steps to reproduce the behavior

1. click on list sync.
2. It shows "Rate limited. Retrying in a moment" and doesn't load anilist.

### Browser

firefox

### Type

Extension

### URL

9anime.pl

**Comment by lolamtisch** [comment]
Anilist servers have problems atm. Not something we can fix

**Comment by Key-explanation** [comment]
The can I open the extension pop up like before instead of it showing correction popup

**Comment by lolamtisch** [comment]
https://malsync.moe/pwa/#/settings/tracking/floatButtonCorrection

**Comment by beedell-roke** [comment]
@lolamtisch, I appear to experience similar:

<p></p><img width="636" height="716" alt="Image" src="https://github.com/user-attachments/assets/c70ca057-29dd-411e-82eb-fa1148f9f32a" /><p></p>

They eventually appear to load.

**Comment by lolamtisch** [comment]
Anilist has horrendous rate limits nothing we can do.

**Comment by beedell-roke** [comment]
@lolamtisch, thanks. Adding, to the notification, the name of the provider, that's being rate limited, would assist, though. I worried that it was Kitsu, which is my source.

Additionally, if I could enter my own API key, if that would assist, I would.
