### ISSUE TITLE
Comick domain change

### ISSUE THREAD

**Issue by Uranite** [MALSync/MALSync#1509]
comick.fun has changed to comick.app

**Comment by lolamtisch** [comment]
Open the settings page in the extension and accept the popup with the new permissions.

**Comment by Uranite** [comment]
Thanks, it works

**Comment by Uranite** [comment]
Actually, it's not working properly, I had to refresh the website to make MALSync work, For example on this [link](https://comick.app/comic/ore-dake-fuguu-skill-no-isekai-shoukan-hangyakuki-saijaku-skill-kyuushuu-ga-subete-o-nomikomu-made/oo3vK-chapter-11-en)
Before refreshing the site, MALSync is not working, as indicated by the absence of the pencil icon on the bottom right
![image](https://user-images.githubusercontent.com/62639703/208932619-1ea10619-3a1c-404c-9b0c-d212f2dd162f.png)
After refreshing the site, MALSync is working properly, there is a pencil icon on bottom right
![image](https://user-images.githubusercontent.com/62639703/208932890-7dfd2cc4-ce56-4517-a3ff-05914260ae51.png)
I'm on windows, using firefox
Things are fine on other website

**Comment by lolamtisch** [comment]
@Uranite Can you add exact steps to reproduce it. I have no problem

**Comment by Uranite** [comment]
> @Uranite Can you add exact steps to reproduce it. I have no problem

Weird, I couldn't reproduce it on a new browser profile
The exact step to reproduce it is the same
Visit this link
https://comick.app/comic/ore-dake-fuguu-skill-no-isekai-shoukan-hangyakuki-saijaku-skill-kyuushuu-ga-subete-o-nomikomu-made/oo3vK-chapter-11-en
Now, MALSync should be working, but it isn't and you have to refresh the website for MALSync to work
