### ISSUE TITLE
Open "Missing Permissions" page in new tab

### ISSUE THREAD

**Issue by meme8383** [MALSync/MALSync#1516]
### Suggestion

Opens the custom domains page in a new tab rather than the current tab after clicking "Add" on the "Missing Permissions Detected" message.

**Comment by henrik9999** [comment]
Its kinda intented to to that right now, so that the user leaves the current episode because it would require the page to be reloaded after they got added for it to work

**Comment by meme8383** [comment]
Ah that makes sense, it just didn't seem right to me that an extention takes over the current tab.
