### ISSUE TITLE
Hanging the browser

### ISSUE THREAD

**Issue by stealthswor** [MALSync/MALSync#1522]
### Describe the Bug

It keeps crashing my browser whenever I turn the extension on.  It freezes for a few seconds and then the browser force quits. Sometimes it happens instantly.

### Steps to reproduce the behavior

It appears to happen when I load a manga page, but it also happens at random times as well.

### Browser

Vivaldi (Chrome web store)

### Type

Extension

### URL

Any webpage

**Comment by henrik9999** [comment]
Are you using 32bit PC

**Comment by RikisuT** [comment]
Same issue I'm using it on vivaldi 64 bit

**Comment by henrik9999** [comment]
> Same issue I'm using it on vivaldi 64 bit

Can you try normal chrome browser

**Comment by RikisuT** [comment]
> > Same issue I'm using it on vivaldi 64 bit
> 
> Can you try normal chrome browser

Looks like it works fine in chrome for now.
I'll reply here if there is any occurence of this in chrome.

**Comment by stealthswor** [comment]
Well I tried some older versions of the extension and none of them work anymore. I assume it's a browser bug.

**Comment by RossDanbyGamer** [comment]
MALSync is crashing my browser as well, using Vivaldi same as OP.

**Comment by lolamtisch** [comment]
Did someone try some of the previous versions of the browser? Or did someone already file a bug report on Vivaldi? The bug tracker is closed so I can not check if it was already reported.

**Comment by stealthswor** [comment]
> Did someone try some of the previous versions of the browser? Or did someone already file a bug report on Vivaldi? The bug tracker is closed so I can not check if it was already reported.

I sent in a bug report.

**Comment by stealthswor** [comment]
The browser has fixed the issue. Closing this.
