### ISSUE TITLE
[Website Request] Ani-One Asia's YouTube Channel

### ISSUE THREAD

**Issue by sannidhyaroy** [MALSync/MALSync#1550]
### Website name

Ani-One Asia

### Website link

https://www.youtube.com/@AniOneAsia

### Website language(s)

English

### Other details

Ani-One is a diversified Japanese animation content platform wholly-owned by Medialink Group.
Since all the anime on the channel are legally licensed and the ad money goes to the creators and distributors, I'm inclined to support this over piracy sites.
Having MAL-Sync work with it would be very helpful.

**Comment by lolamtisch** [comment]
Because of multiple reasons YouTube is not an option for malsync.
