### ISSUE TITLE
[Website Request] marin.moe (formerly tenshi.moe)

### ISSUE THREAD

**Issue by rollingmoai** [MALSync/MALSync#1554]
### Website name

Marin

### Website link

https://marin.moe/

### Website language(s)

English

### Other details

https://tenshi.moe/ has closed, redirecting to their new site https://marin.moe/:
![image](https://user-images.githubusercontent.com/75471378/212288514-be4f170c-c5ce-4ef5-a879-2ef2ec16ad2c.png)

**Comment by Zanes** [comment]
For now I think you can just add as a tenshi custom domain and it will work

**Comment by rollingmoai** [comment]
> For now I think you can just add as a tenshi custom domain and it will work

The problem is that I would have to refresh every time I go to a new page or MALSync won't detect it.

**Comment by lolamtisch** [comment]
There is no workaround. Custom domain does not work because there are too many changes

**Comment by Zanes** [comment]
I just tested and it worked tho. Not only it recognized the anime, it added the episode at the end just fine.

**Comment by lolamtisch** [comment]
You are right the only two things that are not broken are sufficient to update the ep. But the title can not retrieved so you will need to fix the relations to Mal often
