### ISSUE TITLE
[9anime] Not properly detecting different season

### ISSUE THREAD

**Issue by MolotovCherry** [MALSync/MALSync#1556]
### Describe the Bug

I go to a page that has multiple seasons on it, e.g. (below), and the one that malsync is tracking has 12 episodes and is completed (first season), but the actual one I'm watching is season 2 with only 1 episode. Seems fairly consistent

![image](https://user-images.githubusercontent.com/13651622/212450389-053a0bd9-a09f-4c60-a27d-3f0b47ebcce3.png)

I'm watching the season 2 part, but as you can see below, it's tracking the wrong thing (the episode selector right above also shows only 1 episode)

![image](https://user-images.githubusercontent.com/13651622/212450482-5c5aadcf-bef3-4301-91ad-7801568a59b0.png)

### Steps to reproduce the behavior

As far as I know, go to any page that lists anime like this with multiple seasons selector, and the seasons after that it's tracking will be incorrect. That said, I've only tried this with currently-airing shows.

I haven't found exactly the cause of this, because some seem fine too, regardless of having the season selector as well.

### Browser

Chrome 109.0.5414.74 (Official Build) (64-bit)

### Type

Extension

### URL

https://9anime.pl/watch/shin-shinka-no-mi-shiranai-uchi-ni-kachigumi-jinsei.4q28j/ep-1

**Comment by lolamtisch** [comment]
https://github.com/MALSync/MALSync/wiki/Troubleshooting#myanimeentry--anilist--kitsu--simkl-entry-is-not-correct
