### ISSUE TITLE
Support for additional Hentai Sites

### ISSUE THREAD

**Issue by Basara-Hatake** [MALSync/MALSync#156]
- [X] https://hanime.tv 
- [X] https://hentaihaven.org/
- [X] http://hentaigasm.com/
- [X] http://kisshentai.net/
- [X] https://www.underhentai.net/
- [X] https://hentaikisa.com/
- [ ] https://animeidhentai.com/
- [ ] https://hentaidude.com/
- [ ] https://muchohentai.com/
- [ ] https://videos.hentaifox.com/
- [ ] https://nekopoi.care
- [ ] http://hentaipulse.com/
- [ ] http://www.xanimeporn.com/
- [ ] http://hentaimama.com
- [ ] http://kissdoujin.com 
- [ ] https://thishentai.rock

**Comment by one-and-all** [comment]
Mind adding http:///hentaimama.com that list?

**Comment by PursiyMe7Seven** [comment]
[kissdoujin.com](url) - site with doujin hentai manga

**Comment by AccelerateIzaya** [comment]
https://hentaikisa.com/ 
New hentai site, and it's quite easy to use.

**Comment by everyonus** [comment]
Hanime tracking appears to be broken. The hamburger does load but stuff related to tracking does not.

**Comment by Basara-Hatake** [comment]
> https://hentaikisa.com/
> New hentai site, and it's quite easy to use.

done

**Comment by RootAndroid58** [comment]
http://hentaicore.org/ this site too

**Comment by pr0dukt** [comment]
Might as well add these two if we're going all out with the best out there, since they both are incredibly user friendly, and are updated quite frequently;

https://ohentai.org/
https://miohentai.com/

**Comment by Ruriko** [comment]
https://thishentai.rock maybe this site too

**Comment by FateXBlood** [comment]
Surprised to see nhentai.net not there. I recommend it.

**Comment by Draazu** [comment]
another good site is e-hentai.org

**Comment by henrik9999** [comment]
We have decided to close the "Support for additional ..." issues because of them being unorganized and messy. If you still want your site to be added create a new issue (if there isnt already one, use the search) for it and use the website request template
