### ISSUE TITLE
Anime/Mangas filters not showing properly on Firefox

### ISSUE THREAD

**Issue by lepetitpaco** [MALSync/MALSync#1566]
### Describe the Bug

When I want to organisize the ordering of my list in the plugin or if I want to change the layout (list, mosaic,...), the options are not showing properly.

### Steps to reproduce the behavior

Click on the plugin button and select the filters or layout options.

![277_SpcmK8ySew](https://user-images.githubusercontent.com/22540179/213212656-9750acb7-2e0c-4549-830f-2c32d66166e3.gif)

### Browser

Firefox

### Type

Extension

### URL

None

**Comment by lolamtisch** [comment]
Current workaround is to open it in full size and change it there until it is fixed.
https://malsync.moe/pwa/
