### ISSUE TITLE
Mark themes names for translation

### ISSUE THREAD

**Issue by louisroyer** [MALSync/MALSync#1587]
### Suggestion

https://github.com/MALSync/MALSync/blob/d95a9e0d7f3a6c339c186ee9571d6b7997d03598/src/_minimal/components/settings/settings-structure-theming.ts#L15-L19
https://github.com/MALSync/MALSync/blob/d95a9e0d7f3a6c339c186ee9571d6b7997d03598/src/_minimal/components/themes/nordtheme.ts#L4
Would it be possible to use a localized version of theme titles (using `lang()` or equivalent), so I can translate them on Weblate?

**Comment by lolamtisch** [comment]
Good idea. 

But not sure about making Nord translateble too, as it is a name. What do you thing?
https://www.nordtheme.com/

**Comment by louisroyer** [comment]
Oh, since it's a name we should probably let it untranslated (unless if there is an official translation of the name for some languages, but it doesn't seem to be the case). The 4 other titles should definitely have a translation since they convey meaning.

**Comment by lolamtisch** [comment]
The new strings should now be translatable

**Comment by PaulWentzel** [comment]
Would it be possible to do the same for the sorting options?
![image](https://user-images.githubusercontent.com/100777359/216455901-ff620368-35ff-4250-befd-402ebe5de1df.png)
