### ISSUE TITLE
[Website Request] <Website Name>

### ISSUE THREAD

**Issue by MercilessOce** [MALSync/MALSync#1588]
### Website name

4anime

### Website link

4aqnime.gg

### Website language(s)

English

**Comment by lolamtisch** [comment]
I think this is a fake of 4anime.to and it just scraps from zoro either way.

**Comment by jp-man25** [comment]
> I think this is a fake of 4anime.to and it just scraps from zoro either way.

4anime.to is shut down, this still works. This is one of the few sites with toggle CC subs, and Zoro (now Hianime) hasn't been working half the time, I haven't had any issues with 4anime.
