### ISSUE TITLE
Scrolling on an Anilist list calls "Please Authenticate Here" toast to repeatedly pop-up

### ISSUE THREAD

**Issue by SuperStormer** [MALSync/MALSync#1589]
### Describe the Bug

Scrolling on a anilist list when not logged in causes the toast to repeatedly popup. It does go away after a bit of time, but scrolling down enough causes it to reappear.

I'm using default configs (aside from authenticating with MAL) on a fresh Chrome profile, with only MALSync installed.

### Steps to reproduce the behavior

1. Attempt to scroll
2. Observe that the toast popups many times.

### Browser

Chrome

### Type

Extension

### URL

https://anilist.co/user/Fetch/animelist/Completed

**Comment by SuperStormer** [comment]
The same issue occurs on kitsu, but not shikimori or simkl.

**Comment by lolamtisch** [comment]
What would you describe as the correct behaviour? I mean it ask you to authenticate so it can retrieve data for adding things like links to the streaming page or the number of released chapter/episodes on the list.

**Comment by SuperStormer** [comment]
It should only prompt it once on page load (and then hide itself, similar to the toast on mangadex, etc) instead of repeatedly being prompted every time you scroll, causing a distracting animation.

**Comment by lolamtisch** [comment]
It shows the notification every time data is requested. For the lists it waits for it to getting into view. 

Not sure what the better solution would be.
Only to request it once per page load, which for anilist without page reloads could be once. Once a minute, which would be too inconsistent. Or disable it completely for lists and only show it when opening a single entry.

**Comment by SuperStormer** [comment]
Maybe debounce the notification code, so even if it gets called multiple times, the notification will only get displayed if it's been x seconds since the last call.
