### ISSUE TITLE
Would it be possible to do the same for the sorting options?

### ISSUE THREAD

**Issue by PaulWentzel** [MALSync/MALSync#1598]
Would it be possible to do the same for the sorting options?
![image](https://user-images.githubusercontent.com/100777359/216455901-ff620368-35ff-4250-befd-402ebe5de1df.png)

_Originally posted by @PaulWentzel in https://github.com/MALSync/MALSync/issues/1587#issuecomment-1414412110_

**Comment by lolamtisch** [comment]
Should now be translatable

**Comment by louisroyer** [comment]
Reusing `settings_progress_default` is not very future-proof (and even if the label is the same in English, it may cause issues for certain languages)…
