### ISSUE TITLE
Support for additional Anime sites

### ISSUE THREAD

**Issue by Karmesinrot** [MALSync/MALSync#16]
- [X] twist.moe
- [X] ~~animeheaven.eu~~
- [X] ~~otakustream.tv~~
- [X] animepahe.com
- [ ] ~~www.anime-planet.com~~
- [X] 4anime.to
- [X] animeultima.eu
- [X] wakanim.tv
- [X] kickassanime.io
- [X] ~~dreamanimes.com.br~~
- [X] Netflix
- [ ] ~~eyeonanime.tv~~
- [ ] ~~animedao.com~~
- [ ] ~~animepie.to~~
- [ ] ~~watchbox.de~~
- [x] Amazon (I have no account, would need a sponsor)

**Comment by hemlok89** [comment]
I second twist.moe. It is by far the cleanest interface of any anime site.

**Comment by lolamtisch** [comment]
In case you missed it. There is a survey running to this.
https://goo.gl/forms/gRdoO4APyeKYFxk83

**Comment by FunkyJustin** [comment]
Is there any plans for syncing hentai sites in the future?

**Comment by lolamtisch** [comment]
@FunkyJustin
My statement to this theme.

I am not going to support Hentai/h-doujin pages. But if someone wants to write the implementations for that pages and do the support for that pages. I would extend current implementation for supporting/creating a adult only userscript.

**Comment by Karmesinrot** [comment]
Quite a bit of announcement, animeheaven will be closing on December 25.

**Comment by AccelerateIzaya** [comment]
WonderfulSubs
https://www.wonderfulsubs.com/

**Comment by b1n4ryk1lla** [comment]
+1 for wonderfulsubs

**Comment by SneakyGR** [comment]
I Second animedao.com its super clean

**Comment by henrik9999** [comment]
> +1 for animedao.com its super clean
> [https://animedao.com](url)
not really possible right now

**Comment by nattadasu** [comment]
Re-support for [Moeclip.com](https://moeclip.com) as [Meowstream](https://meowstream.com "it's dead lol") "alternative". :v

**Comment by ArifulH8** [comment]
Hello is there a reason why Animedao.com wont work right now?

**Comment by henrik9999** [comment]
Of course there is a reason
The problem is that each anime has a different domain

**Comment by ArifulH8** [comment]
Okay thank you for the information.

**Comment by dexman545** [comment]
I would like to request support for WatchCartoon Online, https://www.thewatchcartoononline.tv/

**Comment by kathelynn** [comment]
https://animeflix.io/
Has the best interface I've seen on any anime site, period. Created by the guys from animeultima.tv

**Comment by lolamtisch** [comment]
@kathelynn 
animeflix is already supported

**Comment by kathelynn** [comment]
Sorry, it was turned off for me for some reason. Thanks for letting me know!

**Comment by AEStudios** [comment]
Hello! I wanted to ask for support for a relatively new website, Animixplay It's really amazing, clean and no ads what so ever. Here the url :-  https://animixplay.com/

**Comment by OnikenX** [comment]
what about pantsubase tv? they are against ads and have a cool community

**Comment by AEStudios** [comment]
Please add support for animeowl.net

**Comment by henrik9999** [comment]
> Please add support for animeowl.net

Already done for next release

**Comment by henrik9999** [comment]
> what about pantsubase tv? they are against ads and have a cool community

Also done for next release

**Comment by cherryleafroad** [comment]
I definitely need anime-planet support. Hope this can come soon / is possible

**Comment by trespordez** [comment]
Any plans to add AnimesROLL support?
[https://www.anroll.net/](url)

**Comment by AEStudios** [comment]
Please add support for https://kimanime.ru/

**Comment by henrik9999** [comment]
> I definitely need anime-planet support. Hope this can come soon / is possible

Anime planet as a tracker? @cherryleafroad

**Comment by cherryleafroad** [comment]
> > I definitely need anime-planet support. Hope this can come soon / is possible
> 
> Anime planet as a tracker? @cherryleafroad

Yeah, but unfortunately I heard there's no API, so I guess that'd be impossible / too difficult

**Comment by henrik9999** [comment]
> > > I definitely need anime-planet support. Hope this can come soon / is possible
> > 
> > 
> > Anime planet as a tracker? @cherryleafroad
> 
> Yeah, but unfortunately I heard there's no API, so I guess that'd be impossible / too difficult

Yeah I don't think it will be added in the near future

**Comment by trespordez** [comment]
AnRoll.net and Animesup.net (y)

**Comment by soredake** [comment]
gogoanime.ai

**Comment by SonikkuPlay** [comment]
I would like to request kimanime.com

**Comment by hugoppp** [comment]
https://animeplyx.one would be nice

**Comment by jainprashul** [comment]
https://an9where.vercel.app one must be added

**Comment by Klairm** [comment]
https://www3.animeflv.net/   and  https://monoschinos2.com/

**Comment by henrik9999** [comment]
We have decided to close the "Support for additional ..." issues because of them being unorganized and messy. If you still want your site to be added create a new issue (if there isnt already one, use the search) for it and use the website request template
