### ISSUE TITLE
[Website Request] 4anime

### ISSUE THREAD

**Issue by klysman08** [MALSync/MALSync#1600]
### Website name

4anime

### Website link

https://4anime.gg/

### Website language(s)

English and others

### Other details

4anime is the safest site to watch English Subbed and Dubbed anime online for free.

**Comment by lolamtisch** [comment]
Duplicate #1588

**Comment by henrik9999** [comment]
4anime is dead this is just a fake clone site

**Comment by klysman08** [comment]
I did not know that. Thanks,

> 4anime is dead this is just a fake clone site
