### ISSUE TITLE
Malsync says 'missing permission detected' at kiwi browser

### ISSUE THREAD

**Issue by soymadip** [MALSync/MALSync#1618]
### Describe the Bug

When opening extension settings on kiwi browser, it says missing permission:- 
![Screenshot_2023-02-14-10-34-00-20_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/84225810/218644293-4299a964-f522-478c-a6e0-c7f7789004ac.jpg)

### Steps to reproduce the behavior

Install extension at [Kiwi](https://play.google.com/store/apps/details?id=com.kiwibrowser.browser) browser. 
Open extension settings. 
- if you click on 'add' button, browser crashes. 

### Browser

Kiwi browser:- https://play.google.com/store/apps/details?id=com.kiwibrowser.browser

### Type

Extension

### URL

chrome-extension://kekjfbackdeiabghhcdklcdoekaanoel/popup.html#/settings

**Comment by henrik9999** [comment]
Nothing we can do, kiwi probably doesn't have the required functions implemented, same for Firefox nighty if I remember correctly

**Comment by soymadip** [comment]
> Nothing we can do, kiwi probably doesn't have the required functions implemented, same for Firefox nightly if I remember correctly

Oh! So it's because of incomplete implementation of chromium. 
Got it.

**Comment by WitherredAway** [comment]
I have found a user-side fix: https://github.com/MALSync/MALSync/issues/1725#issuecomment-1676420440

**Comment by Burnaviour** [comment]
use Lumer Browser its working in that browser
