### ISSUE TITLE
Voiranime broken

### ISSUE THREAD

**Issue by KyroOW** [MALSync/MALSync#1625]
### Describe the Bug

voiranime.com is no longer detected, i think it's because of the new subdomain v2.voiranime.com

### Steps to reproduce the behavior

go to voiranime.com
browser gets redirected to v2.voiranime.com
mal sync doesn't show up

### Browser

Microsoft Edge

### Type

Extension

### URL

https://v2.voiranime.com/

**Comment by henrik9999** [comment]
Please check for new permissions on the custom domain page. Add them and restart.
https://malsync.moe/pwa/#customDomains
