### ISSUE TITLE
English titles in MALSync

### ISSUE THREAD

**Issue by jimmyedagawa78** [MALSync/MALSync#1626]
### Suggestion

Hi, could we potentially see the option to add English Titles in the place of Romaji titles in MALSync, maybe as an option in settings 

![image](https://user-images.githubusercontent.com/30567984/220023797-5d257291-e4ea-4c61-872a-8dee48bef182.png)

**Comment by lolamtisch** [comment]
It should already follow whatever is set in the settings https://anilist.co/settings/media

**Comment by jimmyedagawa78** [comment]
I'm using MAL as my master with English titles and turned on Force English in _Misc_ but the titles are still in Romaji in MAL-Sync (It shows up in English on MAL) Not sure why it doesn't show up in English.

![image](https://user-images.githubusercontent.com/30567984/222871864-d24837e5-3c8f-4b1c-afb6-0875247c85f8.png)

**Comment by lolamtisch** [comment]
The force English option is unrelated. Mal is not possible. Only anilist can follow user settings
