### ISSUE TITLE
No Sync with Plex

### ISSUE THREAD

**Issue by Fu2chN** [MALSync/MALSync#1644]
### Describe the Bug

I don't have sync with Plex, even MAL's modal window disappeared.

Version de Plex server 1.31.1.6733 
Version de MAL-Sync 0.9.2

### Steps to reproduce the behavior

Nothing special, just watch anime on Plex.

### Browser

Firefox 110

### Type

Extension

### URL

https://app.plex.tv/

**Comment by lolamtisch** [comment]
Can not reproduce. Did you follow https://github.com/MALSync/MALSync/wiki/Emby-Plex#plex ?

**Comment by Fu2chN** [comment]
Ah, thx, I had changed the name of my library ^^
