### ISSUE TITLE
[Website Request] Goyabu.org

### ISSUE THREAD

**Issue by rube200** [MALSync/MALSync#1658]
### Website name

Goyabu

### Website link

goyabu.org

### Website language(s)

Portuguese

### Other details

There is already one website registered with that name (Goyabu) but that one is `Goyabu.com` and not `Goyabu.org`.
For some reason for me `Goyabu.com` is down, can you also check it?

**Comment by lolamtisch** [comment]
Thank you. The page seems dead going to remove it now
