### ISSUE TITLE
[Website Request] <MangaHasu>

### ISSUE THREAD

**Issue by dusberendguy** [MALSync/MALSync#1660]
### Website name

MangaHasu

### Website link

https://mangahasu.se/

### Website language(s)

English

### Other details

The website has a built-in read history, as well as some other things, like being able to "subscribe" to manga which means you get a notification when a new chapter releases and being able to mark manga as plan to read. Maybe it would be nice if especially the read history was able to be synced.

**Comment by henrik9999** [comment]
Duplicate #1120
