### ISSUE TITLE
MalSync PWA isn't optimised for mobile/similar devices.

### ISSUE THREAD

**Issue by soymadip** [MALSync/MALSync#1666]
### Describe the Bug

Although the [PWA](https://MalSync.moe/pwa) works perfectly at desktop/larger screen devices. 

It doesn't work correctly at mobile/smaller screen devices. Many visual elements are placed incorrectly, some times they are not displayed fully. 
Example:- 
1. The list sync screen:- 
![Screenshot_2023-03-04-13-32-58-05_32cba261fc08a501ce70de75bdbe2575](https://user-images.githubusercontent.com/84225810/222890157-0ed907c6-348b-45cc-bbe0-91d3676f72d9.jpg)
2. The home screen:- 
![Screenshot_2023-03-04-14-45-01-31_32cba261fc08a501ce70de75bdbe2575](https://user-images.githubusercontent.com/84225810/222890201-7caedba6-7d04-4fa1-ab5c-0e99add12742.jpg)

Unlike kiwi browser, [Lemur](https://play.google.com/store/apps/details?id=com.lemurbrowser.exts) Browser fully supports extensions (almost perfect), so i guess it's not browser's problem.

### Steps to reproduce the behavior

1.Open PWA :- https://MalSync.moe/pwa
2. There will be many incorrect visual elements.
3. Another one is at list sync page. There are the sync lists, some of them will be cut . 
![Screenshot_2023-03-04-13-32-58-05_32cba261fc08a501ce70de75bdbe2575](https://user-images.githubusercontent.com/84225810/222890464-6ab46233-413a-4f9f-838d-a6958219377e.jpg)
Etc...

### Browser

Lemur Browser :- https://play.google.com/store/apps/details?id=com.lemurbrowser.exts

### Type

Extension

### URL

https://malsync.moe/pwa

**Comment by lolamtisch** [comment]
List sync view is just there for debugging, we won't put work into that.

Not sure what you mean with the other one. You want to have the titles cut off so that it looks better? Are these the only things?

**Comment by soymadip** [comment]
> List sync view is just there for debugging, we won't put work into that.
> 
> Not sure what you mean with the other one. You want to have the titles cut off so that it looks better? Are these the only things?

No, i was talking about that the list which is pending to be aynced, some of the provider's title has been cut off 
![IMG_20230304_185100](https://user-images.githubusercontent.com/84225810/222904192-164d2d19-a7cc-4176-be4a-710a53d89e64.jpg)
Like for me it's simkl

**Comment by soymadip** [comment]
And also the front page. 
In extension it looks like this:- 
![Screenshot_2023-03-04-18-52-49-54_32cba261fc08a501ce70de75bdbe2575](https://user-images.githubusercontent.com/84225810/222904288-4f83e072-d5d9-4454-a062-a5168f504507.jpg)

But in pwa :- 
![Screenshot_2023-03-04-18-53-00-51_32cba261fc08a501ce70de75bdbe2575](https://user-images.githubusercontent.com/84225810/222904303-5cbb161c-46e7-4099-8e97-773b411aa518.jpg)

**Comment by lolamtisch** [comment]
You have quite a small phone, so there is no space for it. I could only remove things for the list so that it fits.


![image](https://user-images.githubusercontent.com/12599334/222975531-77bedaaa-76da-43b0-936d-1a4c437cf777.png)

**Comment by soymadip** [comment]
> You have quite a small phone, so there is no space for it. I could only remove things for the list so that it fits.
> 
> ![image](https://user-images.githubusercontent.com/12599334/222975531-77bedaaa-76da-43b0-936d-1a4c437cf777.png)

Ohh, okk

**Comment by lolamtisch** [comment]
Should be fixed now
