### ISSUE TITLE
Some strings to be marked for translation

### ISSUE THREAD

**Issue by louisroyer** [MALSync/MALSync#1677]
### Suggestion

Could you please mark the following strings for translation ?
https://github.com/MALSync/MALSync/blob/a9510d0a402913c8c2ececd06d76a12ea950c721/src/_minimal/components/settings/settings-streaming.vue#L82
https://github.com/MALSync/MALSync/blob/c968582cb267c4d8687b01ce42ccefc72c1b5a81/src/utils/quicklinksBuilder.ts#L123
https://github.com/MALSync/MALSync/blob/c968582cb267c4d8687b01ce42ccefc72c1b5a81/src/utils/quicklinksBuilder.ts#L129
https://github.com/MALSync/MALSync/blob/d95a9e0d7f3a6c339c186ee9571d6b7997d03598/src/_provider/Simkl/metaOverview.ts#L98
https://github.com/MALSync/MALSync/blob/d95a9e0d7f3a6c339c186ee9571d6b7997d03598/src/_provider/Simkl/metaOverview.ts#L103
https://github.com/MALSync/MALSync/blob/d95a9e0d7f3a6c339c186ee9571d6b7997d03598/src/_provider/Simkl/metaOverview.ts#L109
https://github.com/MALSync/MALSync/blob/d95a9e0d7f3a6c339c186ee9571d6b7997d03598/src/_provider/Simkl/metaOverview.ts#L114
https://github.com/MALSync/MALSync/blob/d95a9e0d7f3a6c339c186ee9571d6b7997d03598/src/_provider/Simkl/metaOverview.ts#L122
https://github.com/MALSync/MALSync/blob/d95a9e0d7f3a6c339c186ee9571d6b7997d03598/src/_provider/Simkl/metaOverview.ts#L128
https://github.com/MALSync/MALSync/blob/d95a9e0d7f3a6c339c186ee9571d6b7997d03598/src/_provider/Simkl/metaOverview.ts#L134
https://github.com/MALSync/MALSync/blob/d95a9e0d7f3a6c339c186ee9571d6b7997d03598/src/_provider/Simkl/metaOverview.ts#L140
https://github.com/MALSync/MALSync/blob/d95a9e0d7f3a6c339c186ee9571d6b7997d03598/src/_provider/Simkl/metaOverview.ts#L146
https://github.com/MALSync/MALSync/blob/d95a9e0d7f3a6c339c186ee9571d6b7997d03598/src/_provider/Simkl/metaOverview.ts#L152
https://github.com/MALSync/MALSync/blob/d95a9e0d7f3a6c339c186ee9571d6b7997d03598/src/_provider/Simkl/metaOverview.ts#L167
https://github.com/MALSync/MALSync/blob/d95a9e0d7f3a6c339c186ee9571d6b7997d03598/src/_provider/Simkl/metaOverview.ts#L173
https://github.com/MALSync/MALSync/blob/d95a9e0d7f3a6c339c186ee9571d6b7997d03598/src/_provider/Simkl/metaOverview.ts#L179

**Comment by lolamtisch** [comment]
I cleaned up all the sidebar labels for all the tracking pages and added them for translation.


I skipped the MALSync/src/utils/quicklinksBuilder.ts translations as they only show up on the mal/anilist... page where everything is english either way. It is half legacy as the popup uses icons now.

**Comment by louisroyer** [comment]
Thank you, I added French translation to weblate.
