### ISSUE TITLE
add new tracks website

### ISSUE THREAD

**Issue by nizarelmesbahy** [MALSync/MALSync#1681]
### Suggestion

MAL & anilist are the most popular that is a fact , but they are other tracks like : livechart , anime planet , anidb

I think its cool if they added to the extension

**Comment by henrik9999** [comment]
anidb https://github.com/MALSync/MALSync/issues/69
Livechart https://github.com/MALSync/MALSync/issues/314
Anime-Planet https://github.com/MALSync/MALSync/issues/1002
