### ISSUE TITLE
Jellyfin, custom domain localhost:8096 does not detect or track any series - workaround

### ISSUE THREAD

**Issue by Amniotic5716** [MALSync/MALSync#1720]
### Describe the Bug

Always when you have multiple tabs open from sites that MALSync hooks into (myanimelist / 9anime / netflix), the custom domains will not work (at least Jellyfin custom domain) won't work.

Reason for this is the ORDER OF THE TABS in the browser.

- If the Jellyfin tab is set in a position AFTER the tabs in which MALSync hooks into, it will never detect anything.

To fix this:
- Move the Jellyfin tab position to be BEFORE the tabs in which MALSync hooks into, then refresh the page.

Literally created this account only so I could post this bit of information since for months I haven't found a fix for this issue.

### Steps to reproduce the behavior

Steps to reproduce:
1. Open 3 tabs in Firefox
2. 9Anime tab 1, go to a random episode
3. 9Anime tab 2, go to a random episode
4. Jellyfin with http://localhost:8096/ (the localhost)
5. Open 9anime tab 1 and 2 so they are active
6. Open Jellyfin tab and go to a series, click on the season, MALSync will not detect it.

Steps for workaround:
1. Repeat steps 1-6 from above
2. Move the Jellyfin tab so it is the first tab in the browser
3. Refresh the Jellyfin page, issue solved.

Steps to switch from working to non-working state:
5. Move the jellyfin tab after the other tabs, refresh, issue returns
6. Move the jellyfin tab before the other tabs, refresh, issue is fixed

### Browser

Firefox

### Type

Extension

### URL

http://localhost:8096/

**Comment by lolamtisch** [comment]
Should be a duplicate of #1674 and don't think it has something to do with the tab order.
