### ISSUE TITLE
Firefox Nightly Missing Permissions and No sync

### ISSUE THREAD

**Issue by B1rd113** [MALSync/MALSync#1724]
### Describe the Bug

https://github.com/MALSync/MALSync/issues/586
Followed this guide and has been working for months but now I get missing permissions detected with the red ADD button that does nothing when clicked. Anime progress is also not being synced automatically.

### Steps to reproduce the behavior

https://github.com/MALSync/MALSync/issues/586
Install malsync to Firefox nightly as per above guide.
Immediately shows missing permission field in settings.
Click on next episode or anime, nothing syncs.

### Browser

Firefox nightly

### Type

Extension

### URL

9anime.pl

**Comment by henrik9999** [comment]
Firefox nightly has not implemented that feature nothing we can do about that

**Comment by henrik9999** [comment]
Firefox mobile supports that feature now so will close this issue
