### ISSUE TITLE
Shikimori 401

### ISSUE THREAD

**Issue by matryosha** [MALSync/MALSync#1733]
### Describe the Bug

tldr: after some time tracking stop working due to 401 error

### Steps to reproduce the behavior

Sign in -- use the extension as always -- after some time passes (like couple of days) sync stops working.

### Browser

Firefox 111

### Type

Extension

### URL

https://animepahe.com

**Comment by lolamtisch** [comment]
My session is older than a month without a problem. 

Any more info?

**Comment by matryosha** [comment]
I am not actually sure what else could I provide...
If you say that it's fine on your side then I will at least try to recreate it again more detailed. Is there any logs I'd be able to provide or tips how to get more info for the issue?

**Comment by lolamtisch** [comment]
`about:debugging#/runtime/this-firefox`
on this page you can inspect the extension. Check the request in the network tab. Important would be the error text or something. But be carefull in not posting anything account critical in there.

If you have problem just pass by on our discord. https://discord.com/invite/cTH4yaw

**Comment by matryosha** [comment]
I got the error in that way. I have the same issue now 10 days after the last successful track entry. I will try to find something new

**Comment by nattadasu** [comment]
I have similar issue with Brave 1.48.171 Chromium: 110.0.5481.177 (Official Build) (64-bit), extension may fail to update the entry (without any error shown in extension itself or network inspection). Relogin might resolve the issue temporarily, but it'll be unauthorized in few days after login

**Comment by Phoenomenal** [comment]
There was a bug with Shikimori that anime episodes count don't update  unless you authorize and recheck each 24 hours.   

But now  Shikimori change domain to  .me  (shikimori.me)  so wont work on MAL-Sync

**Comment by matryosha** [comment]
Unfortunately, still nothing new to add to details. Hasn't been using malsync for weeks and encountered the same issue. No errors till trying to set new episode 

![image](https://user-images.githubusercontent.com/23679019/235368711-1de248f1-6446-42d3-af5e-2a766f420a7c.png)

As a side note, probably not related. But when malsync asks "Add to watching?" selecting yes won't actually update anything.

**Comment by lolamtisch** [comment]
What is the response? Does shiki respond why it is unauthorized?

And it does update after finishing the episode

**Comment by matryosha** [comment]
> What is the response? Does shiki respond why it is unauthorized?

The response is empty. 
> And it does update after finishing the episode

It does. At least it tries by sending the request.

**Comment by lolamtisch** [comment]
The whoiam works and returns your user? Do the post requests have the bearer token in the header (don't post it just check if there is one)?

**Comment by matryosha** [comment]
> Do the post requests have the bearer token in the header (don't post it just check if there is one)?

The header is present in all requests to shiki:
![image](https://user-images.githubusercontent.com/23679019/235409512-c811d688-8775-404a-9b20-de6e6471f1e7.png)

> The whoiam works and returns your user

Not sure what triggers that request but after 5 min no whoiam request hasn't been sent. At least it returned something back then judging by my previous screenshot as the size was not zero.

**Comment by lolamtisch** [comment]
Opening the malsync settings and tracking settings page should trigger it

**Comment by matryosha** [comment]
whoami returns correct info

**Comment by lolamtisch** [comment]
I am just now going to check for the error code. Lets hope that fixes it.

**Comment by lolamtisch** [comment]
Please check if the new release fixed the problem 0.9.4

**Comment by matryosha** [comment]
Will do. Currently I have re logged in old version so it works. Prob in 1 week if everything is fine then the check is enough.

**Comment by matryosha** [comment]
Have been using it with time intervals as always and no problem so far. Would assume the fix helped.
