### ISSUE TITLE
Shikimori new domain

### ISSUE THREAD

**Issue by Synrur** [MALSync/MALSync#1755]
### Describe the Bug

Shikimori change domain from Shikimori.one to Shikimori.me and the sync stopped working. On the old domain redirect to a third-party site. 

Also, can you add the ability to change domains for tracking websites in the extension?

### Steps to reproduce the behavior

Open Shikimori.one and get redirect to simsdom.com

### Browser

Chrome

### Type

Extension

### URL

https://Shikimori.one/

**Comment by SolAstri** [comment]
+1, old domain was stolen (see the [post](https://shikimori.me/forum/news/505429-novyy-domen-sayta-shikimori-me) by admin explaining the situation), needs to be updated.

Citing the post by @morr:
> TL;DR The site moved to the new domain shikimori.me on Thursday (April 14) at approximately 6 PM (Moscow time; UTC+3).
The old shikimori.one and shikimori.org domains stopped working on Friday at approximately 11 am (Moscow time).
The content that may appear on the old domains is no longer linked to the site.
> 
> In any case, the site's new domain is now shikimori.me. Even when/if I get the old domain back, the main domain of the site will remain the new one so I don't have to do another move.

**Comment by SolAstri** [comment]
Ok, @ morr has managed to get the old domain back, the api on the old address should work as before; tho, shikimori.me will still be a primary domain.

I guess, we can close the issue now, @Synrur?
