### ISSUE TITLE
Unexpected behaviour on login (low priority)

### ISSUE THREAD

**Issue by jaey-p** [MALSync/MALSync#1760]
### Describe the Bug

The local chrome extension page does not reload upon login, making the onboarding process confusing.

### Steps to reproduce the behavior

- install mal sync on chrome 1.50.121 (brave stable)
- click on authenticate
- after authorization, go back to mal-sync page

the unexpected behaviour is that mal-sync does not detect login, and continues to prompt for authentication. It went away after reloading .. would it be possible to consider this as a low priority bug?

I tried looking for any previous bug reports, but I found none, so I decided to file this in.

### Browser

1.50.121 Chromium: 112.0.5615.138 (Official Build) (arm64) (brave stable)

### Type

Extension

### URL

chrome-extension://kekjfbackdeiabghhcdklcdoekaanoel/install.html

**Comment by lolamtisch** [comment]
Yeah the onboarding will soon be replaced with a multi step and will be based on the popup system/design.

**Comment by jaey-p** [comment]
Gotcha, I'll keep a lookout for any beta-testing!
