### ISSUE TITLE
IP Banned Warning

### ISSUE THREAD

**Issue by DTM450** [MALSync/MALSync#1798]
### Describe the Bug

The IP banned warning is not accurate, currently at the time of this post MAL is down for maintenance but the warning is showing as your IP has been banned.

It would be advisable to warn that MALSync is unable to access MAL and to see if its down or if you have been IP banned

### Steps to reproduce the behavior

Use MALSync while myanimelist is inaccessible

### Browser

Firefox

### Type

Extension

### URL

N/A

**Comment by lolamtisch** [comment]
Mal apparently now uses IP bans to limit access. The error message is not wrong, but yeah I will add an disclaimer.

**Comment by thijsi123** [comment]
So are we actually banned, or is it really just a maintenance thing? (this scared the living hell out of me).

> Mal apparently now uses IP bans to limit access. The error message is not wrong, but yeah I will add an disclaimer.
