### ISSUE TITLE
MAL maintenance shows up as IP being banned

### ISSUE THREAD

**Issue by Jelgnum** [MALSync/MALSync#1799]
### Describe the Bug

While MAL is under maintenance the extension shows as if my IP has been banned
If you visit the API link it throws a 403 error at the moment
A disclaimer should probably be added
![image](https://github.com/MALSync/MALSync/assets/86729439/ae4040cc-119b-47d6-af19-744f4c5a95a6)
![image](https://github.com/MALSync/MALSync/assets/86729439/50151291-7730-4874-9c10-7c35848b3392)

### Steps to reproduce the behavior

1. MAL goes on maintenance
2. check MAL sync
3. MAL sync shows as if I have been IP banned
4. MAL is actually down for emergency maintenance 

### Browser

Firefox

### Type

Extension

### URL

N/A

**Comment by TinLite** [comment]
Chromium version experience the same bug too
![image](https://github.com/MALSync/MALSync/assets/37470201/76c2fa8f-f22b-4fbe-9018-30d53b91daf5)

**Comment by lolamtisch** [comment]
Duplicate #1798
