### ISSUE TITLE
Chrome banned

### ISSUE THREAD

**Issue by gebertiji** [MALSync/MALSync#1805]
### Describe the Bug

![image](https://github.com/MALSync/MALSync/assets/83186972/ace6ff15-ce4e-49ae-950d-92662820b979)

### Steps to reproduce the behavior

i think banned all account when will be unnbaned
its QoL for all people

### Browser

Google Chrome

### Type

Extension

### URL

https://www.turkanime.co

**Comment by lolamtisch** [comment]
#1798
