### ISSUE TITLE
String for the maintenance is in correct

### ISSUE THREAD

**Issue by WiLuX-Source** [MALSync/MALSync#1809]
### Describe the Bug

![image](https://github.com/MALSync/MALSync/assets/61833703/af6aa24f-74a8-40e4-8535-dea9dcef0639)

It should be `MAL is currently under maintenance`

### Steps to reproduce the behavior

Just open the extension while MAL is in maintenance.

### Browser

Chrome

### Type

Extension

### URL

nothing.

**Comment by lolamtisch** [comment]
Duplicate https://github.com/MALSync/MALSync/issues/1798
