### ISSUE TITLE
Sync doesn't work properly in MangaFire

### ISSUE THREAD

**Issue by RickyHunter024** [MALSync/MALSync#1829]
### Describe the Bug

Mangafire.to website autosync doesn't work properly as it doesn't sync the last chapter on any manga read and the menu that shows up if you hover in the bottom middle of the screen doesn't show up in the last chapter as well

### Steps to reproduce the behavior

Read all chapters of any specific manga on the website 

### Browser

Firefox

### Type

Extension

### URL

https://mangafire.to/home

**Comment by lolamtisch** [comment]
Will be fixed in the next update
https://github.com/MALSync/MALSync/commit/ec9e2ecc4705be6b1efe0d94de9deb8399b7a846

**Comment by RickyHunter024** [comment]
Nice!!
