### ISSUE TITLE
Vidstream player not detected

### ISSUE THREAD

**Issue by RandomPersonUMet** [MALSync/MALSync#1830]
### Describe the Bug

MALSync tracking feature cannot detect the Vidstream player on [9anime websites](https://9anime.pl/home), as well as the MyCloud and Filemoon video players. 
However Mp4upload player is detected, so it doesn't seem to be a 9anime issue. This isn't limited to just the '.pl' website ([example](https://9anime.to/watch/dead-mount-death-play.vvqy2/ep-3))

![image](https://github.com/MALSync/MALSync/assets/135276391/b0c54a23-508c-4595-9d52-20615d93ccba)

### Steps to reproduce the behavior

1. Open browser.
2. Go to a 9anime episode ([example](https://9anime.pl/watch/dead-mount-death-play.vvqy2/ep-3)).
3. Make sure that the episode is using a video player other than Mp4upload player, such as Vidstream.
4. Wait for the progress bar to infinitely load, before eventually failing.

### Browser

Chrome

### Type

Extension

### URL

https://9anime.pl/watch/dead-mount-death-play.vvqy2/ep-3

**Comment by lolamtisch** [comment]
I can not reproduce it. Did it ask you to add new permissions? Did you reload the window?

**Comment by RandomPersonUMet** [comment]
Yes I also removed the Web permissions before adding it back and restarted the browser. 
Did the same with the 9anime custom domains.

**Comment by lolamtisch** [comment]
Could you join discord? as it is always so slow in github.

https://discord.com/invite/cTH4yaw

**Comment by RandomPersonUMet** [comment]
Nevermind, after I removed the extension and added it back in, a lot of new site access options in the chrome extension manager appeared, which definitely weren't previously there (I previously checked every single one of them and used _Ctrl+F_). 

![image](https://github.com/MALSync/MALSync/assets/135276391/f3870d50-495b-4490-a11e-6b1ee3344deb)

This ended up fixing the issue, but thank you for your support.
