### ISSUE TITLE
Sync not working

### ISSUE THREAD

**Issue by Key-explanation** [MALSync/MALSync#1831]
### Describe the Bug

It was working fine when I used it on 9anime. But I recently changed to zoro and now it isn't even showing

### Steps to reproduce the behavior

1. Open zoro.
2. The miniMAL isn't showing or can I use it.

### Browser

firefox

### Type

Extension

### URL

https://sanji.to/watch/tonikawa-over-the-moon-for-you-2nd-season-18226?ep=101687

**Comment by lolamtisch** [comment]
Did you accept all new permissions?
https://malsync.moe/pwa/#/settings

**Comment by Key-explanation** [comment]
I accepted all permission.

**Comment by lolamtisch** [comment]
Restart browser and it should work. Firefox injection is a bit unreliable so It sometimes needs a page reload
