### ISSUE TITLE
Notes metadata conversion to links not applying to all entries on AniList

### ISSUE THREAD

**Issue by BrutuZ** [MALSync/MALSync#1832]
### Describe the Bug

The notes metadata for "Continue Reading" is only being converted for "current" (Reading) entries.
Entries marked as Planning MAL-Sync will hide their Notes speech-bubble icon, but won't add the reader favicon/link.

That is to say, the `mal-sync-stream` classed elements are only created for entries marked as "Reading" in the list view. The icon \ link \ element is rendered as expected in the entry's full page beside its title.

### Steps to reproduce the behavior

 - Access a user's list (linked below)
 - Notes icons are hidden
   - If the notes DO NOT include MAL-Sync metadata, they will be unhidden
 - Switch to Reading list
 - Notes icons are hidden but the MAL-Sync metadata in them is properly converted to the "Continue Reading" icons.

### Browser

Firefox 102.11.0esr (64-bit) on WIndows

### Type

Extension

### URL

https://anilist.co/user/BrutuZ/mangalist/Planning

**Comment by lolamtisch** [comment]
What would be the use case of this?

**Comment by BrutuZ** [comment]
Having quick and easy access on the list to the links previously stored by the extension.

![image](https://github.com/MALSync/MALSync/assets/7104931/223e0f7a-0d6d-4af8-b960-ed18cb89f37a)
1️⃣ Is what's expected but only happens to entries marked as "Reading"
2️⃣ Is what happens to entries marked as any other progress status
3️⃣ Is a clean browser profile without any extensions for reference

**Comment by lolamtisch** [comment]
Yeah we dont directly read the info and to minimize the load on anilist we only get the watching list. That is why I am asking for a use case. Because if it is completed it is not really that interessting where you watched it etc

**Comment by BrutuZ** [comment]
I see. The use-case is that those cursed "More like this" suggestions on reading pages often get me, so many entries get added to the ~~backlog~~ Planning list from them. Therefore it'd be handy to have the links at ready when getting to them rather than having to open each entry page.

A couple comments about the workings:
 1- If the Note for that entry wasn't parsed, wouldn't it be better to keep the icon visible then? Currenly hiding them all regardless makes it very hard for me to check at a glance for entries that might already have a link.
 2- Is it really necessary to get the Notes from the API? Their contents are loaded natively by the website as a parameter in the "speech bubble" element. Can the extension read that as the list is lazily populated or it only runs once and thus has to be available on page load?

**Comment by lolamtisch** [comment]
I mean the list view in the popup

**Comment by lolamtisch** [comment]
And I mean it is not a problem to use tags and notes. But that is why the implementation is not that Tylor made for injects and more focused on the popup as we have control over it.

**Comment by BrutuZ** [comment]
> I mean the list view in the popup

TIL about that view usability 😳. I basically just used the entry view and settings page so far. Yep, that kinda works for my use
