### ISSUE TITLE
Malsync crashing Vivaldi when trying to open a streaming site link

### ISSUE THREAD

**Issue by Demiko** [MALSync/MALSync#1834]
### Describe the Bug

When trying to use a link to some anime series on a streaming site upon pressing the link button (be it from the series page or the "resume" link on teh thimbnail) the browser immediately closes without any error report.

The crash does not happen when using the PWA "website" (https://malsync.moe/pwa). Only the extension popup causes the crash.

### Steps to reproduce the behavior

1) open any anime page in Malsync extension popup
2) press any streaming site link

or
1) activate "resume" links in Malsyc settings
2) press the resume link on any series in Malsync extension popup

### Browser

Vivaldi (latest, but was reproducible with a few recent releases as well)

### Type

Extension

### URL

9anime mainly, but crashes with any URL

**Comment by henrik9999** [comment]
https://github.com/MALSync/MALSync/issues/1522

You have to make an bug report at Vivaldi or something not the first time they broke it

**Comment by Demiko** [comment]
Seems like they've fixed their issues in the latest release. Closing the issue as resolved
