### ISSUE TITLE
Change domain name from animeworld.tv to animeworld.so

### ISSUE THREAD

**Issue by bigbear2** [MALSync/MALSync#1870]
### Describe the Bug

Yesterday the site animeworld.tv as change the last part of domain in animeworld.so. Now the plugin not working. the site is the same as before
Thx

### Steps to reproduce the behavior

go on any old link example this
https://www.animeworld.tv/play/kamisama-hajimemashita-2.1bZmK/xq6Co
and you redirect to 
https://www.animeworld.so/play/kamisama-hajimemashita-2.1bZmK/xq6Co 

### Browser

Opera

### Type

Extension

### URL

https://www.animeworld.so/

**Comment by lolamtisch** [comment]
Accept the new permissions in the extension popup and it should work again.
![image](https://github.com/MALSync/MALSync/assets/12599334/6b98d472-b6ba-4ea7-8241-2ba48243e18d)
