### ISSUE TITLE
sync is not working properly 

### ISSUE THREAD

**Issue by Astrokinng** [MALSync/MALSync#1876]
### Describe the Bug

it happening in both zoro and 9anime for me the sync dosent work .... accepted the new permissions it worked bt then the next day onward it didn't . uninstall and reinstalled everything bt still it isn't popping up.

### Steps to reproduce the behavior

1.open firefox 
2.open 9anime or zoro
3.open the anime 
4.the mal sync dosent show up 

### Browser

 firefox

### Type

Extension

### URL

https://9animehq.to/watch/bocchi-the-rock.1pyp/ep-1

**Comment by lolamtisch** [comment]
That is the beta/experimental version of 9anime. We dont support beta pages, because of the many changes they do and will break all the time. 
Please use one of the non beta/experimental pages

![image](https://github.com/MALSync/MALSync/assets/12599334/b905ff37-c833-4134-a341-3cf131477075)

**Comment by Astrokinng** [comment]
ok thnks

**Comment by Astrokinng** [comment]
ok thanks
