### ISSUE TITLE
[Website Request] Anix.to

### ISSUE THREAD

**Issue by suvxshya** [MALSync/MALSync#1883]
### Website name

Anix

### Website link

https://anix.to/home

### Website language(s)

English, Japanese

**Comment by Darklybars** [comment]
ye can someone from mods please add this website please

**Comment by derpsderps** [comment]
This, so bump. Basically the only true AnimixPlay clone with no ads.

**Comment by Source-Dom** [comment]
Can't inspect the page to code this

**Comment by Source-Dom** [comment]
Hi, I'm trying to add the page, but there's a script that blocks the devtools so I can't really do much without it. If anyone has a solution, I would like to know, please, thank you !

**Comment by otDan** [comment]
when will this be released?

**Comment by Source-Dom** [comment]
> when will this be released?

Soon, when pr is approved

**Comment by otDan** [comment]
uhm still not approved, does not seem soon lol

**Comment by Source-Dom** [comment]
Yeah, it's because there's some things I need to fix.

**Comment by otDan** [comment]
whenever there is the mal sync links panel, clicking on anix brings to aniwave from what I have seen
