### ISSUE TITLE
malsync not working 24/7

### ISSUE THREAD

**Issue by Pizza110face** [MALSync/MALSync#1890]
### Describe the Bug

when visiting episodes on 9anime from the home page it will not detect the new episode from the start and will only start working when I switch back and forth from a previously watched episode. thx to fahim2690 on discord for helping me understand what was wrong and how to fix it and seeing if it affected other domains

### Steps to reproduce the behavior

go from the home page to the newest episode of a series that has been tracking and it won't be tracking the episode.
fix: go back to the last watched episode and then move back to the newest and it will be tracking again.

### Browser

chrome (build 114.0.5735.199)

### Type

Extension

### URL

all of 9anime is having the issue but to be specific 9anime.gs

**Comment by lolamtisch** [comment]
Found the problem will be fixed in the next release
