### ISSUE TITLE
MalSync not working on Zoro(Now Aniwatch)

### ISSUE THREAD

**Issue by Key-explanation** [MALSync/MALSync#1910]
### Describe the Bug

Because of the recent rebrand of Zoro, the extension is not working on the website.

### Steps to reproduce the behavior

.

### Browser

firefox

### Type

Extension

### URL

aniwatch.to

**Comment by TheBat913** [comment]
it also does not work on Chrome

**Comment by lolamtisch** [comment]
Please add the new permissions that should popup on here [https://malsync.moe/pwa/#/settings](https://malsync.moe/pwa/#/settings/customDomains)

**Comment by Key-explanation** [comment]
The video isn't tracking

**Comment by lolamtisch** [comment]
Because of technical reasons it is not possible with the userscript. Only works for the extension.

**Comment by Key-explanation** [comment]
But I am using extension and it still doesn't track

**Comment by lolamtisch** [comment]
Do you have an example? It does not work for mobile either

**Comment by CrissZollo** [comment]
I use firefox and the extension. This was automatically added and given permission. 
![image](https://github.com/MALSync/MALSync/assets/69909259/2d0dc2eb-545b-4679-a037-71d8f0a0ff5f)

It is still not tracking.

**Comment by henrik9999** [comment]
> I use firefox and the extension. This was automatically added and given permission. ![image](https://user-images.githubusercontent.com/69909259/251569160-2d0dc2eb-545b-4679-a037-71d8f0a0ff5f.png)
> 
> It is still not tracking.

Firefox is buggy with permissions remove and readd them until it works

**Comment by FroggyRaven** [comment]
still not working for me
