### ISSUE TITLE
Suggestion: Show link to crunchyroll, instead of quicksearch

### ISSUE THREAD

**Issue by Source-Dom** [MALSync/MALSync#1942]
### Suggestion

So, I was wondering if it was possible to put directly the link leading to the anime on crunchyroll, when pressing the quicksearch button, instead of opening the menu that makes you choose what name you want to search.

For example, if I am on Jujutsu Kaisen season 2, in MAL-Sync, and I press the crunchryoll quicksearch button, it will open a menu where I have to choose between 3 ways to write the anime's name and after I press one of the three options it will search on crunchyroll for this anime. But instead, it would be great to just have the link leading directly to the anime, on crunchyroll, even if it doesn't show the right season, because you can't change the season within the link.

Also, I wouldn't mind helping with this idea, if it is approved and if there's a way for me to help.

**Comment by lolamtisch** [comment]
It already works like that. It is fjst for new animes it could take a bit until it appears.
![image](https://github.com/MALSync/MALSync/assets/12599334/87a01860-2a0c-46a7-b72f-8a6e80176034)
