### ISSUE TITLE
Explore Anime 

### ISSUE THREAD

**Issue by I-JMC** [MALSync/MALSync#1946]
### Suggestion

A new feature to explore Anime with custom filters and add them to your list like shown under.
![image_2](https://github.com/MALSync/MALSync/assets/99205448/6a04bf8c-b9dc-4eae-8404-b4990ca6721c)
This screenshot comes from Miru (https://github.com/ThaUnknown/miru)

**Comment by lolamtisch** [comment]
Problem is that the myanimelist api does not provide that functionality

**Comment by I-JMC** [comment]
But Anilist does (I think)

**Comment by henrik9999** [comment]
We are not going to implement features for a single tracker, just use the tracker site for that
