### ISSUE TITLE
[Website Request] aniwave

### ISSUE THREAD

**Issue by Qeuryx** [MALSync/MALSync#1958]
### Website name

aniwave

### Website link

https://aniwave.to/

### Website language(s)

English

**Comment by temmiekaz** [comment]
2nd on this.  9anime has been "updated" to aniwave

**Comment by SaiasiZKS** [comment]
Third this ig.

**Comment by lolamtisch** [comment]
Please add the new permissions on https://malsync.moe/pwa/#/settings/customDomains . It is possible that you need to restart browser once.

![image](https://github.com/MALSync/MALSync/assets/12599334/cb52c0c4-838e-426b-8431-f99169f4ad51)

**Comment by SrabonKhan0461** [comment]
wow the maintainers are fast

**Comment by MinamiHasaki** [comment]
How do we fix the quick links?

**Comment by lolamtisch** [comment]
Waiting

**Comment by MetriC-DT** [comment]
On Firefox, it seems I need to first be on the `aniwave.to` site then go to `Custom Domains` remove (and update) the 9anime permissions, then re-add them, then reload the aniwave site for it to work. Need to do this on every new browser session.

**Comment by edgedick** [comment]
Seconding what MetriC-DT said, have to remove the permissions, update, re-add, then refresh each time you open up a new page; unfortunately quite inconvenient.
