### ISSUE TITLE
[Website Request] AnimeGO

### ISSUE THREAD

**Issue by ooodnakov** [MALSync/MALSync#1977]
### Website name

AnimeGO

### Website link

animego.org

### Website language(s)

Russian

### Other details

It's my primary anime watching website and I will greatly appreciate its support)

**Comment by Source-Dom** [comment]
Needs vpn to go on website :/

**Comment by ooodnakov** [comment]
Thank you!
I will try it soon)

**Comment by NoPlagiarism** [comment]
[v0.9.7](https://github.com/MALSync/MALSync/releases/tag/0.9.7) is out with AnimeGO support added
