### ISSUE TITLE
Tamil Dub New Episode Tracker Not Available

### ISSUE THREAD

**Issue by jimmyedagawa78** [MALSync/MALSync#1979]
### Describe the Bug

The Tamil Dub for Jujitsu Kaisen (Crunchyroll) and Vinland Saga (Crunchyroll) does not show up in the language list for the episode tracker. Here is a screenshot from Vinland Saga
![image](https://github.com/MALSync/MALSync/assets/30567984/0861c96d-fa57-4472-a542-51de6db7fc53)

Here is an image of the Tamil Dub on Crunchyroll
![image](https://github.com/MALSync/MALSync/assets/30567984/2cb6f20a-2bb3-4e85-9a69-1ca65f28ead9)

### Steps to reproduce the behavior

No steps other than accessing the anime page of Jujitsu Kaisen or Vinland Saga on MAL-Sync and viewing the list of dub languages

### Browser

Chrome

### Type

Extension

### URL

https://malsync.moe/pwa/#/anime/49387

**Comment by lolamtisch** [comment]
We track using torrents and there are apparently no torrents with Tamil dub. Tracking crunchyroll is very hard because of all the geofencing, that is why we don't use it as source.

**Comment by jimmyedagawa78** [comment]
Aww man that's too bad, thanks for letting me know! I'll close this issue then
