### ISSUE TITLE
extension sometimes does not work on aniwave

### ISSUE THREAD

**Issue by susgaming82** [MALSync/MALSync#1982]
### Describe the Bug

when aniwave autoplays a new episode sometimes it sometimes will not work unless you reload, tracking does not work, no on site popups menus work, notifications such as the start watching prompt do not display. the only feature that seems to be functioning in this state is the auto fullscreen option.

### Steps to reproduce the behavior

open aniwave.to, play some of an episode in any series with more than 1 episode, then wait 40 minutes and finish playing the episode. when the next episode autoplays it usually shows the cloudflare loading screen and the extension is mostly nonfunctional. if i open another aniwave tab from an aniwave tab where malsync is broken then that tab is broken as well unless i reload it. 

### Browser

waterfox

### Type

Extension

### URL

aniwave.to

**Comment by lolamtisch** [comment]
I Imagine that waterfox has the same Problems as Firefox. Firefox is very unreliable when injecting into additional domains. Sometimes it works sometimes it does not. Nothing we can do there. Works perfectly on chromium based browsers with the same implementation. Will probably be fixed when migrating onto manifest v3, as they have a seperate endpoint to handle this usecase. But mv3 support in browsers is still a minefield.

**Comment by rauenzi** [comment]
Thank you @susgaming82 this was my issue as well!
