### ISSUE TITLE
List sync round down option for decimal scoring systems

### ISSUE THREAD

**Issue by emukus** [MALSync/MALSync#2011]
### Suggestion

AniList has a decimal point scoring system while MAL does not. I would prefer an option to round down when syncing scores between the two, with AniList as the master list. Currently, the list sync feature would round up all my MAL scores, which I absolutely do not want to happen.

**Comment by lolamtisch** [comment]
We use normal rounding 0.4 down and 0.5 up. You just need to rate shows correctly.

**Comment by emukus** [comment]
Rating shows is always personal and subjective so there isn't a "correct" way to do it. Wouldn't hurt to give users an option to always round up or always round down.

**Comment by lolamtisch** [comment]
Objectively speaking normal rounding results in a lower deviation in mean scores between your lists for Mal and anilist. As these scores are used for calculating the community score an anime has on anilist/Mal, it makes sense that as far as possible your scores should have a similar influence on the score on both sites and not being offset by rounding everything down. This at least was the idea.

**Comment by emukus** [comment]
The logic behind your explanation is good. However, the rounding offset will always occur as long as MAL does not allow decimal scores. For example, 1,000 people rating a show 85% on Anilist which then gets rounded up to a 9 on MAL still results in a significant difference between the two community scores. Even with the current system, rounding up still deviates the score by a whole 0.5. A small percentage of those people rounding down would actually lower the size of the deviation.

In my case, a show that I would give an 8.5 on AniList is not the same type of show that I would rate a perfect 9 on MAL. I would much rather the 8.5 or 8.6 show get rounded down to an 8 because I feel it has not crossed that threshold to jump to a perfect 9. Otherwise, there would be no point in me using AniList's decimal scoring system in the first place. (As you can see, it's a very subjective thing but that's just how my brain is wired).

But I understand if your team does not want to add that functionality. I guess I'll just stick to manually scoring them individually. Thank you for your time.
