### ISSUE TITLE
The extension fails to recognize the English title of a manga

### ISSUE THREAD

**Issue by KreiosSama** [MALSync/MALSync#2018]
### Describe the Bug

The problem that is occurring is that, there is a manga that if I search the manga with the Japanese title on the miniMAL it exists. But when I'm reading the manga or press the add button, even if I remove it from the local storage, the extension saves always as a local entree and don't associate with the MyAnimeList entree

### Steps to reproduce the behavior

1 -> Go to this manga - https://mangadex.org/title/9b12ac90-9407-4fe8-9de8-c8f4fe65df6f
2 -> Press 'Add' or start reading it
3 -> It saves as local
4 -> If you search the title in japanese, on the popup window of the extension, it will show that the title exists on MAL/Anilist/etc

### Browser

Google Chrome

### Type

Extension

### URL

https://mangadex.org/title/9b12ac90-9407-4fe8-9de8-c8f4fe65df6f

**Comment by lolamtisch** [comment]
https://github.com/Franciscoseipel/Mal-for-Kissanime-Greasymonkey-/raw/master/Screenshots/Wrong%20recognition.gif
