### ISSUE TITLE
Asurascans domain change

### ISSUE THREAD

**Issue by AeolusDev** [MALSync/MALSync#2026]
### Describe the Bug

Asurascans no longer use the domain [asura.gg](https://asura.gg) but instead uses the domain [asuracomics.com](https://asuracomics.com/)

### Steps to reproduce the behavior

Visiting the asurascans website now redirects users to https://asuracomics.com/ instead of asura.gg

### Browser

Brave, chrome, edge, firefox

### Type

Extension

### URL

https://asuracomics.com/

**Comment by lolamtisch** [comment]
New domain added. Please follow the steps bellow

![image](https://github.com/MALSync/MALSync/assets/12599334/e61b6d64-2646-4ebf-b4b8-a40b59087e1b)
https://malsync.moe/pwa/#/settings/customDomains
