### ISSUE TITLE
correction search not workin on hulu

### ISSUE THREAD

**Issue by pavonismc** [MALSync/MALSync#2031]
### Describe the Bug

When I type the correction search text field nothing happens

### Steps to reproduce the behavior

You accept the mini button at the bottom left it shows you the enemy that it thinks you're currently watching and gives you options to offset the episodes and then gives you an option to correct the search when you tap that nothing happens

### Browser

vivaldi

### Type

Extension

### URL

https://www.hulu.com/series/f1f053e2-ed2e-437c-94c6-c4e557e79bbc

**Comment by henrik9999** [comment]
we dont have a hulu account so we cant check it
