### ISSUE TITLE
Can't see the UI or settings page

### ISSUE THREAD

**Issue by cyber-sec0** [MALSync/MALSync#2057]
### Describe the Bug

It used to show the settings button and everything else only on Crunchyroll, and all other websites never have the bottom right settings page, but now even Crunchyroll does not have the settings button.

Also on 9anime, it does not sync or ask to sync or ask me to log in, because I have deleted and reinstalled the script.

Now I have no way to configure it or to log in.

This is for the tampermonkey/edge/win 11 extension.

I disabled all my other scripts and extensions on Crunchyroll, and I am still unable to see any pop-ups or buttons from mal sync.

I think that the only way to truly solve this bug is to make the setting button the on the tampermonkey extension itself, not a random "HTML" button somewhere on the page.

### Steps to reproduce the behavior

Open an anime website that it is supposed to work on

### Browser

edge

### Type

Userscript

### URL

https://www.crunchyroll.com/pt-br/watch/GRMGPX4VR/doubts-about-youth-the-telepathy-club-appears

**Comment by lolamtisch** [comment]
Settings can be found here. https://malsync.moe/pwa/#/settings
9anime did rebrand and is now aniwave. Should start working again since the update today.
I recommend to use the extension over the userscript.

**Comment by cyber-sec0** [comment]
So people are just supposed to know the settings url?

I already have a good amount of extensions, I do not want to use one more if the script does the same and works...
But recently any website simply does not show anything at all for the script, so I do not even know if it is running and working or not...
