### ISSUE TITLE
[Website Request] AnimeXin

### ISSUE THREAD

**Issue by Darkhhour** [MALSync/MALSync#2068]
### Website name

Animexin

### Website link

https://animexin.vip/

### Website language(s)

English

### Other details

Animexin.xyz and Animexinax.com have both been offline for a while now, mal-sync doesn't seem to detect Animexin.vip even when added as custom domain.

**Comment by silou** [comment]
Hello,

I also have this problem I think : 

URL to reproduce : https://animexin.vip/martial-master/
Screenshot : https://drive.google.com/file/d/1Zh7-USSLggv1FBzKSvb56OzNZjXUTP-i/view?usp=drive_link

PC Windows 10 / Chrome Browser : Version 117.0.5938.132 (Build officiel) (64 bits)
MAL-Sync [0.9.6]

Good extension by the way :)
