### ISSUE TITLE
Anix links to Aniwave

### ISSUE THREAD

**Issue by Loidauk** [MALSync/MALSync#2069]
### Describe the Bug

Anix links to Aniwave instead of Anix

### Steps to reproduce the behavior

Under any given anime, click Anix, to open streaming.
![image](https://github.com/MALSync/MALSync/assets/76977614/7199b332-1687-48b0-8d87-a53c6e7d3e93)

### Browser

Brave

### Type

Extension

### URL

https://anix.to/home

**Comment by lolamtisch** [comment]
Links will be removed in the next release and will be replaced with a quick search.
