### ISSUE TITLE
Unable to open userscript settings modal on condensed keyboard

### ISSUE THREAD

**Issue by bbeenn1** [MALSync/MALSync#2079]
### Suggestion

After one of the updates a while ago that changed the default behavior for the floating button to open the correction dialog instead of settings, I have been unable to open the settings modal on one of my chromebooks that utilize a condensed keyboard layout.

I would like to determine if there is a way to change the keybind in the userscript or to override a variable somewhere (I tried searching through it, but I am not a programmer and it looks condensed somehow as well to me)

**Comment by lolamtisch** [comment]
https://malsync.moe/pwa/#/settings

**Comment by bbeenn1** [comment]
Specifically I was looking for adjusting the Adult variant, which does not have that pwa
