### ISSUE TITLE
Userscript logging in

### ISSUE THREAD

**Issue by Kdog88** [MALSync/MALSync#2083]
Hi, how do i login to my mal sync account from the user script on ios/ipados? My laptop just died this week so i'd like to login to my account via the userscript on my ipad and iphone, but ihdk how to login to my account within the userscript that i got from your website. Any help with info on this subject would be greatly appreciated! Tysm for your time and dedication to this project. And tysm for your help and support with this inquiry!

**Comment by Jerit3787** [comment]
Hi, you can use the PWA to do so. https://malsync.moe/pwa

**Comment by Kdog88** [comment]
It just loads a blank white screen?

**Comment by Jerit3787** [comment]
> It just loads a blank white screen?

If it shows like that, that means the application you used is not supported by the userscript

May I know what app you're using?

**Comment by Kdog88** [comment]
An app called Userscripts

**Comment by Jerit3787** [comment]
> An app called Userscripts

That is not supported tbh

**Comment by Kdog88** [comment]
Do you have one that you suggest and recommend that works?

**Comment by Jerit3787** [comment]
> Do you have one that you suggest and recommend that works?

Refer above message.

**Comment by Kdog88** [comment]
Yes, I read that comment, but do you know of an app that supports mal sync's script?

**Comment by Jerit3787** [comment]
> Yes, I read that comment, but do you know of an app that supports mal sync's script?

above app is working. It has already show it advantages & disadvantages

**Comment by Kdog88** [comment]
No, it's not working,hence the white screen...sorry, not trying to be rude..,![image](https://github.com/MALSync/MALSync/assets/49170700/9f2cadf2-4b68-4c7f-a96f-842f7d32e2a2)I clicked on your link and am getting nothing but a white screen.

**Comment by Jerit3787** [comment]
> No, it's not working,hence the white screen...sorry, not trying to be rude..,![image](https://user-images.githubusercontent.com/49170700/273396053-9f2cadf2-4b68-4c7f-a96f-842f7d32e2a2.png)I clicked on your link and am getting nothing but a white screen.

btw, is this like you put on the home screen. Because, it only works when you've opened in safari. Like I said, it kinda quirking when using iphone/ipad. The macaque works better but still tedious to set it up. I've tried the userscript app but it doesn't work.

**Comment by Kdog88** [comment]
![image](https://github.com/MALSync/MALSync/assets/49170700/9ce5f2dd-b2bf-4e70-adb4-6dcc5be405a4) this is im safari

**Comment by Jerit3787** [comment]
> this is im safari
Are you using the app I've recommended and enabled?

**Comment by Kdog88** [comment]
Yes

**Comment by Jerit3787** [comment]
> Yes

Could you open the extension app menu?

**Comment by Kdog88** [comment]
![image](https://github.com/MALSync/MALSync/assets/49170700/07588d79-b6cd-47d7-86ea-178f53ed3a44)

**Comment by Jerit3787** [comment]
You didn't install macaque :(

**Comment by Kdog88** [comment]
Okay, it's installed but how do I add mal sync to macacque?

**Comment by Jerit3787** [comment]
> Okay, it's installed but how do I add mal sync to macacque?

1. Open macaque app.
2. Open safari and enable macaque in extensions settings. Make sure disable others extensions app.
3. Open MALSync github and click on the userscript link.
4. When prompted to view / download, click view. Macaque page will appear.
5. Click save button on macaque.
6. Close and view MALSync. If does not appear, check the macaque on the safari menu and check if MALSync is enabled.
7. Walla! should work tho.

**Comment by Jerit3787** [comment]
A video tutorial
https://github.com/MALSync/MALSync/assets/64518580/3d457781-331e-4c1e-a52f-2a400db7c0eb

**Comment by Kdog88** [comment]
Tysm for your help and your helpful video! I'm a visual learner so the video was the most helpful! Two last questions....I set it up on my phone...I still have to redo everything on my ipad too, yes? And if so, it's the same exact steps, correct? And lastly, the script will run automatically on sites that I enabled it to run on, like the desktop browser version, yes?

**Comment by Jerit3787** [comment]
> Two last questions....I set it up on my phone...I still have to redo everything on my ipad too, yes? And if so, it's the same exact steps, correct?

Yeah, should be the same steps as well.

> And lastly, the script will run automatically on sites that I enabled it to run on, like the desktop browser version, yes?

yeah it runs at sites it supported

**Comment by Kdog88** [comment]
Gotcha! Tysm for all your help with this today 😁😁

**Comment by Jerit3787** [comment]
Okay, please close this issue as completed to avoid any confusion with other issues.
