### ISSUE TITLE
TMO (Spanish site) changed its URL from lectortmo.com to visortmo.com

### ISSUE THREAD

**Issue by duradara** [MALSync/MALSync#2090]
### Describe the Bug

Nothing else seems to have changed.

### Steps to reproduce the behavior

You can go to the old site and it redirects you to the new one.

### Browser

Edge

### Type

Userscript

### URL

lectortmo.com, visortmo.com

**Comment by lolamtisch** [comment]
Because they decided to move the chapters to many random domains and only some mangas remain on visortmo, we decided to remove support for the page, as it is too much work to keep it working.

**Comment by duradara** [comment]
Would I be posible to keep supporting with a note of needing a redirector extension to make it work?
I use this [extension](https://chrome.google.com/webstore/detail/redirector/ocgpenflpmgnfapjedencafcfakcekcd) to redirect the chapters to the main page like this  
![Screenshot 2023-10-20 184137](https://github.com/MALSync/MALSync/assets/50158352/ec2b1328-14e8-4b46-bb34-34177e25b685)

 Although if you don't want to its no problem.  
Sorry if my english is bad.

**Comment by lolamtisch** [comment]
We don't want to support pages that need additional tools to work.

But if you are willing you could take over the maintenance responsibility for the website in malsync. You will need to always check if there are new domains and open pull requests to add them.

**Comment by duradara** [comment]
> But if you are willing you could take over the maintenance responsibility for the website in malsync. You will need to always check if there are new domains and open pull requests to add them.

I don't know how to program, would I still able to do it? if so what should I do?

**Comment by lolamtisch** [comment]
In this case it is probably just adding the domains. Not more complex than changing a config file. https://github.com/MALSync/MALSync/blob/master/src/pages/tmofans/meta.json

If you are interested the easiest way is to join our discord.

**Comment by duradara** [comment]
> In this case it is probably just adding the domains. Not more complex than changing a config file. https://github.com/MALSync/MALSync/blob/master/src/pages/tmofans/meta.json
> 
> If you are interested the easiest way is to join our discord.

Doing it like this adding all the URL domains? 
![Screenshot 2023-10-21 130028](https://github.com/MALSync/MALSync/assets/50158352/bc6517a4-2cc9-4704-b180-edafec848138)

**Comment by lolamtisch** [comment]
Yeah pretty much. Open an pull request, you can edit the file directly on GitHub too. I will check if it need additional changes for it too work. And you will need to add new domains in the future when new ones get added

**Comment by duradara** [comment]
> Yeah pretty much. Open an pull request, you can edit the file directly on GitHub too. I will check if it need additional changes for it too work. And you will need to add new domains in the future when new ones get added

I just made a pull request and added all the URLs I had, tell me if I did something wrong.

**Comment by lolamtisch** [comment]
There is no pull request.
It should appear on this page if everything was done correctly
https://github.com/MALSync/MALSync/pulls

**Comment by duradara** [comment]
> There is no pull request. It should appear on this page if everything was done correctly https://github.com/MALSync/MALSync/pulls

For me it appears at the top of the page, did I do something wrong?
![1](https://github.com/MALSync/MALSync/assets/50158352/e28796ce-5364-4f9e-9d95-f104523106d8)

**Comment by duradara** [comment]
nvm I fix it
