### ISSUE TITLE
Asura Scans Domain change

### ISSUE THREAD

**Issue by Yakiyo** [MALSync/MALSync#2094]
### Describe the Bug

Asurascans changed their domain name from asuracomic to [asuratoon.com](https://asuratoon.com) so malsyncs not working on the site anymore.

### Steps to reproduce the behavior

Just open up the website on any browser ig

### Browser

Firefox

### Type

Extension

### URL

https://asuratoon.com/

**Comment by henrik9999** [comment]
New domain added. Please follow the steps bellow

![image](https://github.com/MALSync/MALSync/assets/22085664/ef3213ea-3c3d-4b13-8a8c-efc863b825b3)
https://malsync.moe/pwa/#/settings/customDomains
