### ISSUE TITLE
Really weird domain permission requests from "tmofans"

### ISSUE THREAD

**Issue by jp-man25** [MALSync/MALSync#2131]
### Describe the Bug

I checked the recent "missing permissions detected" list and found a bunch of random websites from "tmofans", most of which seem to be cooking and car websites... Completely unrelated to anime or manga.

![image](https://github.com/MALSync/MALSync/assets/93134243/c0075e52-4dc8-4cdd-a38a-843dffb61782)
![image](https://github.com/MALSync/MALSync/assets/93134243/cbf73870-8eb4-47a1-a0c9-a8af2e41df0f)

### Steps to reproduce the behavior

asd

### Browser

asd

### Type

Extension

### URL

asd

**Comment by henrik9999** [comment]
Sadly tmo uses those domains on some chapters, and for malsync to work we need them to be added
