### ISSUE TITLE
Missing permissions - can't add them

### ISSUE THREAD

**Issue by Odin-swe** [MALSync/MALSync#2133]
### Describe the Bug

When playing an episode on aniwave.to it won't update the progress automatically. The little popup at the bottom says permissions are missing and a link to "Add" them. If you click it a new page opens and a link-text with red background says: "The browser or the current window don't support adding permissions, please retry it with the url https://malsync.moe/pwa or use the extension popup". But if you click that text it just opens up another window just like the first.

![MAL-sync Error](https://github.com/MALSync/MALSync/assets/136379145/65d405c6-b093-444d-8495-b662f44773c8)

![MAL-sync Error2](https://github.com/MALSync/MALSync/assets/136379145/4a9ad2f6-38c3-4408-925d-272b85d600b9)

### Steps to reproduce the behavior

Just as soon as you navigate to a series page the little popup at the bottom (collapsed) starts loading. But I guess it times out and shows the missing permissions-thing. I'll attach an url directly to a series.

### Browser

Firefox 119.0

### Type

Extension

### URL

https://aniwave.to/watch/sousou-no-frieren.3rp2y/ep-10

**Comment by GuiReboucas** [comment]
Same thing for me

**Comment by lolamtisch** [comment]
Firefox only allows adding permissions in the extension popup, like stated in the message.

But firefox currently has problems with the allowed permissions. We are looking into it.

**Comment by WitherredAway** [comment]
> Firefox only allows adding permissions in the extension popup, like stated in the message.
> 
> But firefox currently has problems with the allowed permissions. We are looking into it.

I think I'm getting the same problem. I'm on Kiwi Browser (Google Chrome clone but with extensions support for mobile). [It has issues with adding permissions](https://github.com/MALSync/MALSync/issues/1725) but it worked fine with aniwave.to until recently. Now for some reason it no longer detects the "Vidplay" source, while "Filemoon" works fine. But Filemoon sucks. The player often breaks, buffers a lot, subtitles are different from Vidplay and also aniwave's intro/outro skip isn't supported.

**Comment by lolamtisch** [comment]
It is unrelated. Kiwi has no permissions support. So there is no fix

**Comment by WitherredAway** [comment]
> It is unrelated. Kiwi has no permissions support. So there is no fix

Got it, thanks for the response. Should I create an issue for it randomly stopping working with the Vidplay video source or is that also related to the lack of permission support? Sorry, don't mean to hijack this issue.

**Comment by lolamtisch** [comment]
> Got it, thanks for the response. Should I create an issue for it randomly stopping working with the Vidplay video source or is that also related to the lack of permission support? Sorry, don't mean to hijack this issue.

Vidplay changes its domain all the time, so we need to ask for new permissions. Custom domains is a way to add these permissions between releases, because we are only able to do a release every 1-2 months. As kiwi does not have that functionality it will be broken until the next release drops. Which should be in the next few days for chromium.

Firefox is already online, please update to the newest version and it should work again.
