### ISSUE TITLE
Change the RPC from "Playing" to "Watching"

### ISSUE THREAD

**Issue by barraIhsan** [MALSync/MALSync#2136]
### Suggestion

Change the RPC "prefix" from Playing to Watching, like these bot does:
![image](https://github.com/MALSync/MALSync/assets/57800056/176396b5-e46b-47c8-b658-5fc9121345db)

Note : IDK if its possible or not, [some people say that its possible](https://stackoverflow.com/questions/55095596/discord-bot-status-from-playing-to-watching), but [the official discord developer protal say it's not possible](https://discord.com/developers/docs/game-sdk/activities#data-models-activitytype-enum):
![image](https://github.com/MALSync/MALSync/assets/57800056/87b2b58c-b1ab-45b3-979c-48d51a8a415c)

**Comment by henrik9999** [comment]
It's only possible for bots, or self bots which are against discord terms so we will not add that

**Comment by barraIhsan** [comment]
> It's only possible for bots, or self bots which are against discord terms so we will not add that

update: advaith says that we can do that using oauth (idk if it's true or not)
https://twitter.com/advaithj1/status/1777912987418034207

**Comment by barraIhsan** [comment]
update: advaith (who is now an intern at discord) updated the rpc so that now it's possible to have "watching"
https://twitter.com/advaithj1/status/1816655583107510517

**Comment by barraIhsan** [comment]
consider reopening the issue?

**Comment by NoPlagiarism** [comment]
https://discord.com/developers/docs/topics/oauth2#shared-resources-oauth2-scopes

> activities.write - allows your app to update a user's activity - ** not currently available for apps **

WatchDis is probably whitelisted

**Comment by barraIhsan** [comment]
> update: advaith (who is now an intern at discord) updated the rpc so that now it's possible to have "watching"
> https://twitter.com/advaithj1/status/1816655583107510517

no, the rpc one
https://discord.com/developers/docs/topics/rpc#setactivity
(it says that rpc is currently in private beta tho)

And if that was the case, maybe just send a request to discord just like cider?
https://twitter.com/UseCider/status/1816534383274217672

**Comment by NoPlagiarism** [comment]
> the rpc one

Link you provided is for Rich Presence Client, which MAL-Sync + Discord-RPC-Extension are already using to connect to **your local** Discord client. WatchDis uses API through oauth. API for changing activity using oauth is undocumented and has only one mention in docs (AFAIK). And it says: **not currently available for apps**.

> just like cider

From this tweet I can't tell if they are talking about oauth or just using "Listening". My guess is for second. Can't investigate further into Cider, cuz I don't use it. Maybe I'll check it out somehow later

> just send a request to discord

Quoting Akkusativ / lolamtisch

> As expected discord does not want to give us the permission. So rip

advaith really can change the game for all RPC in Discord. So, maybe it will be possible soon

**Comment by NoPlagiarism** [comment]
Fixed in https://github.com/MALSync/MALSync/commit/109a04ed61b728fd443d1cb3db068344903b1a80

**Comment by barraIhsan** [comment]
Very nice! Thank you!
