### ISSUE TITLE
Doesn't detect player

### ISSUE THREAD

**Issue by Key-explanation** [MALSync/MALSync#2138]
### Describe the Bug

As the title says, tracker doesn't track the player. I tried adding new permissions, removing and re-adding already existing ones.

### Steps to reproduce the behavior

1. Open aniwave.to
2. play any anime
3. tracker doesn't track the video progress

### Browser

firefox

### Type

Extension

### URL

aniwave.to

**Comment by Key-explanation** [comment]
why was this closed?

**Comment by itsguan** [comment]
Still getting this issue today
