### ISSUE TITLE
[BUG] Aniwave "Failed to detect player"

### ISSUE THREAD

**Issue by RazredgeBR** [MALSync/MALSync#2150]
### Describe the Bug

Recently the extension just never "sees" the player, doesn't automatically update watched episodes, and even though I've consistently been adding the "missing permissions" it requests, it just never changed anything whatsoever.
Just a couple of minutes ago it happened again when I watched an episode of "Sousou no Frieren" (happened to every episode tbh). And has also happened with other animes, like Jujutsu Kaisen, Tate no Yusha and others.
I don't know whether it's a new player, new server, or whatever, but it should at least be able to auto-update the last episode I've watched when the episode finishes.
I have managed to at least "force" MALSync to default to Aniwave by manually updating via the "pop-up" at the bottom of the screen.

### Steps to reproduce the behavior

Go to "https://aniwave.to/" and watch any episode of any anime, and see that it doesn't update when finishing the episode.
At least I can confirm this just happened right now, and has happened on the past weeks. The last instance was https://aniwave.to/watch/sousou-no-frieren.3rp2y/ep-5, using the first server "Vidplay" on the list for hard subbed episode.
![2023-11-20 160011](https://github.com/MALSync/MALSync/assets/82561645/c1b3117c-a349-4ccf-aae3-503491a4451c)

### Browser

FireFox DEV 120.0b9 (64-bit)

### Type

Extension

### URL

https://aniwave.to/

**Comment by henrik9999** [comment]
update to the latest version of the extension which was released today (0.9.7)

**Comment by RazredgeBR** [comment]
Well, I just updated, but now I'm banned for 24h from Aniwave... WTF? Anyway, I hope it's fixed, gonna find out tomorrow.

**Comment by henrik9999** [comment]
> Well, I just updated, but now I'm banned for 24h from Aniwave... WTF? Anyway, I hope it's fixed, gonna find out tomorrow. But, thank you nonetheless!

they ban you if you open devtools on the page
