### ISSUE TITLE
Domain link update

### ISSUE THREAD

**Issue by GladRedFox719** [MALSync/MALSync#2158]
### Website name

Gogoanime

### Website link

https://anitaku.to/

### Website language(s)

English

### Other details

Just got it's domain updated.
![Screenshot_20231125_071541_Kiwi Browser](https://github.com/MALSync/MALSync/assets/96375823/5b01a224-bbeb-4f9e-9443-2fd4a4764b96)

**Comment by henrik9999** [comment]
New domain added. Please follow the steps bellow

![image](https://github.com/MALSync/MALSync/assets/22085664/ef3213ea-3c3d-4b13-8a8c-efc863b825b3)
https://malsync.moe/pwa/#/settings/customDomains
