### ISSUE TITLE
MALSync does not trigger on double page view on MangaDex

### ISSUE THREAD

**Issue by PythonCoderAS** [MALSync/MALSync#2184]
### Describe the Bug

If you use the double page reader option on MangaDex, the extension will not update MAL even if you get to the last page.

### Steps to reproduce the behavior

1. Set MangaDex reader to double page mode
2. Read chapter being tracked by MALSync
3. Go to last page

### Browser

Chrome

### Type

Extension

### URL

https://mangadex.org/chapter/31a7a011-ef89-4467-8f49-06b9056eb87f

**Comment by lolamtisch** [comment]
Could take 1-2 days until your cache invalidates then it should work again.
