### ISSUE TITLE
[shinden.pl] Wrong anime connected to MAL

### ISSUE THREAD

**Issue by RDKRACZ** [MALSync/MALSync#2191]
### Describe the Bug

On https://shinden.pl/series/55341-22-7 the bar with status, episode management, and the score is loaded for animegataris, not 22/7

### Steps to reproduce the behavior

Open the provided link and hover over the loaded score

### Browser

Brave

### Type

Extension

### URL

https://shinden.pl/series/55341-22-7

**Comment by henrik9999** [comment]
![Wrong recognition (2)](https://github.com/MALSync/MALSync/assets/22085664/cfffaa63-c3c8-41ef-bf23-333dc5eed5d8)

**Comment by RDKRACZ** [comment]
Will this fix it for other users too or just locally for me?

**Comment by henrik9999** [comment]
On this site just for you
On sites that have database support for everyone
https://github.com/MALSync/MALSync/blob/master/pages.md
