### ISSUE TITLE
Mangapark: Malsync not detecting anything

### ISSUE THREAD

**Issue by adryan475** [MALSync/MALSync#2193]
### Describe the Bug

Mangapark recently updated their website and ever since, MalSync has not been detecting anything on either the old version or new version of the website.

### Steps to reproduce the behavior

just open any manga on the website and the MalSync extension will not detect it

### Browser

Opera/Chrome

### Type

Extension

### URL

mangapark.net

**Comment by perseiids** [comment]
same i cant find any help about it , if u find any send me

**Comment by adryan475** [comment]
> version 5 is unsupported currently you have to use version 3 of mangapark

Does that mean I should make a website request for V5?

**Comment by henrik9999** [comment]
no this issue is already enough
