### ISSUE TITLE
Malsync doesn't work

### ISSUE THREAD

**Issue by Key-explanation** [MALSync/MALSync#2196]
### Describe the Bug

It says that "Your IP has been banned on AniList, change your IP or wait for it to get unbanned. A temporary outage could also be a reason." 

### Steps to reproduce the behavior

.

### Browser

firefox

### Type

Extension

### URL

https://aniwave.vc/watch/kamonohashi-ron-no-kindan-suiri.llxk6/ep-12

**Comment by henrik9999** [comment]
anilist is api down
from their discord
![image](https://github.com/MALSync/MALSync/assets/22085664/37cadb35-a6c5-48dc-9ab7-d30dc5df1f81)
