### ISSUE TITLE
Firefox Unable to Add Missing Permission [PWA]

### ISSUE THREAD

**Issue by dabreadman** [MALSync/MALSync#2200]
### Describe the Bug

Was watching an anime, Mal-sync popped up, tried following the steps to add missing permission, no dice.
![image](https://github.com/MALSync/MALSync/assets/43485369/1058c5a6-c074-4e08-820e-89748ee37218)

### Steps to reproduce the behavior

https://malsync.moe/pwa/#/settings/customDomains

### Browser

Firefox

### Type

Extension

### URL

https://malsync.moe/pwa/#/settings/customDomains

**Comment by lolamtisch** [comment]
please retry in the extension button. 
![image](https://github.com/MALSync/MALSync/assets/12599334/6b3d4f18-7974-42eb-bb8d-5c144ad16f7e)

**Comment by henrik9999** [comment]
> On **Firefox Desktop** you can __not__ accept the permission using the url. You need to open the same settings page in the **extension popup** und accept it there.
