### ISSUE TITLE
database flexibility

### ISSUE THREAD

**Issue by Apurvsikka** [MALSync/MALSync#2204]
### Suggestion

hey devs,
as most of the people who use this service, may have more than one anime database account(mal,anilist etc)  , so it is very hard to keep them all up to date , please add a functionality to add more than one database to malsync it will be very hepful
thanks,
my sincere regards ,
read my username

**Comment by henrik9999** [comment]
https://github.com/MALSync/MALSync/issues/1092#issuecomment-1095984452
