### ISSUE TITLE
Quicksearch link for YugenAnime is incorrect

### ISSUE THREAD

**Issue by ericnoble1991** [MALSync/MALSync#2217]
### Describe the Bug

When clicking on the YugenAnime Quicksearch link it opens https://yugenanime.ro/search/?q=suki+tte+ii+na+yo. instead of https://yugenanime.tv/discover/?q=suki+tte+ii+na+yo.

### Steps to reproduce the behavior

Clicking on YugenAnime Quicksearch link. Anime example I used for testing: https://yugenanime.tv/discover/?q=suki+tte+ii+na+yo.

### Browser

Edge (Chromium)

### Type

Extension

### URL

https://yugenanime.tv/discover/?q=suki+tte+ii+na+yo.

**Comment by animesyt** [comment]
https://dizikorea.co/

**Comment by luminara** [comment]
I have submitted a pull request #2235 regarding this issue.
