### ISSUE TITLE
NotFoundError: No Entry Found for malId 49556

### ISSUE THREAD

**Issue by MisterTh** [MALSync/MALSync#2222]
### Describe the Bug

For a few Anime I get a NotFoundError, so the list I'm syncing always has open entries

### Steps to reproduce the behavior

I have made a list entry for 'Love all play' (malId: 49556). For MAL and Simkl its okay, but for Kitsu I get the Error, if I try to sync them. Also get the error for a few other Anime enties. It doesn't matter if I manually set the entry in Kitsu.
Don't know if its an error on your side or of Kitsu (Sorry)

### Browser

Firefox 121.0 (64-Bit)

### Type

Extension

### URL

https://myanimelist.net/anime/49556/Love_All_Play

**Comment by lolamtisch** [comment]
You have to request a correction on kitsu, because the malid is missing.
https://github.com/MALSync/MALSync/wiki/List-Sync#x-exists-on-page-y-but-it-doesnt-sync-it
