### ISSUE TITLE
Linking the episode when clicking "Continue watching", not the anime page

### ISSUE THREAD

**Issue by maximedrouhin** [MALSync/MALSync#2223]
### Suggestion

Currently, when you click the "Continue watching" link for an anime, you are redirected to the anime page (e.g. https://www.crunchyroll.com/series/G1XHJVEXE/shadows-house) instead of the current episode (e.g. https://www.crunchyroll.com/watch/G14U4EG33/a-birdcage-and-flowers for Episode 9 of Season 1).

Intuitively, this might be a bit difficult if you can't rely on MyAnimeList to provide the link to the specific episode, but it seems like a very important feature to me. So, could you please consider implementing it?

**Comment by lolamtisch** [comment]
Is already a feature. If it has that information it will link the next episode. It checks for the next episode while watching, if the episode is not out at that point or you switch/reset devices, because saved localy only, then it does not link it.
