### ISSUE TITLE
[Feature Request] Playback Speed Support

### ISSUE THREAD

**Issue by lemonadeforlife** [MALSync/MALSync#2230]
### Suggestion

Ability to increase/decrease video speed by pressing certain custom key.

**Comment by NoPlagiarism** [comment]
Look at videospeed extension:
- [Chrome version](https://chromewebstore.google.com/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk) | [Source](https://github.com/igrigorik/videospeed)
- [Firefox version](https://addons.mozilla.org/en-US/firefox/addon/videospeed) | [Source](https://github.com/codebicycle/videospeed)

**Comment by lemonadeforlife** [comment]
Thanks for the suggestion.
The Firefox extension seems outdated and not actively maintained.
I recommend this one if anyone wants to 

- [Firefox Version](https://addons.mozilla.org/en-US/firefox/addon/web-video-speed-controller/) | [Source](https://github.com/aynorway/web-video-speed-controller)
