### ISSUE TITLE
Extension not Working

### ISSUE THREAD

**Issue by CardinalBirb** [MALSync/MALSync#2245]
### Describe the Bug

Says I'm banned or outage but I'm not banned. Is the extension out for days now?

### Steps to reproduce the behavior

I'm just using the extension on firefox on android.

### Browser

Firefox

### Type

Extension

### URL

any for MAL

**Comment by henrik9999** [comment]
What do you see on the API https://api.myanimelist.net/

**Comment by CardinalBirb** [comment]
![Screenshot_20240128_162431_Firefox](https://github.com/MALSync/MALSync/assets/86525025/f451ac39-c381-489c-bd42-caa97e78f143)
![Screenshot_20240130_071658_Gmail](https://github.com/MALSync/MALSync/assets/86525025/86a62012-1c6e-48eb-94af-5be9532ce17a)

**Comment by CardinalBirb** [comment]
> What do you see on the API https://api.myanimelist.net/

![Screenshot_20240130_072229_Firefox](https://github.com/MALSync/MALSync/assets/86525025/f2ec3f20-24a3-4f8e-b3c0-b83228a34093)

**Comment by lolamtisch** [comment]
Hmm strange. Is it different for this page and the account section? Did you try to logout in malsync and logging in again?
https://malsync.moe/pwa/#/settings

**Comment by CardinalBirb** [comment]
> Hmm strange. Is it different for this page and the account section? Did you try to logout in malsync and logging in again? https://malsync.moe/pwa/#/settings

Things appear in that website but I can't seem to logout. A millisecond "Loading" appears and disappears. I also tried logging out from the extension screen from firefox extension UI thing and same thing happened.

![Screenshot_20240130_073203_Firefox](https://github.com/MALSync/MALSync/assets/86525025/c6261206-b710-4ea8-abef-51d654224dca)

**Comment by lolamtisch** [comment]
Does it change if you switch to mobile data? Do you have the same problem on desktop in the same network?

**Comment by CardinalBirb** [comment]
> Does it change if you switch to mobile data? Do you have the same problem on desktop in the same network?

I can't check on desktop, but this is what appears if I switch to mobile data. Also a small blurb at rhe bottom of the manhwa page appeared saying "Please Authenticate" in red.
![Screenshot_20240130_074800_Firefox](https://github.com/MALSync/MALSync/assets/86525025/a561a150-f087-4ecd-936c-dc34b36ffec7)

**Comment by lolamtisch** [comment]
If you click on the authenticate does it work?

**Comment by CardinalBirb** [comment]
These are my results by being on mobile data. Normal function it seems. I also got the blurb when going on a manhwa chapter after chapter update. Does this mean my IP is actusaly banned and MAL lied to me on the support email?

![Screenshot_20240130_075442_Firefox](https://github.com/MALSync/MALSync/assets/86525025/e09dc7d2-3caf-4882-a5e8-5be629abf4e0)
![Screenshot_20240130_075457_Firefox](https://github.com/MALSync/MALSync/assets/86525025/ebdf3576-a17a-4d17-84d0-0e11570e1309)
![Screenshot_20240130_075559_Firefox](https://github.com/MALSync/MALSync/assets/86525025/0599799c-ff5f-49b9-abfc-25982bf5a415)

**Comment by lolamtisch** [comment]
I have no idea. IP banns are not that uncommon if you have a shity ISP that gives out abused ips or tunnels many people over one ip address. Additionaly it seems that for some countries it is very likely to get banned without reason. But the strange thing is that you can open `https://api.myanimelist.net/` without a problem, because normaly it shows a banned message there. No idea why it does not for you.

IP bans are not account banns, so at least in that point they did not lie.

**Comment by CardinalBirb** [comment]
So is there no solution? Am I simply unable to use the extension? Cuz I won't be using mobile data to just sync things haha. Screenshots showing me back on home Wifi.

![Screenshot_20240130_075559_Firefox](https://github.com/MALSync/MALSync/assets/86525025/1cf1a9a3-f750-4440-851a-c8cbacceccb2)


![Screenshot_20240130_081418_Firefox](https://github.com/MALSync/MALSync/assets/86525025/7780e91c-5233-4938-b6e2-db162a5ab982)

**Comment by henrik9999** [comment]
Maybe write the support that you are blocked on the API and send that 403 error image to them

**Comment by CardinalBirb** [comment]
> Maybe write the mal support that you are blocked on the API and send that 403 error image to them

I will try

**Comment by DeadRisingStar** [comment]
MAL is currently doing maintenance on the API. Wait a day or 2 before checking again.

**Comment by henrik9999** [comment]
> MAL is currently doing maintenance on the API. Wait a day or 2 before checking again.

When they had the problem the API wasnt on maintenance yet

**Comment by CardinalBirb** [comment]
Well I tried lol. Guess I'll wait but otherwise MAL Sync is just unusable forever for me? Idk they seem to think its just a 3rd party issue. The attached image is the API blocked image.

Maybe it will be over after maintenance but this sucks if it is true that it won't get solved.

![Screenshot_20240131_061746_Gmail](https://github.com/MALSync/MALSync/assets/86525025/cb20eefa-f508-4561-9a23-984112e3c5ad)

**Comment by henrik9999** [comment]
i will be closing this as we cant help you with this sorry, if they continue banning you the only options are somehow use another IP with something like a VPN or switch to a different tracking service
