### ISSUE TITLE
Manga chapters are not being updated to MAL

### ISSUE THREAD

**Issue by hemlok89** [MALSync/MALSync#2246]
### Describe the Bug

MALSync is not able to connect to MAL servers to update or fetch information. Unlike #2245 my IP is not banned. But https://api.myanimelist.net/ shows {"message":"","error":"not_found"}.
![image](https://github.com/MALSync/MALSync/assets/39864104/5b607bd7-72cb-4af9-adaa-2bcb86658cc5)
![image](https://github.com/MALSync/MALSync/assets/39864104/38684796-4465-441d-9655-4bb3a70a20a3)
![image](https://github.com/MALSync/MALSync/assets/39864104/40cd4521-347a-4b31-9b46-4e4377be8b6b)

### Steps to reproduce the behavior

Open any supported page and read a chapter.

### Browser

Google Chrome Version 121.0.6167.86 (Official Build) (64-bit)

### Type

Extension

### URL

https://mangasee123.com/manga/Komi-san-Wa-Komyushou-Desu

Here is a console log 
[mangasee123.com-1706754618116.log](https://github.com/MALSync/MALSync/files/14119532/mangasee123.com-1706754618116.log)

**Comment by farahnur42** [comment]
@hemlok89 This is not a MALSync issue, as MAL has temporarily blocked the manga endpoints in the MAL API -
![image](https://github.com/MALSync/MALSync/assets/37258115/88b3f979-2526-4922-a764-68b0cfde1949)
. As such, there is nothing MALSync can do about this.

**Comment by hemlok89** [comment]
Oh thank you for the link. I was wondering why only manga was affected.
