### ISSUE TITLE
MALSync displays wrong MAL info for certain anime seasons on Crunchyroll series pages

### ISSUE THREAD

**Issue by smithcole264** [MALSync/MALSync#2248]
### Describe the Bug

Sometimes MALSync displays the list info for a different MAL entry based on an incorrect link. This causes an issue where the Score/Status/Episode/Your Score values for certain season listings are wrong and the episodes might not reflect the correct highlighted watch status. Two specific examples are Classroom of the Elite Season 3 (MAL id=51180), which shows the anime list info for Classroom of the Elite Season 1 on MAL (id=35507), and Laid-Back Camp Season 2 (id=38474), which shows the anime list info for Laid-Back Camp Season 2 Specials on MAL (id=49026). This issue makes it so that MALSync doesn't properly update the anime list status of some MAL entries from Crunchyroll.

![CotE_S3_CR_view](https://github.com/MALSync/MALSync/assets/55466305/533aaa36-675b-46b2-a98e-277c53a31fca)
![LBC_S2_CR_view](https://github.com/MALSync/MALSync/assets/55466305/b9ee992a-4a8f-4e4c-a5b1-d528c6706408)

### Steps to reproduce the behavior

Either go to the Crunchyroll series page for Classroom of the Elite and select S3: Classroom of the Elite Season 3 or the series page for Laid-Back Camp and select S2: LAID-BACK CAMP SEASON2. 

Then you can inspect "Score:" underneath where it says "MORE DETAILS" on the series page and check the href link to the associated MAL entry page for id=malRating.

### Browser

Google Chrome

### Type

Extension

### URL

www.crunchyroll.com

**Comment by lolamtisch** [comment]
![Wrong recognition (2)](https://github.com/MALSync/MALSync/assets/22085664/cfffaa63-c3c8-41ef-bf23-333dc5eed5d8)
