### ISSUE TITLE
Sync not working for manga while sync for anime works just fine

### ISSUE THREAD

**Issue by Azingus** [MALSync/MALSync#2249]
### Describe the Bug

MALSync always says 'Server Offline' when loading any manga (I tried three different sites, Mangadex among them) despite MAL being accessible from my device. Furthermore, the sync works just fine for anime.

I already cleared my MALSync cache and the DNS cache of my PC. I also logged out of MALSync and renewed the access token for MAL API. Not quite sure what else I could do to resolve this issue, it's pretty annoying. This happened the first time sometime yesterday, back then i just thought it was a hiccup that would disappear after an hour or two. But since it's still there today, I figured there is probably some bigger underlying issue present.

### Steps to reproduce the behavior

Open the page of any manga on MangaDex. Usually it will already show you rating and progession somewhere, but that already doesn't work. Always says 'Server Offline'. Same thing happens when finishing a chapter.

### Browser

Chrome

### Type

Extension

### URL

https://mangadex.org/title/

**Comment by henrik9999** [comment]
https://github.com/MALSync/MALSync/issues/2246#issuecomment-1920411479
