### ISSUE TITLE
Add animekisa to the streaming site links.

### ISSUE THREAD

**Issue by everyonus** [MALSync/MALSync#225]
As title suggest, add animekisa to the streaming site links thingy.

**Comment by henrik9999** [comment]
You mean the one you can see on Myanimelist right

**Comment by everyonus** [comment]
I'm sure it's more or less the same on the 3 tracking sites but I am talking about this: 
![image](https://user-images.githubusercontent.com/22124013/68062791-8c101100-fcc9-11e9-8a08-9d7fb17abf7f.png) 
and the 2nd section in the settings page in Mal-Sync.

**Comment by henrik9999** [comment]
Yeah that's it

**Comment by henrik9999** [comment]
Well I can't it to that because animekisa is not backed by an database I can only add it to the search you can see a bit higher

**Comment by lolamtisch** [comment]
Currently I don't add new pages to the mapping database. Because I can't handle more pages. As it is a lot of work reviewing them all.
