### ISSUE TITLE
Manga tracking not working (Server Offline)

### ISSUE THREAD

**Issue by cardo6r** [MALSync/MALSync#2250]
### Describe the Bug

The tracking functionality and the update function of the extension are not working/loading

![image](https://github.com/MALSync/MALSync/assets/53486754/4e4a5ad3-ea04-4455-9f3e-d7a97f49312f)

### Steps to reproduce the behavior

Loading any website linked to manga tracking, as well as opening the extension of the tracked manga

### Browser

Chrome

### Type

Extension

### URL

https://mangareader.to/jujutsu-kaisen-168

**Comment by lolamtisch** [comment]
https://github.com/MALSync/MALSync/issues/2246#issuecomment-1920411479
