### ISSUE TITLE
List Sync for Manga not working

### ISSUE THREAD

**Issue by Danieruhuli** [MALSync/MALSync#2251]
### Describe the Bug

Until some days ago it was working fine. I have Anilist as Master and MAL as a secondary. the List Sync works for anime but for manga it just gets stuck. I tried from another PC and it happens the same

### Steps to reproduce the behavior

Have an  Anilist account as Master and a MAL one as a secondary.
Go to List Sync, the go to manga. Have pending Sync manga (in my case there are just 2) and click sync.

### Browser

Chrome

### Type

Extension

### URL

my own manga lists I assume

**Comment by farahnur42** [comment]
See: https://github.com/MALSync/MALSync/issues/2246#issuecomment-1920411479

**Comment by Danieruhuli** [comment]
Ok Thanks!
