### ISSUE TITLE
Deletingposts talking about bugs. Fuck you asshole.

### ISSUE THREAD

**Issue by Mendax1989** [MALSync/MALSync#2256]
### Describe the Bug

Fuck you.

### Steps to reproduce the behavior

Fuck you.

### Browser

Fuck you

### Type

Extension

### URL

Fuck you

**Comment by henrik9999** [comment]
Please read the comment that was linked in #2255

**Comment by prism2001** [comment]
@Mendax1989 maybe you should go back to school and learn how to read
