### ISSUE TITLE
Manga syncing on MyAnimeList

### ISSUE THREAD

**Issue by vvirtues** [MALSync/MALSync#2257]
### Describe the Bug

I haven't used the extension in a while (havent seen anything) and recently got back to it. On the dashboard page, it shows the correct data according to my MAL profile, but clicking on specific manga seems to be out of sync/cannot establish connection. See photos:
![image](https://github.com/MALSync/MALSync/assets/81705406/6a7dd04d-6926-4b28-b434-ccfdfcade431)
![image](https://github.com/MALSync/MALSync/assets/81705406/b4c179cb-3663-4829-81cb-5f3d9d8f7d5b)
Clicking add just loads forever, doesnt change any data on my MAL page either. I've tried removing and reinstalling the plugin, changing the tracking (apparently it was using the worse MAL api, switched it back, reinstalled and made sure it was on MAL) but nothing works. Does not affect anime however. Going on a site shows the `Start Reading?` prompt, also does nothing

### Steps to reproduce the behavior

Open extension, Go to manga tab, click on manga
Or go to manga site, open manga, start reading on any chapter

### Browser

Firefox fork (Floorp)

### Type

Extension

### URL

https://comick.cc/comic/kagura-bachi/ml1UK4C3-chapter-15-en

**Comment by henrik9999** [comment]
https://github.com/MALSync/MALSync/issues/2246#issuecomment-1920411479
