### ISSUE TITLE
Does not work well with tmo

### ISSUE THREAD

**Issue by Keiser04** [MALSync/MALSync#2261]
### Describe the Bug

every time i enter tokyo ghoul it doesn't find me anything. for every chapter i get "you want to add the reading" or something like that but it doesn't add. i try to change the status to reading for example and it doesn't sync either. maybe tmo has been changed to visortmo.

### Steps to reproduce the behavior

I am simply trying to read a manga

### Browser

brave, freflox

### Type

Extension

### URL

https://visortmo.com/viewer/5af1ba531c32c/cascade

**Comment by lolamtisch** [comment]
https://github.com/MALSync/MALSync/issues/2246#issuecomment-1920411479
