### ISSUE TITLE
Unable to update a manhwa through MALSync

### ISSUE THREAD

**Issue by Saanto** [MALSync/MALSync#2262]
### Describe the Bug

I'm reading the following manwha as you can see:
![image](https://github.com/MALSync/MALSync/assets/89352220/10500268-5b4e-4fd7-91f1-48dd9d1d5236)

However, unfortunately I cannot update it.
It looks like I haven't even started reading it on this page:
![image](https://github.com/MALSync/MALSync/assets/89352220/a88f15a8-e748-49cd-9848-3dfb91b33588)
and if I try to click the Add button nothing happens. Nothing also happens if I click the start reading pop-up while reading.

What is also weird is if I go fix the link. It doesn't show the info about the manhwa that it's supposed to such as the cover image, title of the manhwa, status or chapters read:
![image](https://github.com/MALSync/MALSync/assets/89352220/f5c8a1de-d417-4b11-ad2c-9d87a608171d)

### Steps to reproduce the behavior

The manhwa in question is SSS-Class Revival Hunter
https://myanimelist.net/manga/146909

I read on comick

### Browser

Chrome Beta

### Type

Extension

### URL

https://malsync.moe/pwa/#/manga/146909

**Comment by lolamtisch** [comment]
https://github.com/MALSync/MALSync/issues/2246#issuecomment-1920411479

**Comment by Keiser04** [comment]
@lolamtisch how i can desable from manga? is anoying if is not working but anyways is popout in the page

**Comment by lolamtisch** [comment]
You can disable websites here
https://malsync.moe/pwa/#/settings/tracking/allSitesUi
