### ISSUE TITLE
comick.cc is not working

### ISSUE THREAD

**Issue by duradara** [MALSync/MALSync#2267]
### Describe the Bug

The userscript is not working on comick.cc (I don't use the extension so I don't know if that's working).
I tried searching about it in the the GitHub to see if it was a known problem but all the problems were about the recent mal manga api error. I assume the api problem is fixed because the userscript works in the every manga sites I use.
  
Sorry if my english is bad

### Steps to reproduce the behavior

Got to any entry and see that the userscript is not working. Ex: https://comick.cc/comic/01-komi-san-wa-komyushou-desu

### Browser

Microsoft Edge Version 121.0.2277.112 (Official build) (64-bit)

### Type

Userscript

### URL

https://comick.cc/comic/01-komi-san-wa-komyushou-desu

**Comment by lolamtisch** [comment]
Yeah comick has a new domain that is not yet part of the userscript. You have 2 options. 
1. Use the extension and accept the new permissions on the settings page.
2. Wait for the next release or build a version yourself until then.

**Comment by duradara** [comment]
Thx
