### ISSUE TITLE
comick domain change

### ISSUE THREAD

**Issue by Uranite** [MALSync/MALSync#2273]
comick.cc will migrate to comick.io at the end of this month
Right now, both domain are still alive, so you should keep support for comick.cc for now.
comick.ink redirects to comick.io, so you can safely remove comick.ink
Actually, I should make a pull request.

**Comment by NoPlagiarism** [comment]
Fixed in #2275

Can you close the issue now?

Also, you should not forget about PR linking that can automatically close issue on PR accepted. [Read about it here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
