### ISSUE TITLE
Issue with the new manhuaplus website

### ISSUE THREAD

**Issue by silou** [MALSync/MALSync#2298]
### Describe the Bug

Hello,

Since Manhuaplus.**com** migrated to the new website manhuaplus.**org**,  I don't see the MalSync on the new page even if I have put  this custom domain : 
![screenshot](https://github.com/MALSync/MALSync/assets/833674/b521d676-ca61-415b-af65-4453fe520d66)

Could you please help me?

### Steps to reproduce the behavior

Mal-Sync  : version 0.9.7

https://manhuaplus.org/manga/martial-peak

### Browser

Firefox  123.0 x64 

### Type

Extension

### URL

https://manhuaplus.org/manga/martial-peak

**Comment by lolamtisch** [comment]
.com is back and works

**Comment by silou** [comment]
Yes i saw it :)
