### ISSUE TITLE
[Website Request] hianime.to

### ISSUE THREAD

**Issue by Venom2729k** [MALSync/MALSync#2314]
### Website name

hianime

### Website link

hianime.to

### Website language(s)

English

### Other details

Rename of aniwatch.to

**Comment by farahnur42** [comment]
Already implemented in https://github.com/MALSync/MALSync/commit/59bf535121227ca7c352243364223f4c78a50e52, wait for the next release or continue using one of the mirrors listed in https://aniwatch.gg/.
