### ISSUE TITLE
SIMKL "Is special" error when syncing

### ISSUE THREAD

**Issue by trivarialthea** [MALSync/MALSync#2321]
### Describe the Bug

You try to sync a list and get a "Is special" error.
<img width="425" alt="image" src="https://github.com/MALSync/MALSync/assets/34968650/9f7104e9-5769-460a-8ae6-551be06d3a12">

- Star Wars Visions does exist, but reports as missing. Record is [here](https://simkl.com/tv/2392829/star-wars-visions)

There are around 12 I currently have that are facing this issue... How can I help with debugging the "Is special" error and/or others? 

### Steps to reproduce the behavior

1. Settings -> List Sync
2. Start sync
3. Get "Is Special" Error

### Browser

Firefox

### Type

Extension

### URL

https://simkl.com/, https://anilist.co/, https://myanimelist.net/

**Comment by henrik9999** [comment]
AFAIK simkl doesn't have specials that's why that error is thrown, the star wars one seems to be a different bug

**Comment by trivarialthea** [comment]
@henrik9999 SIMKL has specials but they are under the "specials" category. 

Here is a screenshot from SLF for example ([SIMKL PAGE](https://simkl.com/anime/1947224/shangri-la-frontier-kusogee-hunter-kamige-ni-idoman-to-su)): 
<img width="960" alt="image" src="https://github.com/MALSync/MALSync/assets/34968650/4cccbe6f-1a63-42c8-abd5-8320e4501335">

**Comment by lolamtisch** [comment]
We have no idea how we should map them

**Comment by trivarialthea** [comment]
@lolamtisch I see, just in case asked the main DEV of SIMKL and apparently they are working on it, but you are already aware of it.
<img width="827" alt="image" src="https://github.com/MALSync/MALSync/assets/34968650/5c818aa4-320b-4952-b129-f60016f0053a">
I guess, my bad then as I was not aware of it until today. 😅

**Comment by beedell-roke** [comment]
@Stale [shouldn't have closed this](https://github.com/actions/stale/issues/1190#issue-2736526981), because these still haven't been mapped.
