### ISSUE TITLE
Isssue with the AnimeXin Website

### ISSUE THREAD

**Issue by silou** [MALSync/MALSync#2334]
### Describe the Bug

Hello,

I have an an issue on AnimeXin , the the extension doesn't seem to remember the between the page of the Anime (which is working fine) and the page with video player (doesn't work fine  / also the anime is not updated).

Could you please help me?

![Animexin_1](https://github.com/MALSync/MALSync/assets/833674/12cd9686-5257-4fd9-b24e-839a321d0491)
![Animexin_2](https://github.com/MALSync/MALSync/assets/833674/606ea398-96b2-4bd4-b77c-9330c2216cb7)

### Steps to reproduce the behavior

Go there https://animexin.vip/martial-master/ (working fine)
Not working : https://animexin.vip/martial-master-episode-419-indonesia-english-sub/

### Browser

Firefox 123.0.1  / Mal-Sync  0.9.7

### Type

Extension

### URL

https://animexin.vip/

**Comment by lolamtisch** [comment]
Page changed apparently and malsync is half broken. It still works but you will have to correct it everytime as it does not detect that they are different animes anymore.

**Comment by silou** [comment]
Thank you :-)
