### ISSUE TITLE
List Sync: hide returning Entries from previous Runs

### ISSUE THREAD

**Issue by rpgstuff-pingo** [MALSync/MALSync#2337]
### Suggestion

List Sync is a great feature, i love it .

I mostly use  MALSync with kitsu  as master source so i have the most anime or anime-like videos on crunchyroll tracked.
Some Errors like "NotFoundError: Not found." are expectable and will shown on every list sync Run.

So my wish were that the returnning errors will not shown in every run so I think feature in one these implentations were nice:

1.  individual click on  on a media to ignore it it in further List Sync Runs
or
2.make a setting in MALSnc-Option to ignore showing know issues from previous runs

In both cases the entries should be added in a foldable category(number of  items) "know issues" or "old issues(number of items)" with folded state so the items will not shown till the unfold it

![image](https://github.com/MALSync/MALSync/assets/132201428/7e0fd8f4-695f-4cc4-8834-375cb61492a6)

**Comment by Jadewalk920** [comment]
i would love it cuz my list is filled with specials and simkl doest accept specials
