### ISSUE TITLE
One piece is not One piece: The movie

### ISSUE THREAD

**Issue by Keiser04** [MALSync/MALSync#2343]
### Suggestion

I don't know if it could be done but since I saw that there are rules like in bug stray dogs where instead of ep 16 season, it's ep 4 of that season, so don't select One piece as One piece: The movie.

**Comment by Keiser04** [comment]
@NoPlagiarism like in any web is autodetecting the op anime like the op: the anime when in the title there not any word refiring to the movie

**Comment by Jimeoin** [comment]
I am definitely having issues with the synchronization of One Piece. It displays on the Crunchyroll page as Episode 1/1 no matter what season I'm on, and when I click on it, it directs me to the first One Piece movie instead of the episodes I'm on.

**Comment by lolamtisch** [comment]
You will have to fix it every season, because one piece is just a mess on crunchy roll. Nothing we can do

**Comment by Jimeoin** [comment]
> You will have to fix it every season, because one piece is just a mess on crunchy roll. Nothing we can do

How would I fix this? I have no problem with doing the offsets, that's complete already, but still when viewing each season it states "Status: Completed,  Episode: 1/1" (As per my picture), which is incorrect. If I can fix this manually I will.

![image](https://github.com/MALSync/MALSync/assets/106084555/cf05076f-30b5-45a4-bec4-dbbadf1e1002)

**Comment by henrik9999** [comment]
![Wrong recognition](https://github.com/MALSync/MALSync/assets/22085664/f0648c2c-7985-44c6-b6b9-55fdd88f8f93)

**Comment by Jimeoin** [comment]
> ![Wrong recognition](https://private-user-images.githubusercontent.com/22085664/333803021-f0648c2c-7985-44c6-b6b9-55fdd88f8f93.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDM5MDAsIm5iZiI6MTcxNjY0MzYwMCwicGF0aCI6Ii8yMjA4NTY2NC8zMzM4MDMwMjEtZjA2NDhjMmMtNzk4NS00NGM2LWI2YjktNTVmZGQ4OGY4ZjkzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDEzMjY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MWFkYTJmOTIwYjhhYmUwNWRmMmExYmRmZjI2OWVjYTQwYmM2NzE5YjA2NDBlNWU5MzVjYWNjN2NlYjM3ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.svnXosf-yzxnP1XE9_34z-cOXodfkNWgxn5cbABg6tk) [ ![Wrong recognition](https://private-user-images.githubusercontent.com/22085664/333803021-f0648c2c-7985-44c6-b6b9-55fdd88f8f93.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDM5MDAsIm5iZiI6MTcxNjY0MzYwMCwicGF0aCI6Ii8yMjA4NTY2NC8zMzM4MDMwMjEtZjA2NDhjMmMtNzk4NS00NGM2LWI2YjktNTVmZGQ4OGY4ZjkzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDEzMjY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MWFkYTJmOTIwYjhhYmUwNWRmMmExYmRmZjI2OWVjYTQwYmM2NzE5YjA2NDBlNWU5MzVjYWNjN2NlYjM3ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.svnXosf-yzxnP1XE9_34z-cOXodfkNWgxn5cbABg6tk) ](https://private-user-images.githubusercontent.com/22085664/333803021-f0648c2c-7985-44c6-b6b9-55fdd88f8f93.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDM5MDAsIm5iZiI6MTcxNjY0MzYwMCwicGF0aCI6Ii8yMjA4NTY2NC8zMzM4MDMwMjEtZjA2NDhjMmMtNzk4NS00NGM2LWI2YjktNTVmZGQ4OGY4ZjkzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDEzMjY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MWFkYTJmOTIwYjhhYmUwNWRmMmExYmRmZjI2OWVjYTQwYmM2NzE5YjA2NDBlNWU5MzVjYWNjN2NlYjM3ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.svnXosf-yzxnP1XE9_34z-cOXodfkNWgxn5cbABg6tk) [ ](https://private-user-images.githubusercontent.com/22085664/333803021-f0648c2c-7985-44c6-b6b9-55fdd88f8f93.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDM5MDAsIm5iZiI6MTcxNjY0MzYwMCwicGF0aCI6Ii8yMjA4NTY2NC8zMzM4MDMwMjEtZjA2NDhjMmMtNzk4NS00NGM2LWI2YjktNTVmZGQ4OGY4ZjkzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDEzMjY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MWFkYTJmOTIwYjhhYmUwNWRmMmExYmRmZjI2OWVjYTQwYmM2NzE5YjA2NDBlNWU5MzVjYWNjN2NlYjM3ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.svnXosf-yzxnP1XE9_34z-cOXodfkNWgxn5cbABg6tk)

Thankyou very much!
