### ISSUE TITLE
[Website Request] <animebuff>

### ISSUE THREAD

**Issue by ZerOIIIIIIIIIIIIIII** [MALSync/MALSync#2347]
### Website name

animebuff

### Website link

https://animebuff.ru/

### Website language(s)

Russian

**Comment by NoPlagiarism** [comment]
~~It will be difficult~~
For now it seems almost impossible to support watch together (`совместный просмотр`)
Website does not provide any information there that could be used for syncing

**Comment by NoPlagiarism** [comment]
[v0.10.0](https://github.com/MALSync/MALSync/releases/tag/0.10.0) is out with basic AnimeBuff support added
