### ISSUE TITLE
Possible to create MALSync Plex Plug-ins?

### ISSUE THREAD

**Issue by Tama47** [MALSync/MALSync#2358]
### Suggestion

This is not for the Plex webapp https://app.plex.tv/. But a plug-in that you can place on the Plex Media Server itself, and be able to sync to MAL from any device with the Plex app client.
![Screenshot 2024-03-31 at 10 34 24](https://github.com/MALSync/MALSync/assets/96937943/51ffdee8-666c-4f65-927e-8469834aedc3)

**Comment by lolamtisch** [comment]
Out of scope really as it would need to a completely separate application with different programming language etc
