### ISSUE TITLE
[Website Request] smotret-anime

### ISSUE THREAD

**Issue by Gigas002** [MALSync/MALSync#2376]
### Website name

smotret-anime

### Website link

https://smotret-anime.com/

### Website language(s)

ru-RU

### Other details

Mirror: https://anime365.ru/
Also has NSFW mirror with completely same UI and abilities, `hentai365.ru`
Not sure about how hard would it be to implement it's support, since it's paywalled..

**Comment by NoPlagiarism** [comment]
[v0.10.0](https://github.com/MALSync/MALSync/releases/tag/0.10.0) is out with Anime365 support implemented

**Comment by Gigas002** [comment]
Thanks, I'll check this out!
