### ISSUE TITLE
Animes Vision dont work anymore

### ISSUE THREAD

**Issue by Bashousen** [MALSync/MALSync#2380]
### Describe the Bug

Animes Vision is no longer tracking anime

### Steps to reproduce the behavior

Open an anime page on animes.vision

### Browser

Brave - Version 1.64.122 Chromium: 123.0.6312.122 (Official Build) (64-bit)

### Type

Extension

### URL

https://animes.vision/

**Comment by Martins-74** [comment]
Animes Vision has been closed for good, owner was arrested and police seized the website and all it's belongings.
This has taken action because of DMCA law.
I think this issue can be closed.

**Comment by Bashousen** [comment]
> Animes Vision has been closed for good, owner was arrested and police seized the website and all it's belongings. This has taken action because of DMCA law. I think this issue can be closed.
