### ISSUE TITLE
Green notification dot and Permission needed mouseover label when no permissions are needed

### ISSUE THREAD

**Issue by JukePlz** [MALSync/MALSync#2435]
### Describe the Bug

The green dot notification persistently reappears in the interface icon when there are no new permissions to accept. Exploring the permissions page makes the notification dot temporarily disappear but it returns consistently shortly afterwards.

This bug started happening with the manifest v3 update, after MALSync v0.10.0

![firefox_2024-05-25_11-21-09](https://github.com/MALSync/MALSync/assets/8497884/108ac84e-5033-48af-bd35-ed3304b596e6)

### Steps to reproduce the behavior

Happens sporadically and doesn't go away unless the user interacts with UI.

### Browser

Firefox v126.0

### Type

Extension

### URL

N/A

**Comment by lolamtisch** [comment]
Nothing we can do. That is how it works for Firefox. https://bugzilla.mozilla.org/show_bug.cgi?id=1851083

**Comment by JukePlz** [comment]
Oh well, I will learn to live with it, hopefully they can figure it out in time. Guess I'm closing this if it's a Firefox bug.
