### ISSUE TITLE
Anilist error "failed to fetch"

### ISSUE THREAD

**Issue by LittleDaoist** [MALSync/MALSync#2451]
### Describe the Bug

I can't use Anilist as the mode all I got are failed to fetch and error. I even revoke app in anilist and authenticate it again but still same result. 

I even reinstalled the extension. It works fine with myanimelist. Recheck doesn't do anything.

![6](https://github.com/MALSync/MALSync/assets/48300166/784f9728-a673-4579-a07b-98c4778a7912)
![5](https://github.com/MALSync/MALSync/assets/48300166/fca7e899-3bde-4fcf-ac76-bc4e0b569ae2)
![1](https://github.com/MALSync/MALSync/assets/48300166/56fe6c77-1997-45e5-aca3-3a2bb823a5a9)
![4](https://github.com/MALSync/MALSync/assets/48300166/b61671bb-17e4-44e0-9743-1a071a168891)

### Steps to reproduce the behavior

- Revoke App in anilist
![7](https://github.com/MALSync/MALSync/assets/48300166/9e52069a-6916-40d8-b6d3-bd38cc820e10)
- Authenticate in malsync
- After getting the token all it shows is
![2](https://github.com/MALSync/MALSync/assets/48300166/546317f5-7281-4ad3-966f-5da7a96e181b)
![6](https://github.com/MALSync/MALSync/assets/48300166/227f43ff-7d74-4a05-ab89-ef16df7760fb)
- If I try to authenticate again
![3](https://github.com/MALSync/MALSync/assets/48300166/b71c859c-4f5a-4c2e-b423-0e6cad96982c)
-Undefined showing at the bottom in anilist
![5](https://github.com/MALSync/MALSync/assets/48300166/946cf0e5-1047-4e2d-8bac-807684509754)
- And stuck in loading in mangadex
![8](https://github.com/MALSync/MALSync/assets/48300166/4fa0e351-c349-4c0a-9c98-4840483a2c40)

 It's working properly if I use MyAnimelist
![0](https://github.com/MALSync/MALSync/assets/48300166/a8232c86-9f91-4f08-9ae2-2e98972f16f1)
![00](https://github.com/MALSync/MALSync/assets/48300166/0fe9b28d-3952-4a4b-9c0e-ae990cc1b727)

### Browser

Google Chrome

### Type

Extension

### URL

https://anilist.co/home

**Comment by Martins-74** [comment]
Same

**Comment by henrik9999** [comment]
> Same

Please join the discord and go to the supprt channek so we can debug the issue
https://discord.com/invite/cTH4yaw

**Comment by LittleDaoist** [comment]
I tried malsync(extension) on firefox and everything works just fine so I think the problems on google chrome.
