### ISSUE TITLE
Released episode counter not updating on general view on PWA.

### ISSUE THREAD

**Issue by eridanired123** [MALSync/MALSync#2463]
### Describe the Bug

When in the general view where all shows are listed, it used to say on the card of every tracked entry when will be the next release or when was the last one, plus a progress bar showing how many you haven't read/watched (manga and anime views affected).

Now this info doesn't appear unless you enter each show, wait a few seconds and then go back to general view. See image below for missing info circled in red:

![Instantánea de el 2024-06-12 a las 15:31:58 hrs](https://github.com/MALSync/MALSync/assets/41547329/c0d23a84-7b5d-4ac3-bfcc-d07cfb49ad39)

### Steps to reproduce the behavior

Access https://malsync.moe/pwa and wait. No show would display released episode info.

### Browser

Firefox 126.0.1 (Ubuntu) and Firefox 124.1.0 (Android)

### Type

Userscript

### URL

https://malsync.moe/pwa

**Comment by licebmi** [comment]
I got the same issue using the userscript on safari with tampermonkey.

In my case, it seems like the "release/<type>/<cacheKey>" keys are getting deleted from the storage after certain time.

**Comment by lolamtisch** [comment]
Release 0.10.3 should fix this now. Please check

**Comment by licebmi** [comment]
can confirm, it works now.
