### ISSUE TITLE
gogoanime <anitaku.pe> on android issue

### ISSUE THREAD

**Issue by martelor** [MALSync/MALSync#2515]
### Describe the Bug

on this website, malsync extension not working as intended on Kiwi browser but working on Lemur browser which use older version of chrome.
working just fine on aniwave on both browser, so it's a website related issue.

### Steps to reproduce the behavior

Kiwi only: in anime page, the element that shows watching status etc at all. even the blueish color for watched episodes does not applied.

also,
can't the element shows up in episode pages too? 
so we don't need to back to anime page just to check which episodes that have been watched.

### Browser

Kiwi

### Type

Extension

### URL

anitaku.pe/*

**Comment by lolamtisch** [comment]
Kiwi is a buggy browser that does not have full extension support. 

Please use Firefox on android. It is the only one that works correctly
