### ISSUE TITLE
https://yugenanime.ro/* links under the quicklinks section need to be removed as the domain has changed

### ISSUE THREAD

**Issue by ericnoble1991** [MALSync/MALSync#2517]
### Describe the Bug

The https://yugenanime.ro/* links under the quicklinks section need to be removed as the domain has changed to https://yugenanime.tv/*

### Steps to reproduce the behavior

Example link can be found on this page: https://myanimelist.net/anime/42481

### Browser

Edge

### Type

Extension

### URL

https://yugenanime.tv/

**Comment by lolamtisch** [comment]
Should be fixed
