### ISSUE TITLE
Mal Sync loads LN info for Himekishi ga Classmate! on FanFox

### ISSUE THREAD

**Issue by Squall-Leonhart** [MALSync/MALSync#2529]
### Describe the Bug

Different behavior between Fanfox and Mangadex, the former loads the light novel info, the latter correctly loads the Manga info

### Steps to reproduce the behavior

Open the below supplied urls and click the extension button, it will load the light novel info incorrectly on Fanfox, but the Manga info on Mangadex

### Browser

Firefox, Edge, Chrome

### Type

Extension

### URL

https://fanfox.net/manga/himekishi_ga_classmate/ , https://mangadex.org/title/3584eeb4-7ce4-4aed-b5e4-5f4a26da55d7/himekishi-ga-classmate

**Comment by henrik9999** [comment]
![Wrong recognition](https://github.com/user-attachments/assets/a27380ea-1ee7-4880-83a9-996997a2b40b)

**Comment by Squall-Leonhart** [comment]
Thanks!
