### ISSUE TITLE
Stealth UI affects the mini-mal button

### ISSUE THREAD

**Issue by Squall-Leonhart** [MALSync/MALSync#2530]
### Describe the Bug

When Stealth UI is turned on, the mini-mal button is made transparent, and the editing pen is hidden making it less obvious in some manga readers on some displays.

### Steps to reproduce the behavior

Toggle on Stealth UI,
Navigate to any manga on Fanfox or MangaDex

The button appears fairly visible (mangadex) or much less visible (Fanfox) but the editing pen is no longer visible with the feature enabled.

based on the description of the stealth feature, this might be an undesired side side effect?

### Browser

Firefox, Edge, Chrome

### Type

Extension

### URL

https://fanfox.net/manga/komi_san_wa_komyushou_desu/v00/c000/1.html

**Comment by lolamtisch** [comment]
It an desired effect. The descriptions are just sometimes not the best
