### ISSUE TITLE
Error with anilist

### ISSUE THREAD

**Issue by Key-explanation** [MALSync/MALSync#2531]
### Describe the Bug

malsync logs me out if i pick my anilist account as my primary account

### Steps to reproduce the behavior

1. set anilist as mode in tracking
2. open any manga or anime page on anilist
3. a pop up shows up says "Please authenticate here"
4. the pop up keeps coming back even after authenticating

### Browser

firefox

### Type

Extension

### URL

https://anilist.co/

**Comment by farahnur42** [comment]
AniList is currently having major infrastructure and related issues, you'll just need to wait it out while they fix things. Nothing we can do about it.

**Comment by henrik9999** [comment]
Anilist has fixed it
