### ISSUE TITLE
kitsu.io -> kitsu.app

### ISSUE THREAD

**Issue by bongcloudmove** [MALSync/MALSync#2548]
### Describe the Bug

kitsu changed to a new domain just recently to

https://kitsu.app

### Steps to reproduce the behavior

https://kitsu.io shows domain on sale

### Browser

firefox

### Type

Extension

### URL

https://kitsu.io

pr: #2547

**Comment by rishabp-alokin** [comment]
any updates on this. the whole SYNC thing is broken because of this

**Comment by henrik9999** [comment]
It will be fixed when we have time
