### ISSUE TITLE
[add support] kurina.co animexin.xyz maidasindex.site

### ISSUE THREAD

**Issue by RohitM-IN** [MALSync/MALSync#255]
* [X]  https://animexin.xyz/ 
* [ ]  https://kurina.co/ 
* [ ]  https://maidasindex.site/

has found very useful when it comes to fan subs and lot faster than other fan subbers so if possible plz add it to mal sync

**Comment by plW0lf** [comment]
For both sites I recommend adding also script that will also automaticaly set english subs, as by default it plays video with other language subs (animexin) or without (kurina)

**Comment by henrik9999** [comment]
> For both sites I recommend adding also script that will also automaticaly set english subs, as by default it plays video with other language subs (animexin) or without (kurina)

i wrote an quick dirty userscript to select the english language on animexin
https://greasyfork.org/de/scripts/394670-animexin-xyz-english-language-selector

**Comment by RootAndroid58** [comment]
> > For both sites I recommend adding also script that will also automaticaly set english subs, as by default it plays video with other language subs (animexin) or without (kurina)
> 
> i wrote an quick dirty userscript to select the english language on animexin
> https://greasyfork.org/en/scripts/394670-animexin-xyz-english-language-selector

thanks man

**Comment by henrik9999** [comment]
animexin got added in the latest version
i dont plan to add the other requested pages (kurina, maidasindex) for now

**Comment by henrik9999** [comment]
closing this as kurina and maidasindex seem to be dead
