### ISSUE TITLE
Force/Set default Streaming quality

### ISSUE THREAD

**Issue by KAGEYAM4** [MALSync/MALSync#2556]
### Suggestion

Sometimes watching anime, the video starts playing with 720p. Would it be possible for MalSync to change the quality to 1080p? Maybe it can check for quality at start and offer to change it or notify the user about quality being different from the preference or even change it to desired preference.

**Comment by lolamtisch** [comment]
Would be a lot of work as it needs separate implementations for hundreds of player.
