### ISSUE TITLE
[Website Request] aniwatch

### ISSUE THREAD

**Issue by Zartris** [MALSync/MALSync#2572]
### Website name

aniwatch

### Website link

https://aniwatchtv.to/

### Website language(s)

English

### Other details

It is almost identical with h!anime when playing, it is only the "home" page that has a better layout. So everything can almost be reused from h!anime

**Comment by SirFancyEXE** [comment]
+1

**Comment by henrik9999** [comment]
Fake site so wont be added

**Comment by wambo121** [comment]
What do you mean with fake site? @henrik9999
