### ISSUE TITLE
show scores from multiple sources

### ISSUE THREAD

**Issue by KAGEYAM4** [MALSync/MALSync#2573]
### Suggestion

Currently i use Anilst for tracking but because of that i see scores from Anilist only. It would be awesome if we could add statistics such as scrores from multiple sources. 

I like open-source and ui/ux of Anilist but myanimelist scores makes more sense to me. So that why i wanted to be able to see myanimelist score even if i am using Anilist for tracking.

**Comment by henrik9999** [comment]
Duplicate of #2188

**Comment by KAGEYAM4** [comment]
Thanks, sorry i searched for duplicated using the query `score` that's why i didn't find one.
