### ISSUE TITLE
[Website Request] <9anime>

### ISSUE THREAD

**Issue by Tim-Plaimer** [MALSync/MALSync#2579]
### Website name

9anime

### Website link

https://9anime.pe/

### Website language(s)

Japanese, English

### Other details

Has different designs on different domains

**Comment by lolamtisch** [comment]
Fake websites are not supported. 9anime/Aniwave is no more

**Comment by Tim-Plaimer** [comment]
> Fake websites are not supported. 9anime/Aniwave is no more

Thank you for your quick response. By fake websites, do you mean illegal websites?
