### ISSUE TITLE
Add anime-sites play button to chiaki.site

### ISSUE THREAD

**Issue by KAGEYAM4** [MALSync/MALSync#2580]
### Suggestion

for examlple - https://chiaki.site/?/tools/watch_order/id/35262

i have to go to this site, check the order then select the anilist button, then on anilist page select animepahe to start streaming.

If not possible, are there any alternative workflow that you know of?

**Comment by lolamtisch** [comment]
There is none. But you could add a quicklink on malsync then you dont have to search on chaiki and can directly open it from anilist. 


https://malsync.moe/pwa/#/settings/streaming
`https://chiaki.site/?/tools/watch_order/id/{cacheId}`
![image](https://github.com/user-attachments/assets/aa856a16-c209-49c0-93f2-5b958a24114f)
![image](https://github.com/user-attachments/assets/346f69b2-f940-404a-85b9-85865071b957)
