### ISSUE TITLE
Site Favicon and New episode pill not showing 

### ISSUE THREAD

**Issue by resuta566** [MALSync/MALSync#2581]
### Describe the Bug

New Episode and site favicon are working but on FF it works sometimes?
![image](https://github.com/user-attachments/assets/0d7ae92b-a5ab-4d69-b156-4aab78abffd2)

FF network tab
![image](https://github.com/user-attachments/assets/0de7c620-c698-4065-ad83-8118fafd2dbc)

FF Console
![image](https://github.com/user-attachments/assets/41ec4ffb-61c5-42fc-9430-03ae7bce7a5b)

### Steps to reproduce the behavior

I don't know how to reproduce this behavior from FF because seems to be a server-side certificate issue at least based on when I searched for the error text, at least for the favicon.

### Browser

Firefox 129

### Type

Extension

### URL

https://malsync.moe/pwa/#/anime/52635

**Comment by lolamtisch** [comment]
I can not reproduce it. So no idea. But we had a small number of similar reports since a few weeks, but over all browsers. Our certificates are completely handled by our CDN. So very unlikely that is the problem. Strange that it is only a problem in your Firefox. Could be that your DNS is doing something strange or something strange is happening in your certificate storage, which can be changed by antivirus or ISPs I think, but 0 idea. Or something is corrupt in your Firefox but no idea.

**Comment by resuta566** [comment]
My router has Google DNS (can't change the ISP wouldn't give me the admin credentials). I have Cloudflare DNS on my computer. Didn't use VPN, only using Windows Defender. 

I used my company VPN (AWS OpenVPN) looks like the favicon issue is fixed with it but not the new episode pill. 

Looks like the progress process didn't work on FF

![image](https://github.com/user-attachments/assets/2314b9c8-9e11-411b-ba0c-c590cfb97746)

![image](https://github.com/user-attachments/assets/b24f0aab-9c4a-4bf3-82e6-59a1807110f7)

**Comment by resuta566** [comment]
Tried checking Disable Cache in the Network tab - It works?
Restart FF unchecked - Still works???

shift reload - now it won't work in the anime page
![image](https://github.com/user-attachments/assets/abd68beb-74b3-4763-a552-8e6493427284)

![image](https://github.com/user-attachments/assets/5ec00990-0433-416e-b4ad-1c0b373f80d4)

yeah no Idea what causes this. I disabled the dns in my computer still nothing.

**Comment by lolamtisch** [comment]
Yeah no idea either

**Comment by resuta566** [comment]
It's Cloudflare protection checking 

https://api.malsync.moe/nc/mal/anime/57380/pr

I manually input this endpoint in a new tab and the new episode pill works.

**Comment by lolamtisch** [comment]
Hmm. Then it is probably some strange edge case, where it thinks you are the worst pc on the planet. The protection is already set as low as cloudflare allows.

**Comment by resuta566** [comment]
Does it check the cores? I have R5 3600 set to only 4 cores and a weird 16060 5GB China GPU but have 32gb ram. or is it my connection? i only have 35Mbps

**Comment by lolamtisch** [comment]
Cors should be disabled on the complete domain.

It has to be your connection. Is your Firefox up to date? That is pretty much the only information that gets sent of your setup. Everything else is location and past requests, that get checked from cloudflare I imagine.

So things you don't really have influence over.

**Comment by resuta566** [comment]
Tried to check the API today, seems that FF is just too strict...

![image](https://github.com/user-attachments/assets/ffcf3ec0-20f2-42f7-9557-6280d992acc9)

**Comment by lolamtisch** [comment]
Did you try using firefox with/without DNS-over-HTTPS?

**Comment by resuta566** [comment]
Yup, I turn off all of FF "strict" protocols

**Comment by lolamtisch** [comment]
If it works with a VPN, isn't it then like an ISP problem? Could be that they have some bad routing. But again that would mean that most  pages with cloudflare should have problems. As they should hit the same edge server. 
But with DNS over HTTPS on Firefox it still does not work? As that is I think a way to get around ISP messing with DNS responses.

**Comment by resuta566** [comment]
Sorry for the very late reply. Everything works since a month ago. Cloudflare seems to be blocking my IP because I shared it with other users because my ISP is also just using a major ISP connection. But since I've solve the clouldflare captcha everytime it doesn't work, it seems to whitelist my IP. Well now I'm on a different ISP and it still works fine.
