### ISSUE TITLE
[Website Request] add 9animetv.to

### ISSUE THREAD

**Issue by H644b** [MALSync/MALSync#2583]
### Website name

9Anime

### Website link

https://9animetv.to

### Website language(s)

UI is English but there is a switch for JP on the bottom only for the names of the Anime.

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by lolamtisch** [comment]
Fake website

**Comment by H644b** [comment]
oh
