### ISSUE TITLE
[Website Request] animixplay.name

### ISSUE THREAD

**Issue by Daniverzum** [MALSync/MALSync#2585]
### Website name

animixplay.name

### Website link

https://animixplay.name/

### Website language(s)

English

**Comment by henrik9999** [comment]
fake site

**Comment by Daniverzum** [comment]
then add a template of the original so I can add it as a custom domain?

**Comment by Daniverzum** [comment]
> fake site

Then add a template of the original so I can add it as a custom domain?

**Comment by lolamtisch** [comment]
As their main goal is to deceive people, we will never add fake websites.

**Comment by Daniverzum** [comment]
> As their main goal is to deceive people, we will never add fake websites.

this does not answer my question. I acknowledged that it is a copy website and can not be added, however, the original site existed and that should have a template that could be selected when adding a custom domain, if I could just select that template now and use it on the copy's domain that would be great for me while it wouldn't promote that specific site overall

and even if it is a "fake successor" of animixplay, it has been acknowledged both on fmhy and everythingmoe, of course, that doesn't necessarily mean much but it is neither a random throw-away scam site

**Comment by lolamtisch** [comment]
What would be the point to add a website that do not get new content or fixes content? It is a waste of work.

**Comment by Daniverzum** [comment]
to which are you referring to? because animixplay.name gets new content. but to begin with, the original site was already added at some point, so I assume putting it back at least as a template wouldn't be too much work, especially since it isn't even being updated so no need to fix anything later either, but I guess we'll just go with "we can't be bothered to please everyone"

and well "what would be the point?" I think I already explained that, so I could use it, but I guess I'll just have to forego malsync for the time being and go back to manual mal updates, compared to animixplay all other sites are as user-friendly as a website from the early 2000s

**Comment by lolamtisch** [comment]
It says that it is only an archived version. So there will be no new content, right?

**Comment by Daniverzum** [comment]
this issue is for animixplay.name which gets new content, legacy.animixplay.to is indeed an archived version which is like frozen in time in regard to episodes feed, but the series pages come from MAL and those do get updates and they can also redirect to the original streams, so it's a bit of a yes and no
