### ISSUE TITLE
[Website Request] AniMixPlay

### ISSUE THREAD

**Issue by Daniverzum** [MALSync/MALSync#2587]
### Website name

AniMixPlay

### Website link

https://legacy.animixplay.to/

### Website language(s)

English

### Other details

alternatively, I would like it if it was at least added as a template for custom domains so I can add copy sites that use the same URL scheme
animixplay.name is on everythingmoe.com, and to this day this is the most usable site by far. Also, as far as I can tell, it's been up for at least a year, idk exactly since when, so it'll stay probably and even if it won't there are and will be more copies for which a template could be useful

**Comment by lolamtisch** [comment]
Fake website

**Comment by Daniverzum** [comment]
legacy.animixplay.to is not fake website, it's literally the original domain, and adding the original's template back wouldn't support the copy websites either. but if that can't be arranged I'd like to know how I could set it up for myself at least
