### ISSUE TITLE
Aniwave and Anix can be removed from the list of supported sites

### ISSUE THREAD

**Issue by kvhjdffv** [MALSync/MALSync#2590]
The websites just show a message. They can be removed.
![2024-09-07 11_26_44-Charlie Puth - One Call Away](https://github.com/user-attachments/assets/183772df-7ca0-4704-8d6c-059b48685b33)
![2024-09-07 11_28_35-Charlie Puth - One Call Away](https://github.com/user-attachments/assets/61f7103c-edd2-44e4-8ae4-98375de47668)

**Comment by henrik9999** [comment]
Duplicate of #2568
