### ISSUE TITLE
Seek Forward/Back by custom amount

### ISSUE THREAD

**Issue by InsaneDoggo** [MALSync/MALSync#2592]
### Suggestion

Would be nice to have feature similar to "Skip Opening" to let user seek forward/backward by customizable amount of time. 

**Use case:** I'm subtitles enjoyer so I often have to seek back and forth to read text lines. It's not convenient with seek amount of 5 sec (default for most players).

P.S. also would be nice to temporary set minimal "skip length" to 1 sec instead of 8, so I can utilize existing "skip op" feature as a replacement while described one isn't implemented.

![image](https://github.com/user-attachments/assets/83430562-37db-4f1b-af48-831ea6911df0)

**Comment by InsaneDoggo** [comment]
**Note:** personally I'm interested in chrome extension

**Comment by lolamtisch** [comment]
Default min 5 not 8 but lowered it to 1 now.
