### ISSUE TITLE
MALSync UI Disappear

### ISSUE THREAD

**Issue by Tama47** [MALSync/MALSync#2603]
### Describe the Bug

https://github.com/user-attachments/assets/4024c5c8-d207-414c-814c-4e758ac34ec6

### Steps to reproduce the behavior

Leaving a tab open for an extended period and then attempting to play an episode without reloading the tab causes the MALSync UI to disappear, and the episode won't be tracked. You have to reload the page to bring the UI back, and the episode is tracked normally.

### Browser

Chrome

### Type

Extension

### URL

https://www.crunchyroll.com/watch/GX9UQEG3V/brother-and-sister

**Comment by ericnoble1991** [comment]
I have also seen this happen. Using Microsoft Edge. 

Just some thoughts:

Is it not due to the tab being put into "sleep mode" in order to save system resources for other tasks?

Maybe try adding Crunchyroll to the never put to sleep list in your browser settings and see if it still happens?

**Comment by lolamtisch** [comment]
Does it happen on other pages other than crunchyroll too? Could you check the console (f12 and then console tab), if there is something apparent that could trigger this?

**Comment by Tama47** [comment]
@ericnoble1991 Adding Crunchyroll to the "Always keep these sites active" list seems to fix it for me. Thanks for the suggestion!

@lolamtisch Seems like a browser-settings related issue like ericnoble suggested, rather than extension bug, closing as resolved. Thank you for taking a look!
