### ISSUE TITLE
Version 0.10.4 was not published on firefox addons page

### ISSUE THREAD

**Issue by LokiMidgard** [MALSync/MALSync#2621]
### Describe the Bug

The current version on Firefox is 0.10.3 instead of 0.10.4. 
In the chrome web store it was updated on August 22, 2024.
while the Firefox extension was last updated on Jul 25, 2024.

I haven't seen any mention that the publishing for Firefox take longer or is currently blocked. Nor have I found an issue. If I missed something Sorry to have bothered you. 

PS:
This project seems to be quite useful. Thanks :)

### Steps to reproduce the behavior

N.A.

### Browser

Firefox

### Type

Extension

### URL

N.A.

**Comment by lolamtisch** [comment]
0.10.4 was unlisted by mozilla. They were not able to find the build documentation for some reason and retroactive removed the version from the store. I answered with the documentation 3 days ago, but did not get an response yet.

**Comment by lolamtisch** [comment]
Firefox finally answered and the version is back online.
