### ISSUE TITLE
Cannot stay authenticated

### ISSUE THREAD

**Issue by Phase1234** [MALSync/MALSync#2627]
### Describe the Bug

![image](https://github.com/user-attachments/assets/3e6796ab-3ec9-4043-b730-99378d6ed209)

Anytime I authenticate I get this after I click my name to try and sync. I paused all blockers on MAL but no luck.

### Steps to reproduce the behavior

Click on extension > Hit Gear for settings > tracking Click name or Recheck / Authenticate > Go through token process > Repeat 

### Browser

Chrome

### Type

Extension

### URL

n/a

**Comment by lolamtisch** [comment]
Could you clear the cache and try again? 
https://malsync.moe/pwa/#/settings/miscellaneous/clearCache

**Comment by Phase1234** [comment]
Cleared via link and browser. I got a 404 on my first attempt after hitting allow on MAL and then it went through the second try. However it still reverts back right after

**Comment by henrik9999** [comment]
Do you have the malsync userscript and extension both installed? If yes remove the userscript

**Comment by Phase1234** [comment]
Is that an extension as well? If so, no.

**Comment by lolamtisch** [comment]
Ah you log out by clicking your name. Just do not klick on your name
