### ISSUE TITLE
authenticated keep Loading 

### ISSUE THREAD

**Issue by Katehuuh** [MALSync/MALSync#2632]
### Describe the Bug

On userscript I have notice "Loading", e.g.`voiranime`:
![image](https://github.com/user-attachments/assets/50170326-e30d-4131-a105-e4c54d3ef226)

### Steps to reproduce the behavior

When look at https://malsync.moe/pwa/#/settings:
![image](https://github.com/user-attachments/assets/824b56f2-3a7b-45e2-9c15-f60d51ca8a4a)
I have the same behavior, no error found in `console`.

I could't logout/login to oauth again, I tried
- Acces directly https://malsync.moe/mal/oauth
- Clear cache https://malsync.moe/pwa/#/settings/miscellaneous/clearCache (include browser cookie)
- Reinstall MALSync userscript and `Factory reset` (include *alway* ressource page)
<img width="241" alt="image" src="https://github.com/user-attachments/assets/eb977c85-df8e-41b6-91f1-426691218f06">

- Changed myanimelist password to attempt to invalidate existing OAuth tokens..

However *Chome extensions* work fine, and i did have this issue before.

### Browser

Chome

### Type

Userscript

### URL

https://malsync.moe/mal/oauth

**Comment by lolamtisch** [comment]
And you are sure it was not just mal that was slow at that moment?

**Comment by Katehuuh** [comment]
> And you are sure it was not just mal that was slow at that moment?

The page had min to load, so not about _slow_.

**Comment by Katehuuh** [comment]
@lolamtisch Can we have a timer logout in the userscript if loading takes too long? Unsure if it will fix soon, so in the meantime, I'll use Chrome extensions.
