### ISSUE TITLE
Flamescans integration broken

### ISSUE THREAD

**Issue by vivek201** [MALSync/MALSync#2634]
### Describe the Bug

Currently sync on Flamescans is not working. The site url has changed from "flamescans.com" to "flamescans.me", so I'm suspecting that might be the issue.

### Steps to reproduce the behavior

- Go to Flamecomics.com
- Click on any chapter
- Sync does not happen

### Browser

Zen Browser (1.0.1-a.7) - Tested using Firefox 131.0 as well

### Type

Extension

### URL

https://flamecomics.me/series/solo-leveling/

**Comment by lolamtisch** [comment]
Add missing permissions on the settings page and it should work again.
