### ISSUE TITLE
Add option to remove an anime

### ISSUE THREAD

**Issue by ghost** [MALSync/MALSync#2644]
### Suggestion

![2024-10-17 12_12_18-Window](https://github.com/user-attachments/assets/04b439c7-88ce-4bea-90a0-06095faf0200)
Currently there's no option to remove an anime from MyAnimeList. The most I can do is to drop an anime. So I have to manually remove it via going to the website. Can you please add the option?

**Comment by henrik9999** [comment]
Inside the anime on the extension is a delete button

**Comment by farahnur42** [comment]
And since Orell didn't provide a screenshot, here's an example of what it looks like.
![image](https://github.com/user-attachments/assets/77061d63-bbd7-4963-8586-88ea5d13cf66)
