### ISSUE TITLE
Anime and manga name in English

### ISSUE THREAD

**Issue by kvhjdffv** [MALSync/MALSync#2649]
### Suggestion

Hello, please add the option to have anime and manga titles in English. I have tried to find a option of similar nature. I even turned on an option called "Force English" under the "Miscellaneous" tab, though that fixed nothing.
![2024-10-20 17_44_26-MAL-Sync](https://github.com/user-attachments/assets/9252f5b9-9e28-4cea-8dc7-c9c863a4d423)

**Comment by lolamtisch** [comment]
Not possible in Mal only in anilist.

**Comment by kvhjdffv** [comment]
Oh, alright :(
