### ISSUE TITLE
MalSync doesn't work anymore on AnimeXin

### ISSUE THREAD

**Issue by silou** [MALSync/MALSync#2674]
### Describe the Bug

Hello, 

 The plugin doesn't appear on AnimeXin.

Could you please help me?

### Steps to reproduce the behavior

Open the URL  : https://animexin.top/throne-of-seal/

### Browser

Firefox version 132.0.1 - MalSync version : 0.10.4

### Type

Extension

### URL

https://animexin.top/

**Comment by lolamtisch** [comment]
![image](https://github.com/user-attachments/assets/9f66cce6-1404-47ff-bccd-6e962609a6d0)
https://malsync.moe/pwa/#/settings/customDomains

**Comment by silou** [comment]
It reworks  again :-)
Thank you
