### ISSUE TITLE
chapters with decimals in the number are not recognized

### ISSUE THREAD

**Issue by fuzetsu** [MALSync/MALSync#269]
**Describe the bug**

When visiting a manga chapter that includes a decimal place in the number, it is not recorded by MALSync. This may be specific to manganelo, I've only tested there. 

**Steps to reproduce the behavior:**
1. visit this page https://manganelo.com/chapter/god_of_martial_arts/chapter_100.2
2. notice that chapter is not recorded

**Additional information:**
 - Browser: Firefox
 - Type: Extension
 - Other Urls:
   * https://manganelo.com/chapter/read_one_punch_man_manga_online_free3/chapter_122.5
   * https://manganelo.com/chapter/read_one_punch_man_manga_online_free3/chapter_99.3

**Comment by lolamtisch** [comment]
Decimals are rounded down, because MAL/Anilist etc only can save Full numbers. Nothing i can do there.

**Comment by fuzetsu** [comment]
Aha, I suspected that might be the case based on the behavior, what threw me off that theory is that it doesn't even show the current chapter bar along the bottom. 
Although I did see the rounded number in the console. 

Hard to deal with this without some sort of local DB I suppose, or changing the approach with which chapters calculated.

Like basing the chapter number on the current index / absolute number of chapters in the selection list rather than parsing it out. I can imagine though that this approach might cause more issues overall though when a crappy manga site includes random noise chapters in between or something. Also I imagine there's a good amount of shared code in this area between manga/anime, and this would kind of be unique to manga.

Fortunately it's not a huge inconvenience since it catches back up on the next whole number chapter, so I can live with it :laughing:

**Comment by fuzetsu** [comment]
Also I guess a question would be how does MAL see this. Do they just consider fractional chapters to not count towards the total. Or if a series relies heavily on them does it just count each one as a whole chapter? I've seen some manga that will do 1.1, 1.2, 1.4 etc.. :thinking:

**Comment by lolamtisch** [comment]
Are they really new chapters? On kissmanga they are normally only fixed of the translations etc I think. Mal does not accept them like that. I have to round them on my side.

The update bar only shows if the ep/Ch is higher as the one on Mal.

**Comment by fuzetsu** [comment]
Ah, makes sense for the bar :+1: 

But yeah they really are new chapters, I've mainly seen it on web comics though, not as much on normal manga since they're actually published in books, and are more bound by conventional numbering rules :laughing:

**Comment by RootAndroid58** [comment]
@lolamtisch  cant you make it save in local if the manga chapter includes decimal only those who are in decimal will be saved in local and deleted when a whole number appears which can be saved in mal 
Just an idea 👍
