### ISSUE TITLE
Firefox custom domain permission repetition

### ISSUE THREAD

**Issue by Srini-B** [MALSync/MALSync#2720]
### Describe the Bug

Though the browser permission has been given first time, app keeps on showing the section to accept new domains

### Steps to reproduce the behavior

Just open the extension, on version 0.10.4

https://github.com/user-attachments/assets/e455c8ea-3079-4930-9999-93025d849eb0

### Browser

Firefox 133 m1 mac

### Type

Extension

### URL

any url

**Comment by lolamtisch** [comment]
It very likely means that you did not accept the permissions. Did the browser ever prompt you to accept additional permissions for malsync? Looks something like bellow. Firefox unfortunatly is very buggy with that permission popup. As it is often bellow the popup or on another window/display. We have no controll over that window as it is a security feature.

You could try doing it on the full version of the popup. 

1. Open `https://malsync.moe/pwa/#/settings/customDomains` in a tab
2. There should be a red error box at the bottom, click on it. It should open the page on a `moz-extension://` page. 
3. Try adding the permissions again.

![image](https://github.com/user-attachments/assets/ff29940a-3e6d-4689-b6dd-d13c2d4db09a)

**Comment by Srini-B** [comment]
Thanks, this solved it, weirdly I got only the 1st permission popup for the extension to work before (one with 600+ domains)
