### ISSUE TITLE
My Anime List supports dub names now

### ISSUE THREAD

**Issue by IrishBruse** [MALSync/MALSync#2731]
### Suggestion

https://api.myanimelist.net/v2/users/@me/animelist?nsfw=true&limit=24&offset=0&status=watching&sort=list_updated_at&fields=list_status{tags,is_rewatching,is_rereading,start_date,finish_date},num_episodes,num_chapters,num_volumes,alternative_titles

alternative_titles field contains the english

```
        "node": {
                "id": 52995,
                "title": "Arifureta Shokugyou de Sekai Saikyou Season 3",
                "main_picture": {
                    "medium": "https://cdn.myanimelist.net/images/anime/1553/145597.jpg",
                    "large": "https://cdn.myanimelist.net/images/anime/1553/145597l.jpg"
                },
                "num_episodes": 16,
                "alternative_titles": {
                    "synonyms": [
                        "From Common Job Class to the Strongest in the World Season 3"
                    ],
                    "en": "Arifureta: From Commonplace to World's Strongest Season 3",
                    "ja": "ありふれた職業で世界最強 season 3"
                }
            },
```

**Comment by DFreezerR** [comment]
But isn't it already handled?
https://github.com/MALSync/MALSync/blob/0de6b95bafaa65f9ffdb002495cf8801a4993888/src/_provider/MyAnimeList_api/metaOverview.ts#L141-L150

![image](https://github.com/user-attachments/assets/b134e8ae-41e8-45a1-9863-0b25e0e5b420)

**Comment by IrishBruse** [comment]
Oh is there a way to set it to use the enlish in the list view then it only works for me with anilist not mal

**Comment by henrik9999** [comment]
For anilist we use the account title setting, mal also has this setting but they dont reveal it in the API so we did not bother implementing english titles

**Comment by IrishBruse** [comment]
Made a PR there would love some feedback new to this repo
