### ISSUE TITLE
Change domain name from v5.voiranime.com to v6.voiranime.com

### ISSUE THREAD

**Issue by Zerkios2** [MALSync/MALSync#2745]
### Describe the Bug

The site v5.voiranime.com has changed the first part of the domain in v6.voiranime.com. Now the plugin is not working.

### Steps to reproduce the behavior

Open v5.voiranime.com and get redirect to v6.voiranime.com

### Browser

Chrome

### Type

Extension

### URL

https://v6.voiranime.com/

**Comment by NoPlagiarism** [comment]
Will be fixed in #2744
