### ISSUE TITLE
tracker not working in kissassanime

### ISSUE THREAD

**Issue by Key-explanation** [MALSync/MALSync#2753]
### Describe the Bug

As the title says, the tracker does not track the episode

### Steps to reproduce the behavior

1. open any episode in kissassanime
2. the tracker would be loading

### Browser

firefox

### Type

Extension

### URL

https://www1.kickassanime.mx/

**Comment by henrik9999** [comment]
Please add the new permissions on the settings page on malsync and it should work again.

https://malsync.moe/pwa/#/settings/customDomains
