### ISSUE TITLE
images for locally saved manga

### ISSUE THREAD

**Issue by Nicebull** [MALSync/MALSync#339]
I read a lot of manga thats not avaliable on mal so i am loving the save to local storage feature. I can see how this would be hard to implement since every site does it differently but would it be possible to display the picture the site is using instead of the grey ? when viewing them in your list?

**Comment by lolamtisch** [comment]
It isnt that easy, because on a chapter page the covers are seldom shown. I would need to cache it when one is on the overview page or do calls in the background. On top of that it would need to be implemented for every page too. 
I will add it to my todos but I will not implement it too soon.
