### ISSUE TITLE
Add anizm.tv

### ISSUE THREAD

**Issue by Treajen** [MALSync/MALSync#34]
Hi, im big fan of your extension but turkanime is really bad place to watch anime.
Can you add anizm.tv ?
Thanks

**Comment by lolamtisch** [comment]
I have to think about it. Atleast not in near future.

**Comment by henrik9999** [comment]
they put ovas and other stuff in the same anime so i wont be doing it

**Comment by DogancanYr** [comment]
Can you review the site again?
