### ISSUE TITLE
Some kind of animefillerlist integration

### ISSUE THREAD

**Issue by ghost** [MALSync/MALSync#370]
I know this would be a whole new feature, but it would be handy to see if an episode is a filler, or maybe skip a bulk of fillers. Information about episodes: animefillerlist.com/shows

**Comment by lolamtisch** [comment]
Already on my todos. But not in the near future, as no mapping to mal and no api.

**Comment by DiegoFleitas** [comment]
I came to request the same feature, I think this is an excellent idea!
I think this code could bring some inspiration too https://github.com/chanlis/anime-filler-extension/blob/master/content.js

**Comment by henrik9999** [comment]
> I came to request the same feature, I think this is an excellent idea!
> I think this code could bring some inspiration too https://github.com/chanlis/anime-filler-extension/blob/master/content.js

We already know of this extension but it only does bad matching with titles and this wouldn't work good in our case

**Comment by DiegoFleitas** [comment]
> 
> 
> > I came to request the same feature, I think this is an excellent idea!
> > I think this code could bring some inspiration too https://github.com/chanlis/anime-filler-extension/blob/master/content.js
> 
> We already know of this extension but it only does bad matching with titles and this wouldn't work good in our case, also animefillerlist doesn't have seasons

I see, then the solution could rely on using Jikan API maybe?
The episode listing endpoint seems to have a boolean to flag filler episodes
ex for one-piece: https://api.jikan.moe/v3/anime/21/episodes

**Comment by henrik9999** [comment]
animefillerlist isnt possible but we added filler check from the MyAnimeList episodes page in the last release
