### ISSUE TITLE
Episode tracking not working on StreamTape

### ISSUE THREAD

**Issue by SheepKid12** [MALSync/MALSync#383]
**Describe the bug**
Episode length is not properly tracked while using StreamTape.

**Steps to reproduce the behavior:**
It's as simple as: start an episode and watch as the bottom thing doesn't update when the video starts.

**Additional information:**
 - Browser: Firefox (version 76.0.1)
 - Type: Extension (version 0.7.5)
 - Url: https://9anime.ru/watch/weathering-with-you.9xqn

Note: this was tested in a clean Firefox profile to rule out any possibility of the extension being weird.

**Comment by lolamtisch** [comment]
StreamTape is new and is still not added. Will be fixed with the next update, probably someday next week.

**Comment by SheepKid12** [comment]
I guess I'm closing this now, as this issue has been fixed.
