### ISSUE TITLE
Add suport to Animeflv.ru, Animeflv.la & monoschinos.com

### ISSUE THREAD

**Issue by RedTestament** [MALSync/MALSync#384]
Its possible to add in the script the following websites, they offer an entire catalog of old series that Animeflv.net is not including on his site:

https://animeflv.ru
https://animeflv.la
https://monoschinos.com/

Thanks in advance!

**Comment by Karmesinrot** [comment]
monoschinos.com is already supported in the latest version.

**Comment by RedTestament** [comment]
Thank for the support!

**Comment by henrik9999** [comment]
Animeflv.ru, Animeflv.la seem like fakes so they wont be added
