### ISSUE TITLE
Nekomori

### ISSUE THREAD

**Issue by lolamtisch** [MALSync/MALSync#404]
https://api.nekomori.ch/ - main endpoint
https://cdn.nekomori.ch/ - cdn endpoint

https://api.nekomori.ch/art/1 - anime get method
https://api.nekomori.ch/art/-20 anime get by malId method
https://api.nekomori.ch/art/-20,2 can get multiple anime entry
https://api.nekomori.ch/user/19281/list
https://api.nekomori.ch/art?search=testing 

```
UserList =
    | none = 0
    | watching = 1 //Watching
    | watched = 2 //Watched
    | next = 3 //sertanlly will
    | maybe = 4 //Maybe watch
    | ban = 5 //Not interested
    | bin = 6 //Paused
    | drop = 7//Dropped
```
 to change list
```
POST https://api.nekomori.ch/list
{
    "artId": 1,
    "list": 1
}
```
 to change episodes watched
```
{
    "artId": 1,
    "ep": 10
}

```

Use token from the website to access api.

**Comment by N0D4N** [comment]
Seems like website no longer works as URL leads to, most likely joking, webpage that mentions that website has been seized as law enforcement operation.

**Comment by lolamtisch** [comment]
Seems like it
