### ISSUE TITLE
Add support for webtoons.com

### ISSUE THREAD

**Issue by Krytos** [MALSync/MALSync#411]
Since webtoons and manhwa are getting pretty big currently it might be a good idea to add webtoons to the extension. 

Thanks for your hard work!

**Comment by lolamtisch** [comment]
Myanimelist has nearly no entries for manhwa. Even anilist only has 2 of the current webtoons top 10 in the database. I think this does not make sense.

**Comment by henrik9999** [comment]
Also they have bad naming schemes which will make it hard for malsync

**Comment by Krytos** [comment]
> Myanimelist has nearly no entries for manhwa. Even anilist only has 2 of the current webtoons top 10 in the database. I think this does not make sense.

**Comment by Pikcee** [comment]
> Myanimelist has nearly no entries for manhwa. Even anilist only has 2 of the current webtoons top 10 in the database. I think this does not make sense.

Would you reconsider this? it has been 2 years, both MAL and Anilist support Manhwa entries today and have most of them.

**Comment by DereC4** [comment]
Agreed
