### ISSUE TITLE
Plex sync

### ISSUE THREAD

**Issue by veralion24** [MALSync/MALSync#412]
Plex sync stopped working as of yesterday. Tried disabling and enabling the add-on. Closed and re-opened Plex (both server and web page). restarted my pc, checked for updates etc.
The add-on seems to be working fine on other streaming sites.

 - Browser: firefox
 - Type: Extension

**Comment by lolamtisch** [comment]
I just checked and it is still woking. If you are on the video page and click on the options button do you see the download option?

![image](https://user-images.githubusercontent.com/12599334/87648630-2331d180-c750-11ea-83cf-d6fcbf3d2b08.png)

**Comment by veralion24** [comment]
![image](https://user-images.githubusercontent.com/16888235/87660917-7c0d6400-c768-11ea-9ded-2058446d73d1.png)

That's the only things i'm seeing. Plus the MAL bar is missing on the series main page.

![image](https://user-images.githubusercontent.com/16888235/87661059-ad862f80-c768-11ea-9a66-e903de6462ea.png)

Thought that has happened every now and then, but after a while it works again. Now it's been 2 days since it last apppeared. I will try again the steps i mentioned before.

**Comment by veralion24** [comment]
![image](https://user-images.githubusercontent.com/16888235/87662048-51240f80-c76a-11ea-83e3-c88e88c54a8b.png)

ok, tried another series, it had a download button i clicked it and the option menu appeared as well (on each episode). But the bar (below the name) and the options (right bottom) still not appear on the main series page.

**Comment by lolamtisch** [comment]
The way it works it needs the api tokken to access the plex api. Unfortunatly there is no official way to get that token, but it is part of the download link. That is how i get it. There isnt really a better way. Before that it cant do anything.

To the overview page. Yeah it looks like that does not work anymore i will fix that with the next release.

**Comment by Zeckro** [comment]
Got a similar problem with Emby. For the third time, it doesn't work anymore. The last two times, after some days, it wanted my token and worked again. In the browser inspector and console, it runs these errors: 
MAL-Sync Not Authenticated
(anonym) @ content-script.js:14
Promise.then (asynchron)
(anonym) @ content-script.js:14
r @ content-script.js:14
Promise.then (asynchron)
l @ content-script.js:14
r @ content-script.js:14
Promise.then (asynchron)
l @ content-script.js:14
(anonym) @ content-script.js:14
r @ content-script.js:14
h @ content-script.js:14
init @ content-script.js:14
init @ content-script.js:14
c @ content-script.js:14
(anonym) @ content-script.js:14
Promise.then (asynchron)
(anonym) @ content-script.js:14
(anonym) @ content-script.js:14
n @ content-script.js:1
(anonym) @ content-script.js:1
(anonym) @ content-script.js:1
/#!/item?id=26305&serverId=2f2a92d22fcb4cf2841899be92a15961:1 Uncaught (in promise) Not Authenticated [Emby]
Promise.then (asynchron)
(anonym) @ content-script.js:14
r @ content-script.js:14
Promise.then (asynchron)
l @ content-script.js:14
r @ content-script.js:14
Promise.then (asynchron)
l @ content-script.js:14
(anonym) @ content-script.js:14
r @ content-script.js:14
h @ content-script.js:14
init @ content-script.js:14
init @ content-script.js:14
c @ content-script.js:14
(anonym) @ content-script.js:14
Promise.then (asynchron)
(anonym) @ content-script.js:14
(anonym) @ content-script.js:14
n @ content-script.js:1
(anonym) @ content-script.js:1
(anonym) @ content-script.js:1
content-script.js:14 MAL-Sync Api Call /Items?ids=26305&api_key=undefined
content-script.js:14 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at content-script.js:14
(anonym) @ content-script.js:14
Promise.then (asynchron)
(anonym) @ content-script.js:14
(anonym) @ content-script.js:14
r @ content-script.js:14
p @ content-script.js:14
(anonym) @ content-script.js:14
(anonym) @ content-script.js:1
setInterval (asynchron)
k @ content-script.js:1
(anonym) @ content-script.js:14
e @ jquery.min.js:2
t @ jquery.min.js:2
setTimeout (asynchron)
(anonym) @ jquery.min.js:2
c @ jquery.min.js:2
add @ jquery.min.js:2
(anonym) @ jquery.min.js:2
Deferred @ jquery.min.js:2
then @ jquery.min.js:2
S.fn.ready @ jquery.min.js:2
(anonym) @ content-script.js:14
Promise.then (asynchron)
init @ content-script.js:14
init @ content-script.js:14
c @ content-script.js:14
(anonym) @ content-script.js:14
Promise.then (asynchron)
(anonym) @ content-script.js:14
(anonym) @ content-script.js:14
n @ content-script.js:1
(anonym) @ content-script.js:1
(anonym) @ content-script.js:1
/#!/item?id=26305&serverId=2f2a92d22fcb4cf2841899be92a15961:1 Error in event handler: TypeError: Cannot read property 'url' of undefined
    at chrome-extension://opmfpllkpmoajolblkjnhejkmafldbbh/content-script.js:14:406355

**Comment by veralion24** [comment]
That happens once in a while on plex too before it stopped working altogether. A restart did the trick but sometimes it persisted through restarts aswell.

**Comment by veralion24** [comment]
Lately MAL site is offline a lot, at unexpected times. This might be the main problem as well. I'm not if it helps, so i'm posting the announcement. i guess it messes up with the api since MAL changed their policy.
https://myanimelist.net/forum/?topicid=1851875

**Comment by Zeckro** [comment]
I see, thanks for your reply. I'm still having the issue and restarting did not fix it, sadly. Well, maybe in some days.

**Comment by lolamtisch** [comment]
I will look into both implementations again soon. I think the Emby implementation had some problems at the moment.

**Comment by henrik9999** [comment]
Plex and emby should be fixed in latest version
