### ISSUE TITLE
Open Next Episode Does not work on Turkanime

### ISSUE THREAD

**Issue by toprak** [MALSync/MALSync#417]
**Describe the bug**
I've set up CONTROL+SHIFT+N as shortcut to open next episode whenever I try to use this shortcut it says "Could not find the next ep."

**Steps to reproduce the behavior:**
Open any anime on turkanime and use your shortcut to open next episode.
**Additional information:**
 - Browser: Firefox
 - Type: Extension
 - Url: turkanime.net

**Comment by henrik9999** [comment]
Fixed in latest version
