### ISSUE TITLE
Add support for jellyfin

### ISSUE THREAD

**Issue by vHUGHv** [MALSync/MALSync#419]
Hey, Please add support for [jellyfin](https://jellyfin.org/) servers, it is an open source fork of emby and has support for [plugins](https://jellyfin.org/docs/plugin-api/index.html). It may be simple to do minor changes to the emby plugin to get it working.
Thanks

**Comment by henrik9999** [comment]
the problem with jellyfin is that it doesnt have a domain like plex and emby does and its hard for us to support local ips

**Comment by oae** [comment]
This would be cool. Is it not possible to add a custom domain to options?

**Comment by lolamtisch** [comment]
It is not possible to add custom domains to extensions. At least i could not find a way to do that.

**Comment by oae** [comment]
It seems like in chrome, an extension can request permission from the user. https://developer.chrome.com/extensions/permission_warnings

**Comment by henrik9999** [comment]
> It seems like in chrome, an extension can request permission from the user. https://developer.chrome.com/extensions/permission_warnings

Yeah but with that you still need to have the domain in the optional permission which we don't know at that point the only way I can think of is requesting all pages permission and then running a script on each page to check if it is the user entered domain

**Comment by oae** [comment]
Also, I found the octotree extension that allows custom domains. https://www.octotree.io/features#browser-permissions

```
The following permissions are optional and only requested when you enable Octotree in a GitHub Enterprise domain (*):

webNavigation: needed to inject Octotree sidebar in GitHub Enterprise domains
tabs: needed to inject Octotree sidebar in GitHub Enterprise domains
*: when enabling Octotree in a GitHub Enterprise domain, Chrome displays the prompt for the "Read your browsing history" permission. That's a bit confusing as Octotree doesn't request the history permission or collect your data at all. See this discussion for more details. Firefox, on the other hand, is clearer about the specific permissions being requested by Octotree.
```

**Comment by vHUGHv** [comment]
Could you add a domain such as "https://jellyfin.*" Or is tha?t not supported

**Comment by henrik9999** [comment]
We cannot wildcard domain endings something like jellyfin.sometld would work

**Comment by oae** [comment]
I have created an example extension. When you click the icon, it asks for the current tab's URL permission. 

![image](https://user-images.githubusercontent.com/1043714/92748051-72c9fd80-f38d-11ea-85c8-68d4516ffa6d.png)

When user clicks ok, it is automatically added to the site permissions
![Screenshot from 2020-09-10 17-47-29](https://user-images.githubusercontent.com/1043714/92748570-f683ea00-f38d-11ea-8a36-dbb4e6b909f3.png)
[optional_permissions.zip](https://github.com/MALSync/MALSync/files/5202516/optional_permissions.zip)

**Comment by lolamtisch** [comment]
I gave it some testing. Getting it to work wasn't that easy. But seems like this is a possibility. Going to add it to my todos.

[optional_permissions_injection.zip](https://github.com/MALSync/MALSync/files/5204080/optional_permissions_injection.zip)

**Comment by henrik9999** [comment]
Added
