### ISSUE TITLE
Firefox add-on outdated, while Chrome is on latest release

### ISSUE THREAD

**Issue by mapuya19** [MALSync/MALSync#420]
**Bug Description**
[Firefox add-on](https://addons.mozilla.org/en-US/firefox/addon/mal-sync/) is at 0.7.4, while latest release is at 0.7.9.

**Steps to Reproduce Behavior**
Visit hyperlink above to see that extension was last updated on March 31, 2020.
<img width="484" alt="ScreenShot" src="https://user-images.githubusercontent.com/15944396/89275786-5d341c00-d608-11ea-9bef-0436fddac433.png">

**Additional Information:**
 - Browser: Firefox
 - Type: Extension

**Comment by lolamtisch** [comment]
> Your submission is taking longer than usual to be reviewed and signed. This process could take a few extra hours and up to a couple of days. Due to disruptions caused by the COVID-19 pandemic, it may take up to a week.

The review will take a while. 

And the missing versions are because Mozilla did remove some versions from the store because of some security concerns. I hope i fixed them all with this release so it is back up to date.

**Comment by mapuya19** [comment]
> > Your submission is taking longer than usual to be reviewed and signed. This process could take a few extra hours and up to a couple of days. Due to disruptions caused by the COVID-19 pandemic, it may take up to a week.
> 
> The review will take a while.
> 
> And the missing versions are because Mozilla did remove some versions from the store because of some security concerns. I hope i fixed them all with this release so it can be back up to date.

I figured as much, just wanted to make sure. Thanks for the quick reply!

**Comment by lolamtisch** [comment]
It is now up to date
