### ISSUE TITLE
Weird fullscreen issue 

### ISSUE THREAD

**Issue by Nicebull** [MALSync/MALSync#426]
**Describe the bug**
Unable to enter fullscreen.

**Steps to reproduce the behavior:**
I really have no clue, it dissapears for a while if i disable and re-enable the extension and comes back randomly, i havent found anything in common when it happends. it seems completely random. Sometimes fixes itself by reloading the page and sometimes not, switching between 2 episodes usually fixes it aswell but not always.
**Additional information:**
 - Browser: Chrome
 - Type: Extension
 - Url: 9anime.to

**Comment by lolamtisch** [comment]
Do you use the autofullscreen feature of malsync? If not it is very unlikely that it has something to do with MAL-Sync, atleast i dont know what could trigger in the MALSync code. I never seen that happen for me too.

**Comment by Nicebull** [comment]
I dont use the autofullscreen feature. At first I Didnt think it was MALSync that was the problem but i have tried disabling all my extensions and only keeping MALSync on and the fullscreen doesnt work. Tried with all extensions except MALSync on and fullscreen worked. i really have no clue what the cause is but based on the testing i have done myself i think it seems to be MALSync. but yeah as i dont use any feature related to fullscreen it would be weird if it was MALSync

**Comment by lolamtisch** [comment]
No one ever had that problem to my knowing. On what video provider does that happen, on all of them or on a special one? How often does it happen?

I dont know. Is your pc good enough could be that the extra code he has to execute of malsync is just to much, but i really doubt that.

**Comment by Nicebull** [comment]
its on all video providers. happens basically eveytime except if i binge a show im usually fine after the first episode.

**Comment by lolamtisch** [comment]
Does it only happen on 9anime? Or do other pages have the same problem. For example www.gogoanime.movie they have mp4upload too there. If there is no problem it is an 9anime problem as it uses the same code without any external decencies for the player for both pages.

**Comment by Nicebull** [comment]
have tried other sites before and had the same issue, gogoanime worked fine tough. guess its time to switch sites.

**Comment by lolamtisch** [comment]
I have never heard of that problem from any of my users so no idea really.

**Comment by Lokitodev** [comment]
I'm having this problem too!

**Comment by Lokitodev** [comment]
url: aniwatch.me
Google Chrome: 87.0.4280.88
MAL-SYNC: 0.8.5

I can't put it on fullscreen mode, i tried disabling the extension and re-enabling it, reloading the page, clearing the cache and none of those worked, i just simply cant put the episode on fullscreen :(
