### ISSUE TITLE
[Feature Request] After the 0.7.11 update MALSync has lost some functionality on Firefox for Anroid (Fennec)

### ISSUE THREAD

**Issue by neipai** [MALSync/MALSync#430]
Because the "Make pop out window size and position configurable" feature changed the floating menu behavior when I touch the miniMAL floating button nothing happens. (I can only assume this is so because there are no "windows" on Android.)
In other words the only way for me to reach the miniMAL menu is: Touching the 3-dot button at the top right corner > touching the "MAL-Sync" add-on on the menu.
And this opens a new tab which does not load the relevant anime/manga page so I have to search for it myself. So it is possible to use the add-on but in a way that feels crippled. After all previously the menu opened within the tab, fullscreen, and when I was done I could just tap the X button and continue.
Also, I'm not sure if this matters but "Open in separate window option" is turned off alongside every option under the miniMAL part of the settings tab.

2nd issue: I have yet to find a way to submit corrections since I can't use keyboard shortcuts on mobile and I'd rather use the floating button to bring up the miniMAL menu and not the correction menu. 
Maybe an option to submit corrections under the overview tab of the menu? (Next to the relevant MAL link?)

I'm submitting these issues as a feature request since I think my problems I listed above would be fixed with a new toggle that'd make the floating menu the way it used to be --rather than opening in a separate window which seems to not work at all on Android. The way it is right now, add-on does work on the desktop Firefox but I'm not exactly a fan of how the pop out window is configurable.
I'm not sure if MALSync is even compatible on FF Android but still I'd love to be able to pick-up on my phone from where I left off on the PC.

In another note, regardless of these issues, I'd like to thank you guys for this awesome add-on. This changed the way I watch anime and read manga, so thanks lolamtisch and everyone that has contributed to this great add-on.

**Comment by lolamtisch** [comment]
We had to remove the onsite miniMAL because of security concerns by firefox. 
The open in new window will have to stay. I will probably have to write a fallback so that it uses the open in new tab browser api instead of a new window for firefox android.

This does not really help with the correction ui as using the shortcut is not possible on mobile and moving the ui into the miniMAL tab isnt possible either as they are then seperate instances and it has to guess what the correct tab to talk to is.

**Comment by neipai** [comment]
Thanks for the clarification.

I guess opening in a new tab would be manageable for android if not as elegant, and I can just use the MALSync extension button on the toolbar when it comes to the desktop FF.
Or I can just get used to the new version which does work on desktop and the fact it loads the anime/manga on the selected tab is really cool. And if the window could be snapped it might work even better than the way it used to... (at least as good)

When it comes to the correction ui for the android version, would adding a second button that could also be hidden work? Or maybe a hold function to the floating button?

**Comment by lolamtisch** [comment]
Holding is not a native feature of the web and needs to be implemented by hand and specially with touchscreens it is difficult. The same for swipe gestures. I will use this issue for these two points now.

- [ ] Fix new window handling on firefox mobile
- [ ] Think of an alternative way to open the correction on mobile

**Comment by lolamtisch** [comment]
In the settings you can map the correction menu to the floating button
