### ISSUE TITLE
Kissanime & Kissmanga has now Shutdown (Informational)

### ISSUE THREAD

**Issue by DavidCarbon** [MALSync/MALSync#431]
Just to give a heads up, kissanime and kissmanga, announced their closures. Their respective sites now show the following: 

![image](https://user-images.githubusercontent.com/9911250/90306440-18b74480-de82-11ea-96a2-353277ac906a.png)

- Anime: https://kissanime.ru/
- Manga: https://kissmanga.com/

**Comment by neipai** [comment]
https://kissanime.nz exists but it is not supported by MALSync

Other Kiss sites with the .nz domain that I know of:
https://kisscartoon.nz/
https://kissasian.nz/

**Comment by henrik9999** [comment]
> https://kissanime.nz exists but it is not supported by MALSync
> 
> Other Kiss sites with the .nz domain that I know of:
> https://kisscartoon.nz/
> https://kissasian.nz/

all fake wont be added

**Comment by henrik9999** [comment]
Removed in latest version
