### ISSUE TITLE
Support for adding anime/manga/manhua/manhwa/webtoon which is not in MAL

### ISSUE THREAD

**Issue by sharoha** [MALSync/MALSync#438]
Does anyone know if I can add a anime/manga/manhua/manhwa/webtoon in MALSynch to track progress even if it is not present in myanimelist?

**Comment by farahnur42** [comment]
Yes, just select no MAL in the correction menu (the default hotkey is C, you can change it to something else in the settings) and it will be stored in your local storage. @sharoha You can also switch to AL if you want access to a lot more manhwas and manhuas.

**Comment by henrik9999** [comment]
Closing this. As stated above.
