### ISSUE TITLE
More choices for Streaming Site Links

### ISSUE THREAD

**Issue by ChristopheRoyer21** [MALSync/MALSync#440]
In the options, there is only a limited choices of Streaming Site that we can click on the MiniMAL so it will redirect us. Is there any plans on adding more of them soon? Mine (animepahe) is not not on the list and that would be neat if it could. 

I see there's also the Search option in the beginning of the list (in the option) I guess that could solve my problem, but I don't really understand how to use it. Even though it is enabled, it doesn't appear in my choices.
Thank you

**Comment by henrik9999** [comment]
luckily for you, animepahe will be added to it next release
