### ISSUE TITLE
Add Related Anime Section on Supported Websites

### ISSUE THREAD

**Issue by laxyapahuja** [MALSync/MALSync#442]
I thought it'll be really useful if the related anime can also be added on all the supported websites so it's easier to move to the next season when you finish an anime or just for the sake of convenience.

![image](https://user-images.githubusercontent.com/31318248/91046733-96bfdc00-e636-11ea-94a4-4643d2ee8dae.png)

**Comment by henrik9999** [comment]
That would only work for pages with our database support and those probably all already have relations themselves

**Comment by henrik9999** [comment]
Aniwatch provides relations

**Comment by lolamtisch** [comment]
We dont use jikan and use scrappers for mal. It is possible but it would be too much work for such a minor feature. 3 clicks in miniMAL dont take more than 15 seconds.
