### ISSUE TITLE
Aniwatch next episode links not working

### ISSUE THREAD

**Issue by rowantran** [MALSync/MALSync#443]
Just wanted to say thanks for developing this plugin -- it definitely smooths out the experience a lot. 

However, I noticed that when clicking "resume watching," the link to the streaming site goes to the last watched episode. e.g. if the anime is marked as 4/12 watched in MAL, the link goes to episode 4. This seems unintuitive to me, since I would expect "resume watching" to send me to the next unwatched episode, not the last episode that I've already watched.

Is this the intended behavior, and if so would it make sense to change it to link to the next episode?

**Comment by henrik9999** [comment]
resume watching sends to the current episode next to it should be a button that sents you to the next episode maybe the site you are watching on which is ist? Doesn't support the next episode feature from Malsync

**Comment by lolamtisch** [comment]
The continue watching link sends you to the next episode. But if there isnt enough information in the system it will show the resume watching button. So it is working as it should. 

You can disable the resume watching links in the settings if you only want to the see the continue watching links if they exist. 

What page are you using? Not every page support next episode link retroviral. Or it is bugged.

**Comment by rowantran** [comment]
That makes sense, thank you. I wasn't aware of the distinction between resume watching and continue watching. But I'm currently using Aniwatch -- should it support the "continue watching" link at the moment?

**Comment by lolamtisch** [comment]
Yeah it should, but currently it is a bit buggy we will look into it.

**Comment by henrik9999** [comment]
Fixed in latest version
