### ISSUE TITLE
"is not a valid value for id. " when using kitsu

### ISSUE THREAD

**Issue by funnisquares** [MALSync/MALSync#444]
**Describe the bug**
Unable to synchronize with kitsu, always get "is not a valid value for id. "  when trying to update entries.

**Steps to reproduce the behavior:**
Set "Mode" setting to kitsu > authenticate > start watching an episode

**Additional information:**
 - Browser: firefox
 - Type: extension

**Comment by lolamtisch** [comment]
@funnisquares 
Works fine for me. Where exactly do you have the problem. What anime and which page are you on?

**Comment by funnisquares** [comment]
I had the same problem both on 9anime and 4anime, the animes I tried were "Deca-dence" and "The God of High School"

**Comment by lolamtisch** [comment]
Both work for me. Could you press the key F12 and open the console tab in there. The error should popup there too. Could you send me a screenshot of it extended?

**Comment by funnisquares** [comment]
Now it is working flawlessly haha. I switched to mal then back to kitsu, and now it is updating properly.
