### ISSUE TITLE
[Feature Request] Way to disable "mal-sync-ep-pre"

### ISSUE THREAD

**Issue by antocs** [MALSync/MALSync#452]
I noticed this things in the latest update, a new number beside the actual episodes count (I use both MyAnimeList and AniList, the screenshots are on AniList but the same is on MyAnimeList).
Add a way to disable it (or remove it at all?), cause I noticed more than once that the episode in square brackets doesn't update after you mark the episode as watched, the example below is "Ahiru no Sora", 47 watched but still 46 shown.
Also, as personal preference, I would like to not see it cause it's bad looking imo with a new number.
![image](https://user-images.githubusercontent.com/22413659/92593028-bdba1700-f2a0-11ea-99d7-4e64004335ad.png)
![image](https://user-images.githubusercontent.com/22413659/92592770-64ea7e80-f2a0-11ea-98cc-77e9d91861ba.png)

**Comment by lolamtisch** [comment]
The number is the estimated newest episode/chapter. 
I found a bug that makes it impossible to deactivate it atm. Tomorrow i will make a new release that fixes it. I will let you know then how to disable it.

**Comment by lolamtisch** [comment]
The new update is out. Just disable the Estimate episode number option.
