### ISSUE TITLE
Toggle for the console.log

### ISSUE THREAD

**Issue by NOSDOOM** [MALSync/MALSync#453]
I was wondering if it would be possible to get a toggle or something to turn off the console logging. I'm sure it's not an issue for most people but so often when I have to debug a script I have to disable the MALSync extension because the console log is full of entries and it takes a while for the console to open every now and then. It could maybe be a toggle that's default position is on and the user can decide to turn it off that way it could be activated if there is an issue people need to give you info for.

**Comment by lolamtisch** [comment]
I had an Similar system to that in the past. But somehow that kills the performance quite a bit so i removed it and was kind of pointless. With the default logging settings MAL-Sync really doesn't log much and never had any performance problems with the dev-tools. They are like 20 entries per page or so.

Personally I dont want to add an logging toggle, as people like to enable random settings and then helping to debug things it is a pain then.

**Comment by NOSDOOM** [comment]
Huh weird. Understandable though. There's an entry every second so I figured if it was possible a toggle would be great but I get the pitfalls outweigh it. Thank you.

**Comment by lolamtisch** [comment]
It is logged in verbose. So if you disable that then it should not show anymore. That is the default logging setting too
![image](https://user-images.githubusercontent.com/12599334/92936637-9d2dc080-f44a-11ea-8bc9-a9a61174350c.png)

**Comment by NOSDOOM** [comment]
Thank you!
