### ISSUE TITLE
MAL Episode Progress in PTW Animelist

### ISSUE THREAD

**Issue by Whitedoteu** [MALSync/MALSync#465]
**Describe the bug**
Not sure how long ago!
Every Anime in my Listview was showing an Episode Progress.

Now this is not longer working. "Kind of"

If i open the Animedetailpage I can see the Episode Progress. 
When i reload the Animelistafter that the Episode is also showing up. 

 
**Steps to reproduce the behavior:**
Open MAL Animelist
Open Anime Detailpage
Reload MAL Animelist

**Additional information:**
 - Browser: Chrome
 - Type: Extension
 - Url: 

I tested with the Adult Extention and without. 
Also tested without Adblocker
Console is showing all Anime that i don't have manuelly opened the Detailpage as undefined
![chrome_oHsUM4OK9R](https://user-images.githubusercontent.com/16068109/93665731-34150100-fa79-11ea-9053-a681e3533766.png)
Episodes are not showing
![chrome_pJ5FmAwlsv](https://user-images.githubusercontent.com/16068109/93665733-35dec480-fa79-11ea-89ae-2cccdab9c458.png)
Video with Reload Page
[MP4Video.zip](https://github.com/MALSync/MALSync/files/5249733/MP4Video.zip)

**Comment by lolamtisch** [comment]
Since the last release the implementation replaced with a new system that supports manga too. Could you check if the "Progress Check" is enabled in the settings? Not the update check that is something else.

Changing the interval time should force the update of the data too if you don't want to wait. The browser icon should have an hoverglass showing that it is running. When it is done just reload.

Could be that you cleared the cache or changed the provider because that deletes all data until the next progress check.

**Comment by Whitedoteu** [comment]
I tryed cleaning the Cache a few Hours ago. And the update was set to 1h so it should be up-to-date.

I'm not sure where to enable Progress Check? Is thatset only with the interval?

![IdZWJQ0QMV](https://user-images.githubusercontent.com/16068109/93671421-2a07f800-faa3-11ea-85ac-f0192afdbcdf.png)

I tryed changing every Value

![chrome_exv1X1aQVx](https://user-images.githubusercontent.com/16068109/93671448-591e6980-faa3-11ea-8d5c-4227119376a7.png)

I'm getting the hourglas but only for a second or so. 

![chrome_QV44Soctyb](https://user-images.githubusercontent.com/16068109/93671482-b0bcd500-faa3-11ea-9bd3-f711a62a1250.png)

When changing manuelly i can't see anything in the Networklog.
Is there an fixed URL to get the Data? So i can check if I'm able to connect to the URL?

If you want to debug on my PC we can setup a session and debug that thing together.

**Comment by henrik9999** [comment]
maybe come and join the discord so we can talk there https://discord.gg/cTH4yaw

**Comment by lolamtisch** [comment]
Yeah it is easier on discord.
The url for example is like this https://api.malsync.moe/nc/mal/anime/19815/pr
But i dont think that is the problem as you see it on the overview page of an anime.
You have to check the backgroundpage of the extension if you want to debug it. Enable developer view on the upper right and check the background page
![image](https://user-images.githubusercontent.com/12599334/93671758-085c4000-faa6-11ea-89d7-90b127c8021f.png)
