### ISSUE TITLE
gogoanime.video episode tracking problem

### ISSUE THREAD

**Issue by MysticalFlame** [MALSync/MALSync#475]
**Describe the bug**
Mal sync does not track how far I am in a episode or update when I watch episodes on gogoanime.video on the Vidstreaming server.

**Steps to reproduce the behavior:**
go to https://www2.gogoanime.video/
watch an anime episode using vidstream server
Mal-sync will not track progress

**Additional information:**
 - Browser: chrome
 - Type: Extension/Userscript
 - Url:https://www2.gogoanime.video/

**Comment by henrik9999** [comment]
Is already fixed for the next release

**Comment by henrik9999** [comment]
should be fixed in latest release
