### ISSUE TITLE
Split anime with episode offset

### ISSUE THREAD

**Issue by lublak** [MALSync/MALSync#490]
As an example: https://www.anime-on-demand.de/anime/258
Fairy Tale can't track after Episode 175 because in anilist and myanimelist FairyTail ist splitted after 175
The first 175 episodes are: https://anilist.co/anime/6702/Fairy-Tail/
The remaining 102 episodes are: https://anilist.co/anime/20626/Fairy-Tail-2014/
On Animeondemand we have all episodes on one page.

**Comment by farahnur42** [comment]
Use the correction menu to correct the entry and add an episode offset @lublak , the default hotkey for it is C.

**Comment by lublak** [comment]
@farahnur42 yes i know this function but 2 seasons are on the same page.
So the correction is not possible.

**Comment by lolamtisch** [comment]
The current workaround is to watch the first season and then correct it to the second one with the offset.
