### ISSUE TITLE
9Anime can't detect Vidstream server

### ISSUE THREAD

**Issue by fr0r** [MALSync/MALSync#492]
**Describe the bug**

The MAL-Sync 9Anime integration will loop, always trying to detect the player when the Vidstream is selected, causing the episode being watched, not to be counted.

Github hates my ~~comically~~ large gifs, [so here's a direct link to it](https://menma.is-inside.me/kkAp84cz.gif).

**Steps to reproduce the behavior:**

1. Open a random anime series
2. Select Vidstream as your server
3. Click ``OK`` on MAL-List Watching status.

**Additional information:**
 - Browser:  Microsoft Edge 87.0.658.0 dev (64 bits)
 - Type:  Extension

**Comment by henrik9999** [comment]
Yeah I will fix this for the next release

**Comment by henrik9999** [comment]
Fixed in latest version
