### ISSUE TITLE
Potential 9anime bug: skip op, other shortcuts broken

### ISSUE THREAD

**Issue by charlesdrose** [MALSync/MALSync#499]
With the reskin of 9anime and the video server change, my skip op hotkey isn't working anymore. I've tried changing binds to no avail. Is it a video server problem, or something else entirely?

Browser: Brave
Version: Chromium Extension 0.8.3

**Comment by henrik9999** [comment]
You are probably using vidstream player which is still not supported by malsync only in the next release

**Comment by charlesdrose** [comment]
Noted and accounted for. Thanks for the quick feedback. :)

**Comment by henrik9999** [comment]
Then I will close this as #492 exists
