### ISSUE TITLE
Matching localhost plex / organizr

### ISSUE THREAD

**Issue by daephx** [MALSync/MALSync#500]
So I installed the extension and it's worked out pretty great for Crunchyroll and plex. Doing gods work, appreciate it!
However, I noticed that plex from the localhost ie. `localhost:32400` the extension is under 'no access needed' so Its not activating. Just to confirm I watched a few episodes from both domains and only plex.tv was syncing.
Would this simply be due to the app not recognize the proper domain `https://app.plex.tv`; if so is there any way to set localhost as a custom domain?

As a side note to that I tend to use [Organizr](https://github.com/causefx/Organizr) for plex on my home network, currently under `localhost:8099`; the difference there I believe is that plex is served in an iframe and I was curious as to if the extension would be able to recognize plex in that environment?

**Comment by lolamtisch** [comment]
Yeah currently it can not be used with a custom domain or localhost. Webextension dont allow easy adding of new domains that are not defined in the release and adding localhost is obviously not a good idea by default.

But we have a solution for that in view #419. It will need an alternative script injection, an custom interface to add the domains and alternative page detection. Still did not begin with it, but expect it in the near future.

**Comment by henrik9999** [comment]
Custom domain support has been added see https://github.com/MALSync/MALSync/wiki/Custom-Domains

I don't think organizer will be added
