### ISSUE TITLE
"Set as completed" not working

### ISSUE THREAD

**Issue by lilcsz** [MALSync/MALSync#502]
When i click OK nothing happens.

Image:
![image](https://user-images.githubusercontent.com/43272857/96726454-aa7b8a80-13ba-11eb-967d-e7edee38dd25.png)

 - Browser: Opera GX
 - Type: Extension
 - Url: https://www.turkanime.net

**Comment by lolamtisch** [comment]
What player are you on? You have to watch 85% of a video before it updates

**Comment by lilcsz** [comment]
Sorry I wasn't know that, I just clicked completed for testing.
