### ISSUE TITLE
Support for "wcostream"

### ISSUE THREAD

**Issue by A-Sparowe** [MALSync/MALSync#508]
Hi! I'm new to using this awesome extension/app and while the list of available streaming sites is pretty large I noticed one I use pretty much all the time  was missing and that's "wcostream.com". I didn't see it in the list list to be added so I figured I'd mention it.  Great service you guys have btw! Glad I found it!

**Comment by henrik9999** [comment]
they put ovas and other stuff in the same animes so i wont be doing it
