### ISSUE TITLE
Auto Detect OVA

### ISSUE THREAD

**Issue by lilcsz** [MALSync/MALSync#516]
URL Can be changed manual but auto detect will be better i think

![1](https://user-images.githubusercontent.com/43272857/98840041-629ad100-2457-11eb-9b1e-77fc907b6c50.PNG)
![2](https://user-images.githubusercontent.com/43272857/98840146-7cd4af00-2457-11eb-88b5-bb6ca770d46e.PNG)

**Comment by lilcsz** [comment]
Uptade: I changed URL still having problems.

**Comment by lolamtisch** [comment]
You can add an offset to the episode number. I imagine here in the example everything after Bölüm 13 is a special. So the offset should be -13 and the url should be set to the ova.

**Comment by lilcsz** [comment]
> You can add an offset to the episode number. I imagine here in the example everything after Bölüm 13 is a special. So the offset should be -13 and the url should be set to the ova.

Thanks
