### ISSUE TITLE
mangakakalot support

### ISSUE THREAD

**Issue by Krappa420** [MALSync/MALSync#519]
I would love mangakakalot support, its one of the popular sites out there.
I saw in the changelog it was removed with no explanation.

Please add this.

**Comment by henrik9999** [comment]
just use https://manganelo.com/

**Comment by lolamtisch** [comment]
mangakakalots db is broken and strange. Manganelo is the same page just less broken.

**Comment by Krappa420** [comment]
@lolamtisch @henrik9999 99% of my read manga is on mangakakalot, anyway to transfer to manganelo?

![image](https://user-images.githubusercontent.com/66475753/99127070-a52dec00-25c4-11eb-8d22-60da918ca387.png)

this is what I mean like it shows me my read/last read, dont want to lose these. any tips ?
