### ISSUE TITLE
Disable fullscreen notifications

### ISSUE THREAD

**Issue by PhilAnders** [MALSync/MALSync#539]
With the most recent update, there was support added for fullscreen notifications.
Getting a popup at the bottom of the screen near the end of each episode just to tell me it added it to my list is not only distracting, but detracts from my immersion in the show. Is there a way to disable fullscreen popup notifications?
If not, please consider this as a feature request.

**Comment by lolamtisch** [comment]
Yes the stealth UI option does remove fullscreen popup and makes a lot of the UI less intrusive.
