### ISSUE TITLE
Anilist Authentication 404

### ISSUE THREAD

**Issue by 8227846265** [MALSync/MALSync#542]
**Describe the bug**
I'm using the userscript version of MALSync and trying to authenticate Anilist. However, this is what I get after authenticating
![image](https://user-images.githubusercontent.com/66582769/102842730-9a2b6e80-4442-11eb-811a-a7d956351662.png)

**Steps to reproduce the behavior:**
1. Install userscript version
2. Authenticate Anilist

**Additional information:**
 - Browser: Brave (Version 1.18.75 Chromium: 87.0.4280.101 (Official Build) (64-bit)
 - Type: Userscript (https://greasyfork.org/en/scripts/372847-mal-sync)
 - Url: https://anilist.co/

**Comment by 8227846265** [comment]
Issue fixed. I just have to simply change the Site Access of the Tampermonkey extension back to All Sites. 

Then upon completion of the authentication, change it back to specific sites I only want to run Tampermonkey.

**Comment by farahnur42** [comment]
@8227846265 You should also use the non-userscript variant (the extension) as it both has more features and gets more dev time, if possible.

**Comment by 8227846265** [comment]
I prefer using the userscript since it reduces the amount of extension I install on my browser :)
