### ISSUE TITLE
Support for MANGA Plus by SHUEISHA

### ISSUE THREAD

**Issue by 8227846265** [MALSync/MALSync#548]
Please add support for https://mangaplus.shueisha.co.jp/ (MangaPlus seems to source the release from https://www.viz.com/shonenjump/ as well)

Thank you.

**Comment by farahnur42** [comment]
@8227846265 MangaPlus doesn't source the releases from Viz, MangaPlus **IS** Viz (it's a collaboration between Viz and Shueisha) and also it's already supported.

**Comment by 8227846265** [comment]
I see. That's good to hear. Thanks
