### ISSUE TITLE
Watching anime on Plex where the seasons are in Parts makes it so you can only sync the first part

### ISSUE THREAD

**Issue by tobinstultiens** [MALSync/MALSync#556]
As I described in my title with shows like season 3 of AOT it's setup in 2 parts [part 1](https://myanimelist.net/anime/35760/Shingeki_no_Kyojin_Season_3) [part 2](https://myanimelist.net/anime/38524/Shingeki_no_Kyojin_Season_3_Part_2).
My request would be that you can transition to the different part if the show where to continue after MAL says it should have ended.

**Comment by lolamtisch** [comment]
We have no solution for this problem currently. But we have a manual workaround for this.

Watch the first 12 episodes. When hitting the 13ths episode correct the entry to part two and add an episode offset of -12 and then continue watching to the end. This way the tracking is correct.

The correction popup can be opened with `c` (Default shortcut can be changed in the settings)
![image](https://user-images.githubusercontent.com/12599334/103797704-1c25b500-5049-11eb-9132-e37f63691296.png)
