### ISSUE TITLE
Option to disable manga module

### ISSUE THREAD

**Issue by Wrizz** [MALSync/MALSync#558]
Like the title says. Is there a possiblity to make an option that disables all manga functionality from the extension? I do use the anime functions but I don't really like the manga functions. It shows the menus on every manga/comic/webtoon/manhwa etc. I read. It's annoying since MAL has only japanese mangas and nothing else.

**Comment by henrik9999** [comment]
You can disable a page in the Settings under General the blue Website button

**Comment by Wrizz** [comment]
> You can disable a page in the Settings under General the blue Website button

Oh I see. One click button would be great though. Well anyway, thanks!
