### ISSUE TITLE
Scrolling lags 1frame every 5s on Firefox

### ISSUE THREAD

**Issue by weirdal3333** [MALSync/MALSync#561]
My computer is a low-end computer. The scroll is 1 frame every few seconds, and never increases. Other pages load and scroll fine, even if I have 20 tabs (until the computer randomly freezes). 
Even with 1 tab on about:blank and no other options it still scrolls the same. I have tried enabling and disabling hardware acceleration and smooth scrolling options. 

I am running:
Browser: Mozilla Firefox For Ubuntu 84.0.2
OS: lubuntu 19.04 x64
CPU: Core 2 Duo
Ram: 1gb onboard ram, 2gb sodimm
Drive: 128gb SSD
Graphics: Intel integrated graphics VGA port, 1920x1080p 30hz

**Comment by henrik9999** [comment]
Do you mean the scroll on the malsync pop up or on some page

**Comment by weirdal3333** [comment]
The scrollbars in the MAL popup
Additionally, it doesn't matter which popup I use; it's always slow.
If I open up the MAL popup as a separate browser window instead of a popup, there's no scroll lag. I have other popups extensions that don't have the scroll issue (for example, the honey app)

**Comment by lolamtisch** [comment]
This is a firefox problem and not related to malsync. The code of the seperate browser window mode is the same as in the popup and in the window everything is smooth. I found a bug with a semilar problem. Seems like they currently (28days ago) changed the scrolling behavior for popup windows in the nightly build. 

Could you test if it works better in firefox nightly. If yes, then you have to use nightly or wait for firefox to release the next version. Alternatively use the open in new window until then.

https://bugzilla.mozilla.org/show_bug.cgi?id=1490487

**Comment by lolamtisch** [comment]
It is now in the stable version of firefox. It should now have no performace problems anymore.
