### ISSUE TITLE
Support showing anime status on https://chiaki.site/?/tools/watch_order pages

### ISSUE THREAD

**Issue by soredake** [MALSync/MALSync#562]
It will be nice to show anime status on these pages like on mal.

Example created in GIMP:
![Screenshot_20210114_180607](https://user-images.githubusercontent.com/5204968/104616815-6df6bc80-5693-11eb-9aa7-4b1e2e3aa069.png)

**Comment by lolamtisch** [comment]
It is a bit too far from the main purpose of malsync. This is more a feature for a seperate userscript.
