### ISSUE TITLE
Add more 9anime domain TLD's

### ISSUE THREAD

**Issue by cherryleafroad** [MALSync/MALSync#570]
This isn't a "typical" bug report, but nevertheless because there are a few more 9anime domain TLD's not listed in the extension, I feel it's suitable as a bug report.

There are  few more 9anime domains that the extension doesn't check. Specifically the endings
```
.bar
.pw
.cz
```

The benefit to adding these official domain TLD's doesn't need to be stated, as the extension doesn't work on these official TLD's because they're not listed.

Note: If you visit `9anime.zone` you WILL NOT see these listed, even though they are valid and official. What gives? No idea, but if you want to verify for yourself that these are legitimate, go to the official 9anime Discord and ask them. They will verify the authenticity.

**Comment by henrik9999** [comment]
For now you can add the domain yourself
https://github.com/MALSync/MALSync/wiki/Custom-Domains
