### ISSUE TITLE
Watched episodes not highlighted

### ISSUE THREAD

**Issue by cherryleafroad** [MALSync/MALSync#571]
**Describe the bug**
When you watch an episode and it is marked as completed watching, ordinarily the previous watched episodes will get highlighted blue, however, if you use specific domains it won't show up (although other parts of the extension work properly)

**Steps to reproduce the behavior:**
1. Go to an anime that you've seen that should have marked (blue) episodes. I used 9anime.live for this one.
2. You can see that the episodes are marked blue as they should be.
3. Now, keep everything in the URL, but change the domain to 9anime.to instead (my full URL was www12.9anime.to)
4. Extension works, but previously seen episodes are not marked blue anymore.

I have a 100% reproduce rate with this. It is not required to go to a different working one first, I merely included that in steps for contrast.

**Additional information:**
 - Browser: Chrome 87.0.4280.141
 - Type: Extension from Chrome store v0.8.5
 - Url: 9anime.live (working one), www12.9anime.to (not working one)

**Comment by henrik9999** [comment]
come and join the discord so we can talk i cannot reproduce this https://discordapp.com/invite/cTH4yaw

**Comment by cherryleafroad** [comment]
Turns out it's an extension conflict.

**Comment by cherryleafroad** [comment]
If anyone else has an issue (maybe you're coming from Google), check and disable any extensions that might be modifying the website styling. In my case, it was a darkmode extension.
