### ISSUE TITLE
Domain changed

### ISSUE THREAD

**Issue by Oreloth** [MALSync/MALSync#574]
Domain for OtakuFR changed :

Old domain : https://www.otakufr.com/

New domain : https://otakufr.co/

![image](https://user-images.githubusercontent.com/14059407/105650535-4df5a300-5eb4-11eb-92ba-39616eeb6601.png)

**Comment by farahnur42** [comment]
@Oreloth https://github.com/MALSync/MALSync/wiki/Custom-Domains Use this to put the domain in yourself, it should work as long as they haven't changed anything in the HTML of the site
