### ISSUE TITLE
Invalid Parameters when clicking "Undo"

### ISSUE THREAD

**Issue by cherryleafroad** [MALSync/MALSync#579]
**Describe the bug**
Bottom dialog popup displays "Invalid Parameters" when clicking "Undo"

**Steps to reproduce the behavior:**
1. On 9anime, go to a show you've never tracked before
2. When the dialog "Start Watching?" appears, click "Ok"
3. Go to bottom of screen, hover over popup, click "Update MAL to episode 1"
4. Click "Undo" on the popup
5. You will see "Invalid Parameters"

**Additional information:**
- Using MAL as tracker, using MyAnimeList API Beta (might also happen on normal MyAnimeList mode too - untested)
 - Browser: Chrome
 - Type: Extension
 - Url: Any anime show on 9anime you have never tracked before. Might also apply to other sites, but currently untested

**Comment by henrik9999** [comment]
Probably only happens on api beta
