### ISSUE TITLE
9anime: Clicking "Ok" on "Start Watching" doesn't update UI

### ISSUE THREAD

**Issue by cherryleafroad** [MALSync/MALSync#580]
**Describe the bug**
When clicking "Ok" to the "Start Watching?" popup on a new untracked show, the website MAL-Sync UI will not update and still says "Add to MAL". In fact, even if you reload the page after clicking "Ok", it still says "Add to MAL"

**Steps to reproduce the behavior:**
1. Go to show you've never tracked
2. Click "Ok" on popup "Start Watching?"
3. Observe that the UI MAL-Sync tracker still says "Add to MAL"
4. Reload webpage (it should have updated right?).
5. Observe it still says "Add to MAL". Additionally, the "Start Watching?" popup will appear again

**Additional information:**
- Happens on both MyAnimeList API beta and regular MyAnimeList modes
 - Browser: Chrome
 - Type: Extension
 - Url: 9anime sites

**Comment by henrik9999** [comment]
Do you have the video tracking enabled, then it will only set it to start watching after 80% of the video or what it was

**Comment by cherryleafroad** [comment]
I do have video tracking enabled yes
