### ISSUE TITLE
9anime: Clicking "Add to MAL" redirects to homepage

### ISSUE THREAD

**Issue by cherryleafroad** [MALSync/MALSync#581]
**Describe the bug**
Clicking the "Add to MAL" link on a new untracked show sends the user to the homepage instead of staying on current page

**Steps to reproduce the behavior:**
1. Go to untracked show
2. Click "Add to MAL"
3. You get redirected away from page you were on

**Additional information:**
- This appears to be caused by the link, `<a id="AddMal" href="#">Add to MAL</a>`. The `#` is being interpreted as `https://9anime.tld/#` and thus causes the browser to load the new page
 - Browser: Chrome
 - Type: Extension
 - Url: 9anime sites

**Comment by henrik9999** [comment]
Known bug already fixed for next release
