### ISSUE TITLE
Next Episode Shortcut opens different link of alternative

### ISSUE THREAD

**Issue by DishankJ** [MALSync/MALSync#592]
**So I use animepahe.ru because I can't get access to the main URL that is animepahe.com So I set up a shortcut for the next episode but when I press the shortcut button it opens the next episode's url in the main url rather than in the alternative one.**

**Comment by henrik9999** [comment]
It's not our problem we use the animepahe shortlinks because the other ones are session based and run out after a few hours

**Comment by henrik9999** [comment]
You can use a Userscript for this
```
// ==UserScript==
// @name        redirect animepahe
// @match       *://*.animepahe.com/*
// @run-at      document-start
// @grant       none
// ==/UserScript==

window.location = window.location.href.replace('animepahe.com', 'animepahe.ru')
````
