### ISSUE TITLE
wont sync from netflix

### ISSUE THREAD

**Issue by cherushii** [MALSync/MALSync#595]
mal-sync has been working fine but suddenly it wont track my progress when i watch on netflix

**Comment by henrik9999** [comment]
Please post more info what url etc

**Comment by cherushii** [comment]
i was watching dr. stone on netflix. then when i noticed it's not working anymore i checked on other anime shows on netflix again (hxh, bsd) and saw that the mal-sync progress indicator and the miniMAL button are both missing. i tried to check on other steaming sites (aniwatch) and even a manga site (mangasee), and mal-sync is working. the problem is only with netflix

**Comment by BjornHelheim** [comment]
Netflix sync is not working for me either. Watching Beastars on Netflix.

**Comment by henrik9999** [comment]
Its fixed for the next release
