### ISSUE TITLE
Mangadex - Malsync automatic tracking doesn't work

### ISSUE THREAD

**Issue by trespordez** [MALSync/MALSync#599]
'info pop-ups' isn't working in any manga page (but it shows the manga info by clicking on the extension icon)

 - Browser: Chrome 88.0.4324.150 (x64)
 - Type: Extension
 - Url: https://mangadex.org/chapter/1202680/1

**Comment by henrik9999** [comment]
Post a example link

**Comment by henrik9999** [comment]
Closing this for #600

**Comment by henrik9999** [comment]
Fail

**Comment by trespordez** [comment]
> Post a example link

Example link added

**Comment by henrik9999** [comment]
Tracking and popups work fine for me. Can you explain more what do you mean with "info pop-ups"

**Comment by trespordez** [comment]
> Can you explain more what do you mean with "info pop-ups"

The one who appears when you turn off automatic sync, for manually update an anime/manga entry. The extension detects the manga, but doesn't work on the page itselft (MiniMAL, for example).

**Comment by lolamtisch** [comment]
It only shows the popup if the opened chapter is higher than the one set on mal. Are you sure that is the case?

**Comment by trespordez** [comment]
> It only shows the popup if the opened chapter is higher than the one set on mal. Are you sure that is the case?

That's the case, yes ^^
But, if i remember well, i had to manually update the chapter count on the extension (previous release). Anyway, it's working with the latest version, thank you!
