### ISSUE TITLE
Support for additional manga sites

### ISSUE THREAD

**Issue by hemlok89** [MALSync/MALSync#6]
Kissmanga is too ad riddled & mangadex has a lot of update missing. Can you add some other manga site support? My two suggestion would be [MangaNelo](https://manganelo.com/home) & [MangaRock](https://mangarock.com/)  

- [x] [MangaNelo](https://manganelo.com/home)
- [X]  ~~[MangaRock](https://mangarock.com/)~~
- [x] https://mangaplus.shueisha.co.jp/
- [X] [MangaPark](https://mangapark.me/)
- [ ] https://www.readmng.com/
- [ ] ~~https://readms.net/~~
- [X] mangaseeonline.us

**Comment by DeeeFoo** [comment]
I would also throw in MangaPark, since it, like Kissmanga, has the option to view all the pages in a chapter in one long strip.

**Comment by hemlok89** [comment]
I appreciate that you are willing to add new pages. And also can understand that maintaining a database is troublesome. But you can make it manual so the user can search & link manga or anime from their preferred site to mini mal. And the data is stored locally.

**Comment by lolamtisch** [comment]
![image](https://user-images.githubusercontent.com/12599334/47010738-2b567a80-d140-11e8-865e-763d53bf1a7a.png)
This is already saved localy (to be specific on mal) and will work without the database.

Only on the side bar it wont show up.
![image](https://user-images.githubusercontent.com/12599334/47010826-6d7fbc00-d140-11e8-99d8-00c1febb0a74.png)

**Comment by lolamtisch** [comment]
In case you missed it. There is a survey running to this.
https://goo.gl/forms/gRdoO4APyeKYFxk83

**Comment by matrixik** [comment]
I would suggest also https://www.webtoons.com/en/

**Comment by duradara** [comment]
I would also want https://tmofans.com if posible

**Comment by jacobmix** [comment]
I too would vote for Naver Comics/Line Webtoon to be added, and MangaHere + MangaFox.
Also if you need a heap of suggestions there's a lot of good ones [here](https://gitlab.com/all-mangas-reader/all-mangas-reader-2/-/tree/develop/src/mirrors/mirrors).
Also: Tapas, Lezhin Comics, and Ciayo Comics.

**Comment by Deku2k** [comment]
I would suggest also https://toomics.com/ (https://global.toomics.com)

**Comment by ronaldolaj** [comment]
Hi,
Can you add https://mangahost2.com/ too?

Thanks!

**Comment by Arrow-x** [comment]
this one is fantastic https://mangasee123.com/

**Comment by henrik9999** [comment]
> this one is fantastic https://mangasee123.com/

use https://manga4life.com/ its the same site and already supported by malsync

**Comment by 8227846265** [comment]
Please add support for
https://manhuaus.com/

**Comment by mnabid** [comment]
Hi, can you add support for https://mangapill.com/ ?

**Comment by meotimdihia** [comment]
Please add support for comick.fun

https://github.com/MALSync/MALSync/issues/652

If you could, please add comick.fun to the database. When it is the same as Mangadex.

**Comment by Pancakes0** [comment]
Hello, please add support for isekaiscan.com 
my alt for md w/3,7k manga. tried mangatx/toonilynet but doesnt have them. thank you

**Comment by asilentdreamer** [comment]
Can you please add support for [Cubari.moe](https://cubari.moe) (previously known as guya proxy).
Almost every DISC thread on r/manga links to it now and it would be quite helpful to a lot of people if MAL-Sync supports it

**Comment by emanuelserpa** [comment]
dynasty-scans.com

**Comment by henrik9999** [comment]
We have decided to close the "Support for additional ..." issues because of them being unorganized and messy. If you still want your site to be added create a new issue (if there isnt already one, use the search) for it and use the website request template
