### ISSUE TITLE
[BUG] Background sync option randomly disables itself

### ISSUE THREAD

**Issue by rsmyst** [MALSync/MALSync#603]
**Describe the bug**
Over the past few months, this keeps happening regardless of browser being used. The background sync option disables itself sometimes when I look at the option :(
I have set it to enabled.

**Steps to reproduce the behavior:**
1. Set background sync to enable.
2. check back later after around 2-3 weeks maybe.

**Additional information:**
 - Edge Chromium currently. Was using Chrome and issue was there back then too. Both are on version 88.
 - Type: ??? Extension maybe?

**Comment by lolamtisch** [comment]
Did you change the default provider (mode) you sync to? Or did you clear the cache in the settings?

**Comment by rsmyst** [comment]
I didn't change the default provider... But i might've cleared the cache a few times. I definitely know this issue existed even in times when I didn't clear my tags. Till now, i might've cleared my tags max 4 times. But i've noticed this issue way more times.

**Comment by lolamtisch** [comment]
Clearing the cache disables the background sync

**Comment by rsmyst** [comment]
Ok cool. I'll remember that. Thanks.
