### ISSUE TITLE
[BUG] Serial theme is laggy and looks quite weird

### ISSUE THREAD

**Issue by rsmyst** [MALSync/MALSync#604]
**Describe the bug**
Wouldn't necessarily classify this as a bug but... The serial theme looks straight weird. The scroll bar scrolls fine for the first time but when you scroll it back the direction you had initially scrolled, it over laps and creates a white line in the entire scroll bar. 
My computer resource usage also ramps up crazily and the performance of the mal sync windows drops too :|

**Steps to reproduce the behavior:**
1. enable serial theme
2. Try it out?

**Additional information:**
 - Browser Edge chromium v88

**Comment by lolamtisch** [comment]
Scrollbars: This is a browser rendering bug. Lets hope they fix it someday.

everything else: Then get a better pc or dont use the theme XD

**Comment by rsmyst** [comment]
Oh. Alright. cool bro.
