### ISSUE TITLE
Add beta.crunchyroll.com

### ISSUE THREAD

**Issue by mackson888** [MALSync/MALSync#625]
Crunchyroll started testing their new website, link https://beta.crunchyroll.com/

**Comment by henrik9999** [comment]
Only 20% of the us premium users get access to it and we don't have it

**Comment by Tropixi** [comment]
> Only 20% of the us premium users get access to it and we don't have it
Yeah i'm in the 20% haha

**Comment by maxcutie** [comment]
@henrik9999 if you would like i can provide access to my account with beta
