### ISSUE TITLE
MALSync stopped working on gogoanime after domain change

### ISSUE THREAD

**Issue by ThunderArmy** [MALSync/MALSync#626]
**Describe the bug**
MalSync does not recognize any animes on https://gogoanime.ai/
My guess is that it's because of the domain ending change

**Steps to reproduce the behavior:**
Open an anime on gogoanime with the extension
**Additional information:**
 - Browser: Chrome

**Comment by henrik9999** [comment]
yeah its already added for the next release but you can add it yourself for now just go to the settings then custom domains click the + select gogoanime and add ```https://*.gogoanime.ai/*```

**Comment by ThunderArmy** [comment]
Alright, thank u
