### ISSUE TITLE
Voiranime (FR) no auto-update

### ISSUE THREAD

**Issue by Oreloth** [MALSync/MALSync#628]
**Describe the bug**
Player not detected on [Voiranime](https://voiranime.com/) so no auto-update on MAL.

**Steps to reproduce the behavior:**
Just try an episode, for exemple : [Assassins Pride - 03 VOSTFR](https://voiranime.com/anime/assassins-pride/assassins-pride-03-vostfr/)

**Additional information:**
 - Browser : [Maxthon 6.1.1.1000](https://fr.maxthon.com/) (Based on Chrome engine)
 - Type : Extension
 - Url : [Assassins Pride - 03 VOSTFR](https://voiranime.com/anime/assassins-pride/assassins-pride-03-vostfr/)

**Comment by henrik9999** [comment]
Player is getting detected, cant replicate this issue

**Comment by Oreloth** [comment]
I mean the bar at the bottom of the browser, [this one](https://gyazo.com/6096aff3782ed9aa1fc9d7869d2a57a4) don't progress with the video progression, so no auto-update on MAL, need to update manually for now. Tried it with Maxthon, Chrome and Firefox, same issue each time.

**Comment by lolamtisch** [comment]
Could you check with the new version? Or what player are you using?

**Comment by Oreloth** [comment]
Nothing at all on the page now, both players.

[Screenshot](https://i.gyazo.com/07d1e6b3061f234ed4006e51467a29a2.png)

**Comment by lolamtisch** [comment]
Are you sure the episode you are trying to watch is heigher than the one on mal. As malsync does nothing if it is not an increment.

**Comment by Oreloth** [comment]
Yes, I tried on others animes and I discovered same problem on [OtakuFR website](https://otakufr.co/episode/hajimete-no-gal-nc-08-vostfr/#player-1). MALSync is started, linked to the right page on MAL but autosync does not occurs. Tested on different animes and with different browsers. Still [this](https://gyazo.com/3a0cc363af16525e948e11d5c98d3d65) while episode is playing, need to update manually on both [Voiranime](https://voiranime.com/anime/hajimete-no-gal/hajimete-no-gal-08-vostfr/) and [OtakuFR](https://otakufr.co/episode/hajimete-no-gal-nc-08-vostfr/#player-1).

**Comment by lolamtisch** [comment]
I cant replicate that either. Do you set the permission for the extension manually? Seems like it can not inject itself into the player iframe. Does it work on pages like 9anime or twist.moe (player is not on seperate page so this should work either way).

**Comment by Oreloth** [comment]
Yes, it works on 9anime ( [Screenshot](https://i.gyazo.com/b7e6c34c2dc03d4be24bddf714e48505.png) ) and Twist.moe.
