### ISSUE TITLE
Gogoanime is no longer working with the extension

### ISSUE THREAD

**Issue by Retro8bit** [MALSync/MALSync#642]
**Describe the bug**
Not really a bug, but it looks like gogoanime (Which was previously supported) is no longer working with MALSync. I looked through the site access list in the extension's settings and could only find the domains that redirect to the .ai / .vc site, but not the actual .ai / .vc site.

**Steps to reproduce the behavior:**
Navigate to https://gogoanime.ai or to https://gogoanime.vc , pick a show thats on MAL and start watching. The extension should be tracking episodes and time watched, but it isnt.

**Additional information:**
 - Browser: Chrome
 - Type: Extension (I use uBlock Origin alongside MALSync) 
 - Url: https://gogoanime.ai AND https://gogoanime.vc
 
 
![image](https://user-images.githubusercontent.com/32439271/111093913-6e36fb00-8510-11eb-9924-1a48928c10b4.png)

![image](https://user-images.githubusercontent.com/32439271/111093482-70e52080-850f-11eb-8532-81d1872b7af7.png)

**Comment by farahnur42** [comment]
@Retro8bit You can add the domain to MALSync's custom domain section yourself https://github.com/MALSync/MALSync/wiki/Custom-Domains like so 
![image](https://user-images.githubusercontent.com/37258115/111094467-90a73380-8565-11eb-94f2-ae9f364d81e4.png). Otherwise you will have to wait for the next release.

**Comment by Retro8bit** [comment]
> @Retro8bit You can add the domain to MALSync's custom domain section [it's right next to the Websites button (where you can enable and disable MALSync per site from the pane) in the first section of MiniMAL's settings tab) yourself https://github.com/MALSync/MALSync/wiki/Custom-Domains like so
> ![image](https://user-images.githubusercontent.com/37258115/111094467-90a73380-8565-11eb-94f2-ae9f364d81e4.png). Otherwise you will have to wait for the next release.

Oh neat, thanks for the help. I got it to work
