### ISSUE TITLE
please add support for Animax.to

### ISSUE THREAD

**Issue by AEStudios** [MALSync/MALSync#643]
The website link is www.animax.to

**Comment by lolamtisch** [comment]
We don't want to support clones.

**Comment by AEStudios** [comment]
But doesn't Animax.to post their own videos on their own servers? 
And you added support for the scrapping sites and also Animesuge (which is basically a reskin). 
I don't understand what do you mean by Clones here

**Comment by lolamtisch** [comment]
I mean it is clearly a clone of kissanime. We difference between design and content clones.

What is the goal of a design clone? It is to confuse the user to think it is another page it is not. This is not cool in my book.

Content clones are not cool either, but they atleast dont try to decive people. If possible we try to not add them, but it is very difficult to tell and like nearly all pages scrapp in some way.

Animesuge is really a page we were not really confortable adding, but it got requested quite a lot.
