### ISSUE TITLE
Discord Rich Presence doesn't work correctly with multiple monitors (Needs focus).

### ISSUE THREAD

**Issue by Brasolis** [MALSync/MALSync#649]
The Discord Rich Presence add-on only works correctly when the browser window playing the media is in focus. If you are using a second monitor for browsing at the same time, [it loses focus and no longer works](https://i.imgur.com/TQm6gwp.png) . 

I'm not sure if this is something that can be fixed (Would it be possible to force all instances of the plugin to share the same information?) but it kind of defeats the purpose of the add-on at least for me.

**Comment by lolamtisch** [comment]
It is less of a technical limitation, more of conceptual one. 

There would be 2 solutions:
- Ping the active tab in the window that was last in focus.
- Ping the active tab in all open windows.

if it finds a presence display it. Problem with both of them is that you can not tell if you are actually using it or if it is just in the background doing nothing. This will result in presences beeing displayed all day long like `Browsing mangadex` if you have a tab open. And that kind of defeats the purpose of the addon even more.

**Comment by lolamtisch** [comment]
I think I came up with a solution. Just needs a bit more work. On top of the ping to all windows, the presences are aware themself if they are "active". Browsing mangadex for example would not be active, but a running video for example would be active. Reading a manga should not be active too, as you need focus to read the manga. I think this solution should work.

**Comment by Brasolis** [comment]
Thanks for your hard work!
