### ISSUE TITLE
When new anime episode is out mal-sync shows "Resume watching" button instead of "Continue watching" button

### ISSUE THREAD

**Issue by soredake** [MALSync/MALSync#664]
**Describe the bug**
When i finished ep1 of anime and new anime episode is out mal-sync shows "Resume watching" button pointing to ep1 instead of "Continue watching" button pointing to unwatched ep2.

**Steps to reproduce the behavior:**
![Untitled](https://user-images.githubusercontent.com/5204968/113481444-4cdb8600-94a2-11eb-97a1-bdcbecc7146e.png)

**Additional information:**
 - Browser: Firefox 87
 - Type: Extension
 - Url:

**Comment by lolamtisch** [comment]
That is the correct behavior. If the system does not know what the link to the next ep is, then it uses the ep of the last episode. The link to the next episode is saved while watching the episode, if the episode did not air yet then it does not know the link.

**Comment by soredake** [comment]
@lolamtisch can't mal-sync periodically check for new ep existence?

**Comment by lolamtisch** [comment]
Yes but that feature is leagazy, unreliable and slow. I discorage the usage of it. I don't see it as an solution anymore.
