### ISSUE TITLE
AniMixPlay tracking is inaccurate

### ISSUE THREAD

**Issue by LeeCrawshaw** [MALSync/MALSync#666]
Whenever I watch anything on AniMixPlay it consistently updates my list to episode 20 of whatever I'm watching at the start of an episode.

**Comment by henrik9999** [comment]
Send an example link where it happens

**Comment by LeeCrawshaw** [comment]
Sure, 
https://animixplay.to/v1/vinland-saga/ep3
https://animixplay.to/v1/hataraku-saibou-tv/ep5 - if the series has less than 20 episodes it just updates it to as many episodes as there are
https://animixplay.to/v1/boku-no-hero-academia-3rd-season

**Comment by henrik9999** [comment]
> Sure,
> https://animixplay.to/v1/vinland-saga/ep3
> https://animixplay.to/v1/hataraku-saibou-tv/ep5 - if the series has less than 20 episodes it just updates it to as many episodes as there are
> https://animixplay.to/v1/boku-no-hero-academia-3rd-season

sorry i cannnot reproduce this can you come and join our discord so we can talk there https://discordapp.com/invite/cTH4yaw

**Comment by LeeCrawshaw** [comment]
I've just given it a go on Chrome and I think it might just be me - I normally use Opera and it hasn't caused any issues with other sites, but seeing as it's fine on Chrome I can only assume that that it's Opera causing problems. Sorry for opening this issue.
