### ISSUE TITLE
MalSync no longer working on Safari Browser

### ISSUE THREAD

**Issue by CodexJeff** [MALSync/MALSync#668]
**Describe the bug**

No longer updates anime when watching Crunchyroll or any anime website. I use AniList. Using safari with Tampermonkey and MalSync version 0.8.7. Issue first observed about 4 days ago. Everything has worked properly before then. Screenshot is provided. 

**Additional information:**
 - Browser: Safari
 - Type: UserScript with Tampermonkey
 - Url: 
<img width="1257" alt="Screen Shot 2021-04-07 at 3 48 21 AM" src="https://user-images.githubusercontent.com/42257491/113830596-c7333100-9754-11eb-8afa-c0e99a18a80a.png">

**Comment by henrik9999** [comment]
Are you on the crunchyroll beta

**Comment by CodexJeff** [comment]
No, it doesn't work on other websites as well like 9anime and twist

**Comment by lolamtisch** [comment]
![image](https://user-images.githubusercontent.com/12599334/113834094-b7ceda80-978a-11eb-8857-f607369b0f3a.png)
Seems like the last tampermonkey update is long ago and the last MALSync update is 26 days ago. Safaris last update was on 2021-02-23. So theoretically there was no change in the last 26 days.

Tampermonkey sometimes get stuck tho. Try to restart everything, reinstall everything or try out older version of malsync.

**Comment by CodexJeff** [comment]
Reverting to 0.8.5 fixes it! Updating breaks it though

**Comment by lolamtisch** [comment]
0.8.5 is now 4 months old. Could you join our discord server as it is easier to debug like that, as none of us has macos.
https://discordapp.com/invite/cTH4yaw

**Comment by henrik9999** [comment]
waiting for tampermonkey developer to release the fix on safari

**Comment by Ghajik** [comment]
in order to get working with updated sites (like manganato) just copy the portions of the new code related to the site (in my case manganato) and replace with those of manganelo...
0.8.6 is the latest supported version for tampermonkey on safari

**Comment by lolamtisch** [comment]
Should be fine again
