### ISSUE TITLE
List Sync not working

### ISSUE THREAD

**Issue by Archimedes9500** [MALSync/MALSync#679]
I tried List Mirroring from AniList (Master) to MyAnimeList, both Anime and Manga, but every single entry just says `{ "code": 903, "message": "Update failed" } `
Checked a few MAL ID's and they are correct
Both sites are up too

 - Browser: Firefox android
 - Type: Extension

**Comment by lolamtisch** [comment]
The main Mal implementation is broken. We will replace it in the next update soon
