### ISSUE TITLE
Weird text in Permissions Prompt

### ISSUE THREAD

**Issue by AgrMohit** [MALSync/MALSync#688]
**Describe the bug**

There is some non-english text in a a permission prompt from MAL-Sync allow it on a number of sites
I trust MAL-Sync developers to not do anything malicious but this makes think a bit if this is a bug and could cause potential problems

**Steps to reproduce the behavior:**
Nothing. Most probably MAl-Sync auto-updated and asked me to grant new permissions required

**Additional information:**
 - Browser: Microsoft Edge Dev 91.0.852.0 on Windows 10 Pro 19042.928
 - Type: Extension
 - Url: URL does not matter for this
 
**Attached screenshot of Permission Prompt with the text**
![image](https://user-images.githubusercontent.com/32242258/115587505-662a6200-a2eb-11eb-8349-0045638b4259.png)

**Comment by lolamtisch** [comment]
These promts are from the browser to accept new permissions. We dont trigger or decide the text in them. We add new permissions in an update and it will automatically popup because of security reasons. Probably a problem of the edge dev build you are using.
