### ISSUE TITLE
MalSync no longer working on the Crunchyroll Beta

### ISSUE THREAD

**Issue by BubblemintEDM** [MALSync/MALSync#702]
I remember being able to use malsync on the crunchyroll beta (although it was kinda weird) but now it's gone entirely

 - Browser: Chrome
 - Type: Extension
 - Url: https://beta.crunchyroll.com/

**Comment by lolamtisch** [comment]
On my end it still works like it should. Could you join the discord server as it is easier to debug there.
https://discord.com/invite/cTH4yaw
