### ISSUE TITLE
[Website Request] Shiro

### ISSUE THREAD

**Issue by yusatial** [MALSync/MALSync#713]
## Website
- Name: Shiro
- Link: https://shiro.is/
- Language(s): English

**Comment by ty-coon** [comment]
@henrik9999 shiro is going to self host soon

**Comment by henrik9999** [comment]
> @henrik9999 shiro is going to self host soon

idc, nobody from the malsync team will add another gogoanime scraper if someone wants shiro on malsync he has to add it himself

**Comment by ty-coon** [comment]
@henrik9999 what did i said just now? Soon it will self host but i guess u r strongly opposing a new self host site.  👍🏻 Nvm.

**Comment by henrik9999** [comment]
> @henrik9999 what did i said just now? Soon it will self host but i guess u r strongly opposing a new self host site. 👍🏻 Nvm.

its still just a gogoscraper even if self hosted

**Comment by BubblemintEDM** [comment]
@henrik9999 the new v2 came out, most of the content is self hosted now. Gogo is just used as a backup source.

**Comment by ty-coon** [comment]
They already denied *even is self hosted* though the sources won't be gogo soon.

**Comment by BubblemintEDM** [comment]
@ty-coon yeah but you're automatically put on their servers now unlike before where they just put their own player over gogo, you have to manually select gogo in order to use that as your source

**Comment by ty-coon** [comment]
It only depends on the mal sync developer if they wanna add it, or someone else make it and pull request.

**Comment by BubblemintEDM** [comment]
I would do it but idk how 🤣

**Comment by ty-coon** [comment]
Same here

**Comment by ty-coon** [comment]
> > @henrik9999 shiro is going to self host soon
> 
> idc, nobody from the malsync team will add another gogoanime scraper if someone wants shiro on malsync he has to add it himself

i have created a pull request for shiro.... hope you accept it.
