### ISSUE TITLE
[Website Request] <GoGoAnime [Different source]>

### ISSUE THREAD

**Issue by Greeny127** [MALSync/MALSync#720]
## Website
- Name: GoGoAnime
- Link: gogoanime.app
- Language(s): English

## Other details
Currently, mal-synch does not work on this gogoanime version and I cannot seem to use the supported version.

**Comment by lolamtisch** [comment]
That is a fake, it is not the real gogoanime. This should be the real domains.
https://github.com/MALSync/MALSync/blob/master/src/pages/Gogoanime/meta.json#L3

**Comment by Greeny127** [comment]
Thank you for the insight, I'll check out the domains
