### ISSUE TITLE
I keep getting [MAL] Server Offline 

### ISSUE THREAD

**Issue by Bora72** [MALSync/MALSync#722]
**Describe the bug**
When I enter in a manga/anime page (usually manganelo and animepahe as those are what I use) the message appears, and then happens again in the proper entry of the manga/anime and in each chapter I watch. I can't use any of the features of the UI at this point. The UI keeps telling me to log in, no matter how many times I do that (this also happens with anilist, but in that case the anime info appears)

**Steps to reproduce the behavior:**
Enter in the list of the chapters of an anime or a manga (ex https://animepahe.com/anime/d01a94c3-83f5-2db7-77ab-84c2fe6a8a0a) or the specific chapter

**Additional information:**
 - Browser: <I use Brave, but I think it has a chromium base>
Oddly enough, I think the chapters get synchronized, so it throw me off even more
EDIT: It sorta fixed itself, I keep getting MAL server offline messages, but now it shows the shows info in the UI (minus images), also I'm logged in now, which is also odd. May as well put this as closed, I guess

**Comment by lolamtisch** [comment]
Difficult to tell. Could you join the discord it is a lot easier there to debug.

https://discord.com/invite/cTH4yaw
