### ISSUE TITLE
Info pop-up no longer updates to correct show.

### ISSUE THREAD

**Issue by Brasolis** [MALSync/MALSync#728]
The info pop-up refuses to update and show me info on the series I am browsing a page on. This used to happen occasionally and fix itself in time but now it seems to be hard stuck in this state. I have cleared the cache and disable/reenabled the addon but it is still stuck.

[Example of the stuck pop-up](https://i.imgur.com/NyNQAxt.gif)

I am unsure if this is just bugged on my end or something is wrong with the addon. Any help would be appreciated!

**Comment by Brasolis** [comment]
Actually I just realized it hasn't been updating anything since today. I just completely removed and re-added the extension but it still isn't doing anything.

**Comment by Brasolis** [comment]
Another edit, it is working on other sites but not at all on crunchyroll.

**Comment by alltimemarr** [comment]
I have the same issue.

I'm on Chrome, MacOS. All sites work, but Crunchyroll.

Did you fix it yourself, and how? As your closed this issue yourself?

**Comment by lolamtisch** [comment]
@alltimemarr 

Crunchyroll did change some things completly breaking the current implementation. Will be fixed with the next release.

The Crunchyroll beta for the new website still works.

**Comment by alltimemarr** [comment]
Thanks for this quick reaction!

I've don't think I ever used the beta before, so I wanted to give it a shot, but it redirects me to https://www.crunchyroll.com/?beta_optout=1. Maybe it's only for paid members? Or perhaps I opted out once in the beginning if it didn't work for me or something.. :(a

**Comment by lolamtisch** [comment]
@alltimemarr It is Us exclusive. But I somehow got it after using a VPN for a bit. Release is planned for end of the week.
