### ISSUE TITLE
No longer auto updating progress

### ISSUE THREAD

**Issue by weirdoboy2112** [MALSync/MALSync#733]
MALSync has randomly decided to stop auto updating episode progress through a show and no longer displays a continue watching button on MAL

**Comment by farahnur42** [comment]
@weirdoboy2112 Which site? If it's Gogoanime, 9anime or Crunchyroll then it's a known issue and you'll just have to wait for the next release. There are workarounds for the time being for the first two in the MALSync Discord server, so that's an option as well.

**Comment by weirdoboy2112** [comment]
It's 9anime. If it's a known issue I'll patiently wait for it to be fixed :)

**Comment by farahnur42** [comment]
@weirdoboy2112 This is all you need to do to fix 9anime (so the workaround is a lot less annoying than with Gogo) 
![image](https://user-images.githubusercontent.com/37258115/119411479-5055f580-bd0c-11eb-9989-cf09db18c86c.png)
