### ISSUE TITLE
[BUG] Skip opening shortcut doesn't work on 9anime.to

### ISSUE THREAD

**Issue by rsmyst** [MALSync/MALSync#737]
**Describe the bug**
As title says. it works on other sites likes animepahe but doesn't work on 9anime since a few days.

**Steps to reproduce the behavior:**
Open an anime in 9anime. 
Use any shortcut.

**Additional information:**
 - Browser: Edge chromium 
 - Type: Mal extension?
 - Url: 9anime.to

**Comment by fseipel** [comment]
Duplicate of #733

**Comment by lolamtisch** [comment]
Duplicate of #733
