### ISSUE TITLE
Anime Auto Sync not working in some sites. 

### ISSUE THREAD

**Issue by baldjy** [MALSync/MALSync#740]
**Describe the bug**
It's been a while that the auto sync for anime stopped working on Crunchyroll and Funimation (at least for me and a friend of mine).  

At first I thought it was something related to how bad Funimation is but since it stopped working on Crunchyroll too recently I decided it was better to report it. It still works on Yugen Anime (Screenshot below) which makes me think it might be something related to other regions of Crunchyroll and Funimation (I'm Brazilian, so the /pt-br/ might crash something?)

Please let me know if I can help in any way for debugging or testing or whatever.

![image](https://user-images.githubusercontent.com/8379062/120011169-638aee80-bfb4-11eb-9123-c2d7b7af3ca4.png)

**Steps to reproduce the behavior:**
There's no much steps, when I enter the anime on Crunchyroll or Funimation I don't get the under tab neither the auto sync.
**Additional information:**
 - Browser: I'm using Chrome 90.0.4430.212 
 - Type: Extension 0.8.9
 - Url: I used https://www.crunchyroll.com/zombie-land-saga/episode-8-the-saga-incident-part-1-810976 and https://yugenani.me/watch/1377/pokemon-2019/67/ for the testing while writing this up.

**Comment by henrik9999** [comment]
crunchyroll is currently broken and funimation was removed in the last release. Both will be fixed/readded in the next release
