### ISSUE TITLE
Add Animesuge.io   in anime overview sites you can watch it on section please!!!

### ISSUE THREAD

**Issue by Pranav-uchiha** [MALSync/MALSync#746]
please add animesuge.io in the anime overview sites section it would be really helpful and convenient  i find it really annoying to go and search it up again and again. instead i could have used MALSync to just redirect me there in one click but unfortunately Animesuge.io is not there in the list anywhere,  So if you could do  just this much it would be really helpful!!!!! thank you!!
![Mal-Sync 6_2_2021 4_18_44 PM](https://user-images.githubusercontent.com/84614630/120467901-3f694c00-c3be-11eb-9b57-4b87d1e51299.png)

**Comment by henrik9999** [comment]
Won't be added. Also animesuge is just a 9anime scraper so you could just use that page

**Comment by Pranav-uchiha** [comment]
> Won't be added. Also animesuge is just a 9anime scraper so you could just use that page

ok i understand,   but is zoro.to possible?

**Comment by henrik9999** [comment]
> > Won't be added. Also animesuge is just a 9anime scraper so you could just use that page
> 
> ok i understand, but is zoro.to possible?

Zoro will be added to it in the next release
