### ISSUE TITLE
Mal-Sync for Android FF

### ISSUE THREAD

**Issue by pablo3x6** [MALSync/MALSync#751]
Since Android Firefox now supports extensions, Mal-Sync could be adapted to work on it. Would be a great asset, since some popular android apps which allowed streaming got killed.

**Comment by lolamtisch** [comment]
It is impossible to get into the accepted android extensions. I think there are less than 20 in total. But it is possible to sideload extensions in android Firefox Nightly. 
Id:13616310
name:MALSync
https://www.androidpolice.com/2020/09/30/firefox-for-android-brings-back-general-extensions-support-heres-how-to-set-it-up/
