### ISSUE TITLE
[Website Request] Bring MALSync back for Mangadex.org

### ISSUE THREAD

**Issue by Karma2424** [MALSync/MALSync#753]
## Website
- Name: Mangadex
- Link: mangadex.org
- Language(s): English

**Comment by henrik9999** [comment]
Lh ist in #690

**Comment by Karma2424** [comment]
@henrik9999 thanks for your fast support

**Comment by Mrfiregem** [comment]
Note that there's no desktop UI yet, just mobile which is currently used for both.
