### ISSUE TITLE
Add a bottom to change the page where you can continue watching the manga

### ISSUE THREAD

**Issue by JacksonSan009** [MALSync/MALSync#761]
I don't know if this also happen with the anime pages, but in the mangas pages I am unable to change the page where I'm watching it. So if I don't like the front end of a page, like the page don't have continues scroll reading, and I want to change of page, I can't because there's no way to change the page, who the system automatically changed him self.

![mangasee123](https://user-images.githubusercontent.com/51487793/121313929-7f539600-c8cc-11eb-965e-959049396953.png)
![MangaFox](https://user-images.githubusercontent.com/51487793/121314002-92666600-c8cc-11eb-9c1c-354675a00d31.png)

**Comment by JacksonSan009** [comment]
The application change of source after 3 episodes, who I have to update manually.

**Comment by lolamtisch** [comment]
Yeah after updating it once on the page of the new source it will switch to that page.

**Comment by JacksonSan009** [comment]
But it doesn't update immediately

**Comment by lolamtisch** [comment]
Yes after reading one chapter it immediately switches.

**Comment by JacksonSan009** [comment]
ok
