### ISSUE TITLE
Not working since 4 weeks ago

### ISSUE THREAD

**Issue by ayyneya** [MALSync/MALSync#767]
Hi, sorry to bother.

Since 4 weeks back it hasn't been syncing for me to anilist.co from crunchyroll & 9anime at all.
I tried re-authenticating, clearing cookies, new browsers, etc. It also doesn't work on my second laptop.

Is there anything else I could try to make it work again? 

Tyvm.

**Comment by henrik9999** [comment]
I think it will be hard to debug this on GitHub so please join the discord if you can https://discord.gg/cTH4yaw
