### ISSUE TITLE
Not working with JellyFin.

### ISSUE THREAD

**Issue by mclarence** [MALSync/MALSync#769]
**Describe the bug**
There does not seem to be any indication that mal sync is doing anything when playing an anime through JellyFin. 

On the right of the screenshot, you can see plex and the mal sync pop ups and hamburger button on the bottom right. On the left is JellyFin and I don't see anything like what is happening on Plex..
![image](https://user-images.githubusercontent.com/25338414/122336646-83447f80-cf80-11eb-9c37-b0c028c7fb0e.png)

**Steps to reproduce the behavior:**
1. Add JellyFin custom domain to MAL-Sync custom domain settings. Approve changed permission popup on chrome.
![image](https://user-images.githubusercontent.com/25338414/122337086-2eedcf80-cf81-11eb-9c11-d991a035466d.png)

2. Check if an "Anime" genre is set on the series. 
![image](https://user-images.githubusercontent.com/25338414/122337050-1aa9d280-cf81-11eb-81b2-554ade0e2179.png)

3. Play an anime series through JellyFin.
4. Mal sync is not working.

**Additional information:**
 - Browser: Chrome 91.0.4472.106 
 - Type: Chrome Extension
 - Url: https://jellyfin.mycustomdomain.xyz.
 - JellyFin version: 10.7.5 running as a docker container in unraid.

**Comment by lolamtisch** [comment]
Try adding the custom domain thing with a / in the end.
`https://jellyfin.mycustomdomain.xyz/`

**Comment by mclarence** [comment]
No differnce with the / at the end.

**Comment by lolamtisch** [comment]
If you open the console (f12 and then the console tab). Do you see a big malsync log on the top?

Could you join the discord as it is easier to debugg things there.
https://discord.com/invite/cTH4yaw

**Comment by lolamtisch** [comment]
Use correct metadata endpoint to get genres:
`Items?ids=e805f5b115d4475b8a5b0eaa3c02c0b1` -> `Items\e805f5b115d4475b8a5b0eaa3c02c0b1`
And check the folder name if includes Anime as a fallback
