### ISSUE TITLE
the video player functions aren't working

### ISSUE THREAD

**Issue by Pranav-uchiha** [MALSync/MALSync#771]
the video player functions dont work like the: auto fullscreen mode, open next episode shortcut, skip intro shortcut etc.

(and yess i have checked the shortcuts are unique for each function and are not same)

**Comment by lolamtisch** [comment]
What page are you using?

**Comment by Pranav-uchiha** [comment]
zoro.to

**Comment by Pranav-uchiha** [comment]
i checked it and it worked fine on other pages  like animixplay.to and others but doesn't work on zoro.to

would be reall nice and helpful if you could fix this problem.  thanx!

**Comment by lolamtisch** [comment]
The next release will still need a few weeks. But there is a workaround:
> **Vidcloud video Iframe on zoro not detected (Extension only)**
> 
> You will need to add the custom domain like below. There is a button Custom Domains in the settings. You possibly need to restart the browser afterwards.
> 
> **Video Iframe** -> `https://vidcloud.one/`
> 
> Wiki: https://github.com/MALSync/MALSync/wiki/Custom-Domains

**Comment by Pranav-uchiha** [comment]
so do i just paste  (https://vidcloud.one/) this?

**Comment by lolamtisch** [comment]
Yes could be that you need to restart the browser.
https://media.discordapp.net/attachments/849673647824175164/854293939333758986/unknown.png

**Comment by Pranav-uchiha** [comment]
k thanx

**Comment by Pranav-uchiha** [comment]
btw any can you give any idea when's the nest release on?

**Comment by lolamtisch** [comment]
We did a release last week and we need to wait a few weeks not annoy the users. We normally do one once a month if there is nothing major breaking.
