### ISSUE TITLE
AnimeSimple links in Firefox have wrong URL

### ISSUE THREAD

**Issue by sorashi** [MALSync/MALSync#773]
**Describe the bug**
Clicking an AnimeSimple link opens the link with `moz-extension://` protocol instead of `http(s)://`.

**Steps to reproduce the behavior:**
- Open the extension
- Find an anime
- Click the link to watch it on animesimple
- New tab opens with the wrong link, for example `moz-extension://ww1.animesimple.com/series/253-puella-magi-madoka-magica-anime.html`

**Additional information:**
 - Browser: Firefox 89.0.1
 - Type: Extension

**Comment by sorashi** [comment]
I looked into it and the problem is with the json data on the website, for example

```json
{ "...": "...",
 "series_url":"//ww1.animesimple.com/series/253-puella-magi-madoka-magica-anime.html",
 "...": "..." }
```
This is a [protocol-relative URL](https://en.wikipedia.org/wiki/URL#Protocol-relative_URLs). Firefox extensions have moz-extension:// protocol and thus redirect relatively to it.

Relevant file: [AnimeSimple/main.ts](https://github.com/MALSync/MALSync/blob/8a51f41e6ea2efe84b13c9ac116bb543943c2b49/src/pages/AnimeSimple/main.ts).

**Comment by henrik9999** [comment]
Yes I know I already talked with them

**Comment by henrik9999** [comment]
Is fixed now. The urls could still be cached on your end and maybe only will update once you watch another episode
