### ISSUE TITLE
[Bug] MALSync is not working on asurascans

### ISSUE THREAD

**Issue by Karma2424** [MALSync/MALSync#777]
**Describe the bug**
MALSync is stuck on loading

**Steps to reproduce the behavior:**
visit https://www.asurascans.com/comics/the-max-level-hero-has-returned/
and when you open MALSync and click on bookmarks it show this error
SyntaxError: Unexpected token u in JSON at position 0autorenew

**Additional information:**
 - Browser: chrome
 - Type: Userscript
 - Url: https://www.asurascans.com/comics/the-max-level-hero-has-returned/

**Comment by lolamtisch** [comment]
Do you use an vpn. Myanimelist blocks some vpn ips. Can you access this?
https://api.myanimelist.net/v2

**Comment by Karma2424** [comment]
@lolamtisch If go to https://api.myanimelist.net/v2 it show me {"message":"","error":"not_found"}

**Comment by lolamtisch** [comment]
I have no problem. Just try clearing the cache there in the settings. And i dont know why asurascans specially would make problems there.

**Comment by Karma2424** [comment]
@lolamtisch after clearing cache its working now thanks and do you any plans to add any feature to combine multiple mangas of same name stored on locally instead of having multiple mangas of same name on ever different website

**Comment by lolamtisch** [comment]
Just because it has the same name it does not mean it is the same manga, so we changed it to per page.

**Comment by Karma2424** [comment]
@lolamtisch cant you make it so i can manually combine multiple mangas when selected and add a prompt to make sure because my manga bookmarks are getting really clustered

**Comment by Karma2424** [comment]
and also most the manga sites have author name so you can compare if the manga is same or not

**Comment by lolamtisch** [comment]
Just because it has the same author it does not mean it is the same manga. 
It would shoot the complexity to the moon with references between entries and don't even get why this is needed. Just delete the old entry.
I would recommend to just switch to anilist as they have more manga entries.

**Comment by Karma2424** [comment]
@lolamtisch no i face the same issue with anilist to

**Comment by Karma2424** [comment]
@lolamtisch sorry for the late respond

**Comment by lolamtisch** [comment]
Can you join the discord it is easier to debugg there.
https://discord.com/invite/cTH4yaw

**Comment by Karma2424** [comment]
@Karma2424 yes sure
