### ISSUE TITLE
Player not detected

### ISSUE THREAD

**Issue by Prixix** [MALSync/MALSync#786]
**Describe the bug**

The video player is not beeing detected at anime-shitai.com.

**Steps to reproduce the behavior:**

1. Go to anime-shitai.com
2. Pick any anime
3. Click any episode

**Additional information:**
 - Browser: Chrome
 - Type: Extension
 - Url: https://www.anime-shitai.com/

**Comment by lolamtisch** [comment]
Please post a link to an Episode that does not work.

**Comment by Prixix** [comment]
> Please post a link to an Episode that does not work.

https://www.anime-shitai.com/anschauen/368/fairy-tail-ger-sub/folge-308/StreamtapeE#stream

**Comment by lolamtisch** [comment]
Could you join the discord to debug it together?
https://discord.com/invite/cTH4yaw

**Comment by Prixix** [comment]
Funnily enough it now works... I didn't do anything so I guess it's fixed 😎
