### ISSUE TITLE
Sort unread manga to the top in the extension popup

### ISSUE THREAD

**Issue by IntermittentlyRupert** [MALSync/MALSync#811]
I'd like to be able to filter my Reading list to show manga with available chapters I haven't read.

I've written myself a [rudimentary userscript](https://gist.github.com/IntermittentlyRupert/a709e8c9908d55a44e24a1c44786509c) to do this on Anilist, but it's very slow and clunky. It seems like MALSync would probably be able to do this without all the scrolling and timeouts.

![image](https://user-images.githubusercontent.com/4526480/128590506-f4bf7a95-cbd7-45e6-8938-5aedaf1163d1.png)

**Comment by lolamtisch** [comment]
The default sorting on the reading list in the extension popup always sorts entries with unread chapters to the top.

**Comment by IntermittentlyRupert** [comment]
Gonna be honest, I always find the popup super buggy on Firefox, so I never use it.

Just checked and it seems to be working for anime but not for manga.

![image](https://user-images.githubusercontent.com/4526480/128591016-55b990e1-2235-47df-b7b1-2b80f0eb3bcf.png)

**Comment by lolamtisch** [comment]
I see you have a small screen. Unfortunately that scrolling issue is not fixable as Firefox does that without we having control on it. I recommend checking in the settings the option "open in separate window" or use https://malsync.moe/pwa , there you should not have that scrolling issue.

In the screenshot I see that you are not using the default sorting and instead the latest update sorting. (The button with the clock). But I am not sure if I disabled it for Mangas as it would confuse more than help there. I currently can't check as not at home, but will look into it in the next few days.

**Comment by IntermittentlyRupert** [comment]
> I see you have a small screen.

This screenshot is very cropped - it's a 4k display (with 125% UI scaling). That's just how big the popup opens. I had a play with the settings and it looks like the height/width aren't respected for the popup. It does respect them when opening in a separate window.

> In the screenshot I see that you are not using the default sorting and instead the latest update sorting.

Oops, that's my mistake. That said, "Default" seems to produce the same ordering as "Last Updated", so it seems like it probably is disabled.

**Comment by lolamtisch** [comment]
Current plan:
For the default sorting we will put mangas with less than unread 5 chapters on top and keep the last updated order below.
Additionaly we are going to add an option to sort by accending unread chapter number where entries that are on the most recent release are bellow.
