### ISSUE TITLE
The shortcuts keys are not working!

### ISSUE THREAD

**Issue by Pranav-uchiha** [MALSync/MALSync#815]
the shortcuts keys in malsync are not working like to skip intro(80 sec's), jump to new episode, jumb back one episode.
the short-cut keys that are set are all different i have checked but it still doesn't work whenever try

please help me, if this problem is fixed it would be a huge help, as these short-cuts were really helpful, but now that they are not working its really a pain in the ass.

**Additional information:**
 Browser: chrome , microsoft edge
 Type: extension

**Comment by lolamtisch** [comment]
What page are you using?

**Comment by Pranav-uchiha** [comment]
zoro.to

**Comment by lolamtisch** [comment]
> **RapidStream video Iframe on Zoro not detected (Extension only)**
> 
> You will need to add the custom domain like below. There is a button Custom Domains in the settings. You possibly need to restart the browser afterwards.
> 
> **Video Iframe** -> `https://rapid-cloud.ru/`
> 
> Wiki: https://github.com/MALSync/MALSync/wiki/Custom-Domains
![image](https://user-images.githubusercontent.com/12599334/129157993-88c3610a-1ec4-40c5-ab0e-e9f3f3645e35.png)

**Comment by Pranav-uchiha** [comment]
but thanx it did fix the problem
