### ISSUE TITLE
Support for tracking on Openvideo player

### ISSUE THREAD

**Issue by BubblemintEDM** [MALSync/MALSync#816]
Would be nice to see, it's an extension that replaces the player on some sites with its own to avoid ads.

https://chrome.google.com/webstore/detail/openvideo-%E2%80%93-ad-free-strea/dadggmdmhmfkpglkfpkjdmlendbkehoh

**Comment by lolamtisch** [comment]
I recommend to just use an adblocker like ublock origin if you dont want ads.
We wont add it officially but you can always add the player in the custom domain section in the settings.
`Video Iframe` -> `https://openvideo-streaming.github.io/`


![image](https://user-images.githubusercontent.com/12599334/129337432-bc71776a-6b13-4efd-b1f0-886dd2ba9ffb.png)
