### ISSUE TITLE
clicking on episode goes to the wrong site.

### ISSUE THREAD

**Issue by jamm00** [MALSync/MALSync#840]
**Describe the bug**

When you go to watch an episode on https://animepahe.org/ using Mal-Sync
anime link it takes you to https://pahe.win/.

**Steps to reproduce the behavior:**
pick any anime you want then go to the list to watch it on animepahe and it will take you to https://pahe.win/.

**Additional information:**
 - Browser: 
 - Edge, Firefox, chrome
 - 
 - Type: 
 - Url: https://animepahe.org/, https://pahe.win/

**Comment by lolamtisch** [comment]
The page is currently down. Just wait until they fix it.

**Comment by mapuya19** [comment]
@lolamtisch They actually changed domains, so it may require a fix: https://animepahe.ac/

**Comment by henrik9999** [comment]
> @lolamtisch They actually changed domains, so it may require a fix: https://animepahe.ac/

.ac is fake

**Comment by mapuya19** [comment]
Thanks for the clarification!

**Comment by unreallimits** [comment]
The page itself is fine. Its the links that are broken. You can go to https://animepahe.com and see there is nothing wrong with their site. MalSync just sends you to a site that doesn't exist at all. Maybe they changed the domain and that broke what MalSync is trying to link to but the site itself works flawlessly. I get that it says won't fix but if you wont fix it than remove it.

**Comment by lolamtisch** [comment]
@unreallimits They officially annouced they wont fix pahe.win. This means links will stay broken as animepahe has no permament link urls. This means there is no fix for this as it is intended to be like this by animepahe.

**Comment by henrik9999** [comment]
i made this userscript that fixes it for now https://greasyfork.org/scripts/432078-animepahe-bookmark-url-fixer

**Comment by jamm00** [comment]
> i made this userscript that fixes it for now https://greasyfork.org/scripts/432078-animepahe-bookmark-url-fixer

Thank you for this, it works great.
