### ISSUE TITLE
Zoro.to - Player not detected  - aksing to update manually everytime

### ISSUE THREAD

**Issue by sandeep9999** [MALSync/MALSync#843]
**Describe the bug**

**Steps to reproduce the behavior:**

**Additional information:**
 - Browser: 
 - Type: 
 - Url:

**Comment by henrik9999** [comment]
RapidStream video Iframe on Zoro not detected (Extension only)

You will need to add the custom domain like below. There is a button Custom Domains in the settings. You possibly need to restart the browser afterwards.

Video Iframe -> https://rapid-cloud.ru/

Wiki: https://github.com/MALSync/MALSync/wiki/Custom-Domains
