### ISSUE TITLE
Skip not working on gogoanime after last update

### ISSUE THREAD

**Issue by mbahArip** [MALSync/MALSync#849]
**Describe the bug**
After latest update, skip function and auto update after xx% vid progress to mal stopped working.
and it show "can't find player" error on bottom of the page.
I'm using vidstreaming on mal.

**Additional information:**
 - Browser: Chrome
 - Type: Extension

**Comment by henrik9999** [comment]
Vidstreaming video Iframe on Gogoanime not detected (Extension only)

You will need to add the custom domain like below. There is a button Custom Domains in the settings. You possibly need to restart the browser afterwards.

Video Iframe -> https://streamani.io/

Wiki: https://github.com/MALSync/MALSync/wiki/Custom-Domains
