### ISSUE TITLE
MalSynch does not work on gogoanime.vc and gogoanime.pe

### ISSUE THREAD

**Issue by Greeny127** [MALSync/MALSync#850]
**Describe the bug**
Doesn't detect video player, controls such as skip opening, move to next episode etc don't work.

**Steps to reproduce the behavior:**
Go to gogoanime.vc, select any anime, and watch, won't detect video player

**Additional information:**
 - Browser: chrome
 - Type: Extension
 - Url: gogoanime.vc

**Comment by lolamtisch** [comment]
#849
