### ISSUE TITLE
Animeshouse.net - Player not detected - asking to update manually everytime

### ISSUE THREAD

**Issue by K0rby** [MALSync/MALSync#851]
**Describe the bug**

Title says everything

**Steps to reproduce the behavior:**

**Additional information:**
 - Browser:  Chrome
 - Type:  Extension
 - Url: https://animeshouse.net/

**Comment by lolamtisch** [comment]
Video Iframe on animeshouse not detected (Extension only)

You will need to add the custom domain like below. There is a button Custom Domains in the settings. You possibly need to restart the browser afterwards.

Video Iframe -> https://animeshouse.net/playerBlue/
Video Iframe -> https://player3.animeshouse.net/mp4/
Video Iframe -> https://nezuko-ah.nl/

Wiki: https://github.com/MALSync/MALSync/wiki/Custom-Domains
