### ISSUE TITLE
auto picture in picture? {feature request}

### ISSUE THREAD

**Issue by stapuft** [MALSync/MALSync#852]
hi, its been a while, lol, thanks for the amazing extension, it works AMAZINGLY, as usual.
i was trying to make a userscript to auto enter picture in picture mode when i play a video, kinda like i did with making it fullscreen (with additional keyboard shortcuts) a few years ago, that you guys made better, and implemented in the extension, cuz you guys are awesome......anyway, im stumped, i cant for the life of me get it to work, maybe it just cant, or maybe im missing something important....i already deleted my script out of frustration, or id paste it here, instead here's the api for PIP
https://developer.mozilla.org/en-US/docs/Web/API/Picture-in-Picture_API

but an amazing feature for mal-sync would be a toggle, nested in the "auto fullscreen" option, that if "auto fullscreen" is enabled, it then asks if you want it to be PIP or not with a secondary toggle.  i mean the PIP has many great uses/features like it being on a secondary monitor/TV, while you browse the comments on your main screen, as well as it being "always on top" means it cant get blocked or hidden by anything that could interrupt your experience.

thanks for humoring me, have a great day.

**Comment by lolamtisch** [comment]
I am not sure, but I think we can not track the player in PIP mode. So that would not be a think for MAL-Sync.

I can imagine PIP can only be startet if the user triggers it with a button. Auto is probably not possible. But you could try setting this option.
![image](https://user-images.githubusercontent.com/12599334/133039406-79359a51-430c-485f-b999-83dae834c1a6.png)

**Comment by stapuft** [comment]
in PIP mode the original player is still there and working like it always has, all PIP does is....hijack the video, for lack of a better word, if you ever use it, you notice the original players time and controls all still function as intended, and although i do enter it manually, mal-sync hasn't had any problems with tracking what i have been watching, or remembering where i left off at.

also i tried injecting that into the page and it basically mad PIP worthless lol, when you switch programs, or tabs it pauses the video, and sometimes exits PIP mode altogether.
