### ISSUE TITLE
YugenAnime no longer syncs - new domain name

### ISSUE THREAD

**Issue by PhilAnders** [MALSync/MALSync#855]
**Describe the bug**
YugenAnime changed their domain name, and MALsync no longer works properly.
i.e. episode progress does not update.
Please add website domain https://yugen.to/

**Steps to reproduce the behavior:**
Watch any anime on YugenAnime and see that it does not sync

**Comment by lolamtisch** [comment]
> **Yugenani domain change (Extension only)**
> 
> You will need to add the custom domain like below. There is a button Custom Domains in the settings. You possibly need to restart the browser afterwards.
> 
> **YugenAnime** -> `https://yugen.to/`
> **Video Iframe** -> `https://yugen.to/e/`
> 
> Wiki: https://github.com/MALSync/MALSync/wiki/Custom-Domains
![image](https://user-images.githubusercontent.com/12599334/133573675-c8eb3a20-c277-4a80-8c88-625ddfdf1981.png)

**Comment by PhilAnders** [comment]
Thank you.
I was unaware I could add it myself.

Problem solved

**Comment by GaganRohith** [comment]
@henrik9999 i have added the domain in custom domains even then control + right is not working

![2](https://user-images.githubusercontent.com/72659340/133731444-9b1c69e6-cbd6-482c-9de1-2b200842535e.png)
