### ISSUE TITLE
animixplay.to - Player not detected

### ISSUE THREAD

**Issue by soredake** [MALSync/MALSync#856]
**Describe the bug**
New domain `https://v.cdnmix.org/` appeared and mal-sync does not know about it yet.

**Steps to reproduce the behavior:**

**Additional information:**
 - Browser: Firefox
 - Type: Extension
 - Url: https://animixplay.to/

**Comment by lolamtisch** [comment]
Do you have an example?

**Comment by soredake** [comment]
> 
> 
> Do you have an example?

<details>
<summary>Example iframe url</summary>

https://v.cdnmix.org/p/player.html#aHR0cHM6Ly92LnZydi5jby9ldnMxL2E2ZDQ4ZTM3NjIwOWNjMWU2MDEzMGIwMTVkYTVhYmY1L2Fzc2V0cy81OTliZmQ0NjM0ZTljNTA4MDMxMjBjMTA4ZTgxOTQxOF8sNDE1OTA5OS5tcDQsNDE1OTEwMC5tcDQsNDE1OTA5OC5tcDQsNDE1OTA5Ny5tcDQsNDE1OTA5Ni5tcDQsLnVybHNldC9tYXN0ZXIubTN1OD9Qb2xpY3k9ZXlKVGRHRjBaVzFsYm5RaU9sdDdJbEpsYzI5MWNtTmxJam9pYUhSMGNDbzZMeTkyTG5aeWRpNWpieTlsZG5NeEwyRTJaRFE0WlRNM05qSXdPV05qTVdVMk1ERXpNR0l3TVRWa1lUVmhZbVkxTDJGemMyVjBjeTgxT1RsaVptUTBOak0wWlRsak5UQTRNRE14TWpCak1UQTRaVGd4T1RReE9GOHNOREUxT1RBNU9TNXRjRFFzTkRFMU9URXdNQzV0Y0RRc05ERTFPVEE1T0M1dGNEUXNOREUxT1RBNU55NXRjRFFzTkRFMU9UQTVOaTV0Y0RRc0xuVnliSE5sZEM5dFlYTjBaWEl1YlROMU9DSXNJa052Ym1ScGRHbHZiaUk2ZXlKRVlYUmxUR1Z6YzFSb1lXNGlPbnNpUVZkVE9rVndiMk5vVkdsdFpTSTZNVFl6TVRrME1EQTRNWDE5ZlYxOSZTaWduYXR1cmU9aThYcEE3eHJUZUJCUzFNUEctLXVKVTZSNzFWMVNJSWFlR0VqYm1QMzdEYUtwbmlaQTlwUmZzZUxGcWNsQTgyWTdGVkNiN3I4NllVSnRmZ0J3Uk5WMmhrSUpRd1FoUUJRUWhKc2VjZzEtaE1sVkY4WUtSWENmc2tOb2VRYWVaa3ZVMXlZNGtGNURsR2g0NFFWMExEUEhOaFF5WEZRMDVmVmg5SlBORzIydzVKVUx0eWZDSE9LTWk4dWZTY1R5amtXcS11cS00RTVMZm55NC1PVmNxUnR3V3Z3OXJyMTl1QmlDQWVndWhnMzBrZnJYcFdyODlCV1FKOVJpa3BmSW12UjYzbFZpblpqSU9NMHJ6eXNzNmx2S3NJNFdrMmFKcGFOZVA5OXU5aHpuellJdGlHWVZUbjZHZXp6dURGfnhDT2M2RjRMZGtiV0NCWjBRelNWQkU3LS1RX18mS2V5LVBhaXItSWQ9QVBLQUpNV1NRNVM3WkIzTUY1VkE=#uid=MTcwNTAz

</details>
