### ISSUE TITLE
Control + right not skipping 85 secs as usual in new YugenAnime Domain

### ISSUE THREAD

**Issue by GaganRohith** [MALSync/MALSync#878]
**Describe the bug**
not able to skip opening using control + right it is skipping 170 seconds i have it set to 85 in settings

Steps to reproduce the behaviour:
open any anime episode on https://yugen.to/?ref=yugenani.me
and use combination of control + right 

Additional information:

**Browser:** chrome
**Type:** Extension
**Url:** https://yugen.to
![1](https://user-images.githubusercontent.com/72659340/133725118-d5e21859-eacd-4253-bfbb-183a4bc30718.png)

**Comment by henrik9999** [comment]
Duplicate #855
