### ISSUE TITLE
Control + Right skipping double the time set in the extension

### ISSUE THREAD

**Issue by GaganRohith** [MALSync/MALSync#891]
**Describe the bug**
I have added the new yugenanime domain to custom domains and started using it but I noticed that when I press control+right it skips 170 seconds instead of the value set = 85
please see the screen shots below

**Steps to reproduce the behaviour:**
add the new yugenanime to custom domains
open https://yugen.to/
open any episode 
play an episode 
press control + right it skips double the time set

**Additional information:**
 - Browser: chrome
 - Type:Extension
 - Url: https://yugen.to/

![1](https://user-images.githubusercontent.com/72659340/133966898-ad55e473-db56-45cc-bd89-c09659b5dc10.png)
![2](https://user-images.githubusercontent.com/72659340/133966902-9860c44a-30c7-4d9c-bad0-75e282addd02.png)

**Comment by lolamtisch** [comment]
Should fix itself with the next release.

**Comment by GaganRohith** [comment]
thank you
