### ISSUE TITLE
MalSync no longer works on MangaPark 

### ISSUE THREAD

**Issue by adryan475** [MALSync/MALSync#896]
**Describe the bug**

MalSync has been functioning as intended on Mangapark for more than a year now. Currently MalSync detects the manga and provides the relevant data for it on minimal but does not update the entry. Not sure if its related but minimal keeps displaying a message saying "Rate Limited"
**Steps to reproduce the behavior:**

**Additional information:**
 - Browser:  Chrome
 - Type:  Extension
 - Url:https://mangapark.net/

**Comment by lolamtisch** [comment]
Going to fix it in the next release
