### ISSUE TITLE
Syncing a Manhwa with a similar name to a manga in Flame Scans

### ISSUE THREAD

**Issue by GhostUnamused** [MALSync/MALSync#905]
I don't think Flame Scans does any manga, but you still added support. And now because of that, MAL-Sync is syncing manhwas with similar names to manga to my MAL. I don't read manga and I definitely don't want manga I have never read on my MAL. The one I was reading is `Solo Necromancy` and MAL-Sync is syncing with `Necromance`. Please do something about this. MAL-Sync isn't very accurate when it comes to manhwa and it was a mistake to add a manhwa scanlation site as a manga site for MAL-Sync. I hope you can remove manhwa sites from MAL-Sync or do something about it

**Comment by lolamtisch** [comment]
No I cant do anything, but you can do something about it.
MAL just does not have/allow many manhwas. Anilist is the better page for that. 
Switch to Anilist or set the entry to "No entry Entry on Myanimelist" in the correction menu. This way it will just track the progress on a localy saved entry instead.
![Wrong recognition](https://user-images.githubusercontent.com/12599334/135371320-7345059f-04ed-4ffa-b45a-2b2de07653c8.gif)

**Comment by henrik9999** [comment]
Or disable the page in the settings

**Comment by GhostUnamused** [comment]
ah ok thanks

**Comment by GhostUnamused** [comment]
> Or disable the page in the settings

How do I do that? Please help me

**Comment by lolamtisch** [comment]
![image](https://user-images.githubusercontent.com/12599334/140282145-57319570-dad3-4b9e-bdda-3d7e5da8164b.png)
