### ISSUE TITLE
[Website Request] <Website Name> safari

### ISSUE THREAD

**Issue by Akira024** [MALSync/MALSync#907]
**PLEASE READ THIS**

I acknowledge that:

- I have checked that the website is not already supported: https://github.com/MALSync/MALSync/blob/master/pages.md
  - If supported but it is not working, then please open an bug issue: https://github.com/MALSync/MALSync/issues/new/choose
- I have searched the existing GitHub issues and this website does **NOT** have an open request
- I will fill out the title and the information in this template
- Support won't be added for pages that:
  - Are clones of another page
- If you are the owner of the website, then please contact us directly on discord.

**DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT**

---

## Website
- Name: ?
- Link: ?
- Language(s): ?

## Other details

**Comment by henrik9999** [comment]
Support for the Safari browser as a extension won't be added. Use tampermonkey and the malsync Userscript if you want to use it on safari

**Comment by Akira024** [comment]
Thank you so much
