### ISSUE TITLE
Syncing with MAL. AL, etc. at the same time?

### ISSUE THREAD

**Issue by GhostUnamused** [MALSync/MALSync#913]
I was wondering if it was possible to sync with MAL and AL at the same time while watching or maybe if it's too much release another MAL-Sync extension so we can sync with 2 sites at once. Is it possible?

**Comment by henrik9999** [comment]
No but you could use https://github.com/MALSync/MALSync/wiki/List-Sync

**Comment by funforgiven** [comment]
Could we learn about why you are not considering implementing this? I know there is list sync but it only runs once a day so watch history is delayed in other services.
