### ISSUE TITLE
Animepahe links dont work

### ISSUE THREAD

**Issue by GaganRohith** [MALSync/MALSync#921]
**Describe the bug**
I can't open the next episode of anime or continue watching pages from extension when I watch in animepahe

**Steps to reproduce the behaviour:**
complete watching 1 episode of any anime in https://animepahe.com/
close the tab and open a new one click on continue watching or next episode buttons in the extension

**Additional information:**
 - Browser: Chrome
 - Type: Extension
 - Url: https://animepahe.com/

![image](https://user-images.githubusercontent.com/72659340/136063761-76a2b63d-63db-4f19-8558-0a3386cb015d.png)

**Comment by henrik9999** [comment]
#840
