### ISSUE TITLE
[Website Request] ADN

### ISSUE THREAD

**Issue by Fu2chN** [MALSync/MALSync#942]
## Website
- Name: ADN
- Link: https://animedigitalnetwork.fr/
- Language(s): VOSTFR / VF

## Other details
It's the 3rd popular French-speaking platform next to Wakanim and Crunchyroll.

**Comment by Guilamb** [comment]
Hi, @skytowz worked on it and submitted a pull request that adds ADN pages support.
https://github.com/MALSync/MALSync/pull/1568

**Comment by Guilamb** [comment]
@henrik9999 this could be closed, ADN have been added.
