### ISSUE TITLE
Episode Time Watched doesn't show up anymore

### ISSUE THREAD

**Issue by therealishida** [MALSync/MALSync#963]
I'm an animekisa user. For the last couple of days, my episodes don't play from where i left off. There isn't any link on the bottom of the screen to resume from [ __:__ ].

**Comment by henrik9999** [comment]
You will need to add the custom domain like below. There is a button Custom Domains in the settings. You possibly need to restart the browser afterwards.

Video Iframe -> https://gogoplay1.com/
Video Iframe -> https://gogoplay2.com/
Video Iframe -> https://sbplay1.com/
Video Iframe -> https://fplayer.info/
