### ISSUE TITLE
[Feature Request] Disable console logs.

### ISSUE THREAD

**Issue by DATL4G** [MALSync/MALSync#964]
Please add an option to disable console logs.
It's a bit annoying to get a bunch of logs when developing something for a site supported by this plugin as it prints a lot details in log.
A simple switch in the options to disable these would be nice.

**Comment by lolamtisch** [comment]
Try disabling verbose logging, it removes a lot the recurring logs. Or just disable the extension when working on the page.

**Comment by DATL4G** [comment]
@lolamtisch The logs aren't verbose level, it's info level. And disabling info level while developing isn't an option :)

**Comment by lolamtisch** [comment]
Then there should't be any recurring spamy logs anymore. Which log entry does anoy you?

**Comment by DATL4G** [comment]
What about these?
![image](https://user-images.githubusercontent.com/46448715/140430872-84b9eb5e-dcf5-4738-b659-334677cb840a.png)

**Comment by lolamtisch** [comment]
There is nothing spamy in them. We wont add an option to disable logs, as it makes debugging a pain with users that just enable random options. But you could just filter out the malsync log entries. `-` can be used to exclude words.
`-Mal -search -rules -global -sync` These filter most entries out.
![image](https://user-images.githubusercontent.com/12599334/140431119-ef804a4d-1a18-4b2f-8bff-e7886f270a8c.png)

**Comment by DATL4G** [comment]
> There is nothing spamy in them.

Well I think this is nothing we can discuss about as it's obviously spamming the whole console log.
The screenshot is fullscreen on a 1920x1080 resolution and even on 2560x1440 the console is full after loading the video.

> [...] it makes debugging a pain with users that just enable random options.

This isn't true at all. Sure it takes an extra step to tell people to disable the option then, however this can be added in the README + an info in the options as others already offer.

Excluding the words is an acceptable option **for now**.

**Comment by lolamtisch** [comment]
![image](https://user-images.githubusercontent.com/12599334/140476183-0041fc01-d5a6-4f59-8b33-6c1ab94f5084.png)
Additional there is still this option to make sure the other contexts dont bleed into the website. But it depends on what you are doing.
