### ISSUE TITLE
Alpha Scans site with problem on detecting new chapters.

### ISSUE THREAD

**Issue by arthurmessi** [MALSync/MALSync#983]
**Alpha Scans site updates are note detected by MAL-Sync, the new chapters are not identified and not showed on the interface.**

**https://alpha-scans.org/manga/1638144121-tower-of-god/ for example, this page has the last chapter identified as the 517, but the 519 is already out. **

**Additional information:**
 - Browser: chrome
 - Type: Extension
 - Url: https://alpha-scans.org

**Comment by lolamtisch** [comment]
Seems fine now.

The new chapter system does only have a few sources, so it could sometimes happen that it is off, if the other sources are slower.
