### ISSUE TITLE
Twitter SNS not functioning

### ISSUE THREAD

**Issue by LilithAbundantia** [MALSync/MALSync#987]
**Describe the bug**
I recently set up the Twitter auto-posting feature and it doesn't post anything, I don't even get a confirmation message when I ask for one in settings, just doesn't work. Have checked permissions and they look all clear. I also checked the forums and someone mentioned turning the settings off and on again so I tried that too, nothing.

Turn on SNS settings for all available options on the list settings page, hit the submit button, and then use the extension to navigate to a show/manga. Click "ok" in the start watching/reading box. (To my understanding this is how it's meant to work so I genuinely don't know what I'm doing wrong.)

**Additional information:**
 - Browser: <chrome>
 - Type: <Just using MAL sync>

**Comment by henrik9999** [comment]
That's a issue from MyAnimeList and not us for some reason they don't do the SNS when we update over the API
