### ISSUE TITLE
Completed shade is hard to read on MangaNato

### ISSUE THREAD

**Issue by PythonCoderAS** [MALSync/MALSync#994]
**Describe the bug**
When using the setting to fill in completed chapters with blue, the resulting fill makes the text hard to read on MangaNato.

![image](https://user-images.githubusercontent.com/13932583/145647723-02379ba4-cade-4a5e-aa2c-d7bbf149a81e.png)

**Steps to reproduce the behavior:**

- Use the option to fill in completed chapters with blue
- Visit a MangaNato manga page where some chapters have been read
- View chapter list

**Additional information:**
 - Browser: Chrome
 - Type: Extension
 - Url: https://manganato.com/manga-lu988529

**Comment by lolamtisch** [comment]
Will be fixed in the next release
![image](https://user-images.githubusercontent.com/12599334/146783208-8f290da3-62eb-45b8-a148-0ffa08e441af.png)
![image](https://user-images.githubusercontent.com/12599334/146783235-897e0c4c-c509-455f-a054-e9ae43d9aed6.png)

**Comment by PythonCoderAS** [comment]
I like this approach, but why red? It seems a lighter shade of blue would make sense.

**Comment by lolamtisch** [comment]
@PythonCoderAS It is the orange that manganato uses in the light theme, just with less opacity. There is nothing red I think you should check your screen XD

**Comment by PythonCoderAS** [comment]
Oh lol it looks more pinkish to me.
